---
title: Las dos revelaciones
---

# LAS DOS REVELACIONES

<p>
<Pin lang="es">99</Pin> <Pin lang="en">112</Pin> Consideraremos ahora las cinco etapas de la ceremonia de la Iniciación, y son:
</p>

1. La "Presencia" revelada.
2. La "Visión" percibida.
3. La aplicación del Cetro, que afecta
   1. a los cuerpos,
   2. a los centros,
   3. al vehículo causal.
4. El juramento.
5. La revelación del "Secreto" y de la Palabra.
   
Estos puntos son enumerados en su debido orden y debe recordarse que tal orden no es arbitrario y conduce al iniciado de una revelación a otra, hasta la etapa culminante donde se le comunica uno de los secretos y una de las cinco palabras de poder que le abren los distintos planos, con todas sus evoluciones. Todo lo que aquí se intenta es indicar las cinco etapas principales que abarcan lógicamente la Ceremonia de la Iniciación: el estudiante debe tener presente que cada una es en sí una ceremonia completa, factible de ser clasificada en forma detallada.

Trataremos los distintos puntos, deteniéndonos brevemente en cada uno, pero recordando que las palabras limitan y restringen el verdadero significado. <Pin lang="en">113</Pin>

## La Revelación de la "Presencia".

Durante los períodos finales del cielo de encarnaciones, donde el hombre hace malabarismos con los pares de opuestos y que, a través de la discriminación está siendo consciente de la realidad y de la irrealidad, surge en su mente la comprensión de que él mismo es una Existencia inmortal, un Dios imperecedero y una parte de lo Infinito. Cada vez se hace más evidente el eslabón entre el hombre en el plano físico y este Regidor interno, hasta que sobreviene la gran revelación. Llega un momento en la existencia del hombre en que se encara conscientemente con su yo <Pin lang="es">100</Pin> real, y sabe que él es ese yo en realidad y no en teoría. Adquiere conciencia del Dios interno, no por medio del oído ni de su atención a la voz interna que dirige y controla, denominada la "voz de la conciencia", sino por medio de la percepción y de la visión directa. Ahora responde no sólo a lo que oye sino también a lo que ve.

Sabemos que los primeros sentidos que el niño desarrolla son: el oído, el tacto y la vista. El niño percibe el sonido y vuelve la cabeza; palpa y toca; finalmente ve conscientemente y estos tres sentidos coordinan la personalidad. Éstos son los tres sentidos vitales. Le siguen el gusto y el olfato, pero no son indispensables, en la vida y aunque carezca de ellos, el hombre no tiene ningún obstáculo para establecer contactos en el plano físico. En la senda del desarrollo interno o subjetivo, rige la misma secuencia.

*El oído* --responde a la voz de la conciencia, a medida que guía, dirige y controla. Esto abarca el período de la evolución estrictamente normal.

*El tacto* --responde al control o vibración, y reconoce lo que está fuera de una unidad humana <Pin lang="en">114</Pin> separada en el plano físico. Abarca el período del gradual desenvolvimiento espiritual, los senderos de probación y del discipulado, hasta el portal de la iniciación. El hombre entra periódicamente en contacto con lo que es superior a él, adquiere conciencia del "toque" del Maestro, de las vibraciones egoica y grupal, y por medio del sentido oculto del tacto se familiariza con lo interno y sutil. Procura alcanzar aquello que concierne al yo superior y al tocar las cosas invisibles, se habitúa a ellas.

*La vista* --esa visión interna que se adquiere por medio del proceso de la iniciación y que después de todo sólo es el reconocimiento de las facultades siempre presentes aunque desconocidas. Así como el niño nace con los ojos perfectamente sanos y llega un día en que lo primero que se observa es su reconocimiento consciente de lo que ve, así también ocurre con el individuo que se está desarrollando espiritualmente. El medio para la visión interna siempre existió y lo que puede verse está siempre presente, pero la mayoría de las personas no lo reconocen.

Este "reconocimiento" por el iniciado, es el primer gran paso en la ceremonia de la iniciación y hasta no trascenderlo se postergan las demás etapas. En cada iniciación el reconocimiento es distinto y puede sintetizarse de la manera siguiente:

El ego, reflejo de la mónada, es en sí una triplicidad, como lo es todo en la naturaleza. Refleja los tres aspectos de la divinidad, así como la mónada refleja, en un plano superior, los tres <Pin lang="es">101</Pin> --voluntad, amor-sabiduría e inteligencia activa- de la Deidad. Por lo tanto:

En la primera iniciación, el iniciado llega a ser consciente del tercer aspecto, o aspecto inferior del ego, el de la inteligencia activa. Se enfrenta con la manifestación del gran ángel solar (pitri) que es él mismo, el auténtico yo. Entonces <Pin lang="en">115</Pin> conoce, sin lugar a duda, que esa manifestación de inteligencia es esa Entidad eterna que, a través de las épocas, ha demostrado sus poderes en el plano físico por medio de sucesivas encarnaciones.

En la segunda iniciación, esta gran Presencia se ve como una dualidad, y otro aspecto brilla ante él. Se da cuenta que esta radiante Vida identificada consigo mismo, no sólo actúa con inteligencia, sino que su origen es amor-sabiduría. Fusiona su conciencia con dicha Vida y se hace uno con ella, a fin de que en el plano físico, mediante el yo personal, esa Vida se vea como amor inteligente, expresándose a sí mismo.

En la tercera iniciación, el ego se presenta ante el iniciado como triplicidad perfeccionada. No sólo conoce el yo como amor inteligente activo, sino que se revela también como voluntad o propósito fundamental, con el cual el hombre se identifica inmediatamente y sabe que los tres mundos no contienen nada para él en el futuro, sólo sirven como esfera de servicio activo, manifestándose como amor para lograr un propósito, oculto durante edades en el corazón del yo. Habiéndose revelado ese propósito, puede entonces colaborar con él inteligentemente y así madurarlo.

Estas profundas revelaciones brillan ante el iniciado en forma triple:

Como *radiante existencia angélica*, vista con el ojo interno, con la misma exactitud y criterio, análogamente a como un hombre enfrenta a otro. El gran ángel solar, que constituye el hombre real y su expresión en el plano de la mente superior, es literalmente su divino antecesor, el "Observador" que, durante largos ciclos de encarnaciones, se ha sacrificado para que el hombre pueda SER. <Pin lang="en">116</Pin>

Como esfera de fuego radiante, vinculada con el iniciado que está ante ella, por el hilo de fuego magnético que pasa a través de todos sus cuerpos y termina en el centro del cerebro físico. Este "hilo de plata" (como se lo llama inexactamente en La Biblia, al describir su liberación del cuerpo físico y la subsiguiente abstracción) emana del centro cardíaco del Ángel solar, vinculando así corazón y cerebro -esa gran dualidad que manifiesta amor e inteligencia en este sistema solar. La esfera ígnea está análogamente vinculada del mismo modo, con muchas otras que <Pin lang="es">102</Pin> pertenecen al mismo grupo y rayo. Este hecho concreto demuestra que todos somos uno en los planos superiores. Una sola vida palpita y circula a través de todo, mediante hilos ígneos y es parte de la revelación que el hombre recibe, ante la "Presencia", con sus ojos ocultamente abiertos.

Como *policromo Loto de nueve pétalos*, que están colocados en tres círculos alrededor de un conjunto central de tres pétalos herméticamente cerrados, los cuales protegen lo que en los libros orientales se denomina "la Joya en el Loto". Este Loto es de rara belleza, palpitante de vida y radiante, en todos los colores del arco iris; en las tres primeras iniciaciones los tres círculos se revelan por orden correlativo hasta que en la cuarta iniciación el iniciado se encuentra ante una revelación mayor y conoce el secreto de lo que encierra el capullo central. A este respecto, la tercera iniciación difiere algo de las otras, pues por el poder de un Hierofante aún más excelso que el Bodhisattva, se conoce por primera vez el fuego eléctrico del espíritu puro, latente en el corazón del Loto.

Las palabras "ángel solar", "esfera de fuego" y "loto", ocultan un aspecto del misterio central de la vida humana, pero sólo será evidente para quienes tienen ojos para ver. La significación mística de estas frases gráficas constituirá una celada o motivo de incredulidad para el hombre que <Pin lang="en">117</Pin> intente materializarlas en forma indebida. En estos términos se oculta la idea de una existencia inmortal, de una Entidad divina, de un gran centro de energía ígnea y del pleno florecimiento de la evolución, y así deben ser considerados.

En la cuarta iniciación, el iniciado comparece ante la Presencia de ese aspecto de Sí mismo denominado "Su Padre en los Cielos". Se lo enfrenta con su propia mónada, esa esencia espiritual pura, existente en el plano más elevado, excepto uno, que es para su ego o yo superior, lo que ese ego es para la personalidad o yo inferior.

La mónada se manifiesta en el plano mental en forma triple, por medio del ego; pero todavía faltan todos los aspectos de la mente, tal como la comprendemos. El ángel solar con quien estaba en contacto, se retira; la forma mediante la cual actuaba (el cuerpo egoico o causal) desaparece y sólo queda el amor-sabiduría y esa voluntad dinámica que es la característica principal del espíritu. El yo inferior sirvió para los propósitos del ego y fue descartado; de igual modo el ego sirvió a los designios de la mónada y ya no hace falta; el iniciado se ve libre de ambos, plenamente liberado y es capaz de entrar en contacto con la mónada, así como anteriormente aprendió a entrar en contacto con el ego. Para las restantes manifestaciones en los tres mundos, <Pin lang="es">103</Pin> está regido sólo por la voluntad y el propósito autoiniciados y crea su cuerpo de manifestación, controlando (dentro de las limitaciones kármicas) sus propios períodos y ciclos. El karma que aquí se menciona es el planetario, no el personal. En la cuarta iniciación entra en contacto con el aspecto amor de la mónada y, en la quinta, con el aspecto voluntad, así completa sus contactos, responde a todas las vibraciones necesarias y es el amo de los cinco planos de la evolución humana.

Además, en las iniciaciones tercera, cuarta y quinta, se hace consciente de esa "Presencia" que encierra en sí esa entidad espiritual, su propia mónada, <Pin lang="en">118</Pin> y la ve como una con el Logos planetario. A través del canal de su propia mónada ve los mismos aspectos (que esa mónada personifica) en escala más amplia, revelándolo así al Logos planetario, el cual anima a todas las mónadas de Su rayo. Esta verdad es casi imposible de expresar en palabras y concierne a la relación que tiene el punto eléctrico de fuego, la mónada, con la estrella de cinco puntas, que revela al iniciado la Presencia del Logos planetario. Esto es prácticamente incomprensible para el hombre común, aunque este libro fue escrito para él.

En la sexta iniciación, el iniciado actúa conscientemente como aspecto amor de la mónada, y es llevado (por medio de su "Padre") a un reconocimiento más vasto; llega a ser consciente de esa Estrella que encierra a su estrella planetaria, así como ésta incluyó antes a su propia y diminuta "chispa". De este modo se pone en contacto consciente con el Logos solar y llega a conocer dentro de sí mismo, la Unicidad de toda vida y manifestación.

Este reconocimiento se expande en la séptima iniciación, a fin de que dos aspectos de la Vida una lleguen a ser realidades para el emancipado Buda.

En forma gradual el iniciado llega frente a la Verdad y a la Existencia. Será evidente para los estudiantes reflexivos, que la revelación de la Presencia tiene que preceder a las demás revelaciones. Esto introduce en la mente del iniciado los conocimientos fundamentales siguientes:

Se justifica la fe que ha sustentado durante épocas y la esperanza y la creencia se fusionan en un hecho autocomprobado. La fe se pierde de vista y las cosas invisibles son vistas y conocidas, Ya no duda, y por su propio esfuerzo el iniciado se convierte en conocedor.

La unicidad con sus hermanos queda comprobada, y reconoce el lazo indisoluble que en todas partes lo vincula a sus semejantes. La hermandad ya no es una teoría, sino un hecho <Pin lang="en">119</Pin> científicamente <Pin lang="es">104</Pin> comprobado, del cual no puede dudarse, como tampoco de la separatividad de los hombres en el plano físico.

La inmortalidad del alma y la realidad de los mundos invisibles quedan para él comprobados y establecidos; antes de la iniciación esta creencia estaba basada en una breve y fugaz visión y en firmes convicciones internas (resultado del razonamiento lógico y de la intuición, en gradual desarrollo), ahora se basa en la percepción y en el reconocimiento de su propia naturaleza inmortal, fuera de toda controversia.

Comprende el significado y la fuente de energía y puede empezar a manejar el poder con precisión y dirección científicas. Sabe de donde extrae la energía, pues ha tenido una vislumbre de los recursos disponibles de la energía. Antes sabía que existía y la utilizaba ciegamente y a veces en forma imprudente, ahora, dirigido por la "mente abierta", la percibe y puede colaborar inteligentemente con las fuerzas de la naturaleza.

La revelación de la Presencia produce de muchas maneras resultados definidos en el iniciado, y la Jerarquía considera que éste es un preámbulo necesario para ulteriores revelaciones.

## La Revelación de la Visión.

La próxima importante revelación es la de la Visión, pues ha llevado al individuo a enfrentar a Aquél con quien ha tenido que ver durante incontables épocas, despertando en él la comprensión inquebrantable de la unicidad de la vida fundamental, al manifestarse a través de las vidas menores. La primera revelación concierne a lo indefinible e inimitable y es (para la mente finita) infinito en su abstracción y absolutismo. La segunda revelación concierne al tiempo y espacio, e involucra el reconocimiento por el iniciado -mediante el sentido de la visión oculta recientemente despertado-, de <Pin lang="en">120</Pin> la parte que ha desempeñado y debe desempeñar en el plan y posteriormente la parte del plan mismo, en lo que concierne a

1. su Ego
2. su grupo egoico
3. su rayo grupal
4. su Logos planetario

En esta cuádruple captación está descripto el conocimiento gradual que corresponde al proceso de las cuatro iniciaciones que preceden a la liberación final.

En la primera iniciación se da cuenta definidamente de la parte poco evidente que le corresponde en su vida personal durante el intervalo desde la revelación hasta la segunda iniciación. Esto puede requerir una o varias vidas. Sabe la dirección <Pin lang="es">105</Pin> que debe tomar; conoce algo de su participación en el servicio de la raza; ve el plan como un todo, en lo que a él concierne, como un pequeño mosaico dentro del diseño general; adquiere conciencia de cómo puede servir -con su particular tipo de mentalidad, su conjunto de facultades mentales o de las otras, y de sus diversas capacidades- y lo que debe realizar antes de poder hallarse de nuevo ante la Presencia y recibir una amplia revelación.

En la segunda iniciación ve la parte que su grupo egoico desempeña en el esquema general. Llega a ser más consciente de las distintas unidades de grupo con las cuales está intrínsecamente asociado; las reconoce por sus personalidades, si están encarnadas, y en cierto modo ve cuáles son las relaciones kármicas entre él, los grupos y los individuos; obtiene la visión interna del propósito específico grupal, y de su relación con otros grupos. Entonces puede actuar con mayor seguridad y su intercambio con otros individuos, en el plano físico, será más firme; puede ayudarlos y ayudarse a sí mismo a ajustar el karma y, por lo tanto, acercarse más <Pin lang="en">121</Pin> rápidamente a la liberación final. Las relaciones grupales se consolidan, y los planes y propósitos pueden impulsarse más inteligentemente. A medida que prosigue esta consolidación de las relaciones grupales, produce en el plano físico esa concertada acción y unidad inteligente del propósito, que da por resultado la materialización de los ideales superiores y la adaptación de la fuerza para el sabio desarrollo de los fines de la evolución. Cuando esto llega a cierta etapa, las unidades que forman los grupos han aprendido a trabajar juntas y a estimularse mutuamente, de manera que pueden adquirir un mayor conocimiento, que dará como resultado mayor capacidad para ayudar.

En la tercera iniciación se le revela al iniciado la finalidad del subrayo del rayo al cual pertenece su ego. Todas las unidades egoicas pertenecen a algún subrayo del rayo monádico. Este reconocimiento se le otorga al iniciado, a fin de capacitarlo para encontrar oportunamente por sí mismo (siguiendo la línea de menor resistencia) el rayo de su mónada. El subrayo lleva en su corriente de energía muchos grupos de egos y no sólo tiene conciencia de su grupo egoico y de su inteligente finalidad, sino de muchos otros grupos similares. Su energía se dirige conjuntamente hacia un objetivo claramente definido.

Habiendo aprendido algo sobre las relaciones grupales y desarrollado la capacidad de trabajar con unidades en formación grupal, el iniciado aprende el secreto de la subordinación del grupo al bien del conjunto de grupos. Esto se manifiesta en el plano físico como capacidad para trabajar sabia, inteligente y armónicamente <Pin lang="es">106</Pin> con distintos individuos, colaborar en grandes planes y ejercer una amplia influencia.

Se le revela una parte de los planes del Logos planetario y esta visión incluye la revelación del plan y del propósito en lo que al planeta concierne, aunque todavía la <Pin lang="en">122</Pin> visión sea confusa respecto a esos planes, en su relación planetaria. Esto lleva al iniciado, por medio de una serie de graduados conocimientos, a los portales de la cuarta iniciación. Con la total liberación del iniciado de las ataduras en los tres mundos y la ruptura de todas las ligaduras de las limitaciones kármicas, amplía enormemente la visión y puede decirse que por primera vez se da cuenta de la amplitud del propósito planetario y del karma en el esquema. Habiendo ya ajustado su karma personal, relativamente de poca importancia, puede dedicarse a agotar el karma planetario y también abocarse a desarrollar los planes de largo alcance de esa gran Vida que incluye a todas las vidas menores. No sólo alcanza el pleno reconocimiento del propósito y los planes de toda la evolución en su propio esquema planetario, la Tierra, sino que incluye en su radio de conocimiento, ese esquema planetario que es el complemento o polo opuesto de nuestra Tierra. Comprende la interrelación existente entre los dos esquemas y se le revela el vasto propósito dual. Se le demuestra que este plan debe convertirse en un solo plan unido y de allí en adelante dedica todas sus energías a colaborar en forma planetaria, a medida que el plan se desarrolla, mientras trabaja con las dos grandes evoluciones en nuestro planeta, la humana y la dévica, y a través de ellas. Esto concierne al establecimiento de los reajustes y a la aplicación gradual de la energía para estimular los diversos reinos de la naturaleza y, mediante la fusión de todas las fuerzas de la naturaleza, acelerar la interacción de la energía entre los dos esquemas. De este modo los planes del Logos solar pueden consumarse a medida que se desarrollan por medio de los dos Logos planetarios. El manejo de la energía solar, en pequeña escala, es ahora privilegio del iniciado, pues no sólo se lo admite en la cámara del concilio de su propia Jerarquía, sino que se le permite asistir cuando otros agentes planetarios están <Pin lang="en">123</Pin> reunidos con el Señor del Mundo y los dos grandes dirigentes departamentales.

En la quinta iniciación la visión le otorga al iniciado una perspectiva más amplia y ve un tercer esquema planetario que, con los otros dos, forma uno de los triángulos de fuerza, necesarios en el desarrollo de la evolución solar. Así como toda manifestación prosigue por medio de la dualidad y la triplicidad, para retornar a la síntesis eventual, así estos esquemas, que sólo son centros de fuerza en el cuerpo de un Logos solar, actúan primero como unidades separadas que viven su propia vida integral, <Pin lang="es">107</Pin> luego como dualidades, por el intercambio de fuerza a través de dos esquemas, pues en esta forma se ayudan, complementan y estimulan mutuamente y, finalmente, como un triángulo solar, que hace circular la fuerza de un punto a otro, de un centro a otro, hasta que la energía es fusionada y sintetizada y los tres actúan en forma unida.

Cuando el adepto de la quinta iniciación puede actuar de acuerdo con los planes de los tres Logos implicados, colaborando con ellos cada vez con mayor capacidad a medida que transcurre el tiempo, está preparado para la sexta iniciación, que lo admitirá a cónclaves superiores. Así llega a participar no sólo de los propósitos planetarios, sino también de los solares.

En la sexta iniciación posee la más maravillosa visión de toda la serie. Ve el sistema solar como una unidad y recibe una breve revelación que abre ante su asombrado entendimiento los propósitos fundamentales del Logos solar, viendo por primera vez el conjunto de planes con todas sus ramificaciones.

En la séptima iniciación su visión penetra más allá del "círculo no se pasa" solar y puede ver lo que ha conocido como fundamental hecho teórico, que nuestro Logos solar está implicado en los planes y propósitos de una Existencia superior y que el sistema solar es sólo uno de los numerosos centros de fuerza y por su intermedio se está expresando una Entidad cósmica mucho más grande que <Pin lang="en">124</Pin> nuestro Logos solar. En todas estas visiones subyace un gran propósito: la revelación de la unidad esencial y el descubrimiento de esas relaciones internas que, una vez conocidas, tenderán, en forma cada vez más plena, a impulsar al iniciado a servir abnegadamente y lo convertirá en un trabajador de la síntesis, la armonía y la unidad fundamental.

La ceremonia de la Iniciación, donde se le abren los ojos al iniciado para ver y comprender, se divide en tres partes, que no obstante son un solo proceso:

1. El pasado se despliega ante él; se ve a sí mismo desempeñando muchos papeles, comprendiendo que sólo constituyen la gradual conducción de sus fuerzas y facultades hasta el punto en que pueda servir a su grupo y con el grupo. Se ve y se identifica -según la iniciación-

   1. con él mismo, en muchas vidas anteriores,
   2. con su grupo, en anteriores grupos de vida,
   3. con su rayo egoico, mientras afluye a través de muchos cielos, con su Logos planetario, cuando actuó en el pasado, a través de muchas evoluciones y reinos en todo el esquema,<Pin lang="es">108</Pin> y así sucesivamente, hasta que se identifica con el pasado de la Vida una, que fluye a través de todos los esquemas planetarios y evoluciones del sistema solar, lo cual despierta en él la resolución de agotar karma y de saber (al ver las causas del pasado) cómo debe realizarlo.

2. En el presente, se le revela el trabajo específico que debe realizar en el cielo menor inmediatamente implicado. Esto significa que no ve tan sólo lo que le concierne, en determinada vida, sino que reconoce la <Pin lang="en">125</Pin> parte inmediata del plan -quizás implique varios de sus pequeños cielos llamados vidas- que el Logos planetario trata de ver consumado. Entonces puede decirse sin lugar a dudas, que conoce su trabajo y puede dedicarse a su tarea con clara comprensión de por qué, cómo y cuándo.
3. En el futuro, se le concede, a fin de estimular al iniciado, una visión de la consumación final, de un esplendor más allá de toda descripción, con destacados puntos que indican los pasos principales para llegar a esa consumación. Durante un breve instante ve cómo será el esplendor y ese sendero de radiante belleza que fulgura cada vez más hasta el día perfecto. En las primeras etapas ve la gloria de su perfeccionado grupo egoico y, posteriormente, la radiación de un determinado tipo y color, que fluye del rayo que lleva en su seno a los perfectos hijos de los hombres y, aún más tarde, obtiene una vislumbre de la perfección de ese gran Ser, que es su propio Logos planetario, hasta que finalmente se le revela la perfección de toda belleza y la radiación que incluye a todos los otros rayos de luz , el sol brillando en toda su fuerza, el Logos solar en el momento de la consumación del propósito.
