---
title: Observaciones preliminares
---

# OBSERVACIONES PRELIMINARES

## Los Tres Aspectos del Hombre

## OBSERVACIONES DE PREFACIO

<p><Pin lang="es">15</Pin> Al estudiar y considerar cuidadosamente las ideas expuestas en este libro deben tenerse presente ciertos conceptos básicos:</p>

1. Primero, que lo más importante para el estudiante no es la personalidad de determinado instructor, sino el grado de verdad que éste representa, de ahí la capacidad para discernir entre la verdad, la verdad parcial y lo falso.
2. Segundo, que *el acrecentamiento de la enseñanza esotérica trae acrecentada responsabilidad exotérica*. Cada estudiante debe hacer un consciente balance de sí mismo, y recordar que la comprensión llega aplicando al problema y medio ambiente inmediatos el grado de verdad captada, y que la conciencia se expande empleando la verdad impartida.

:::note Recuerda

El acrecentamiento de la enseñanza esotérica trae acrecentada responsabilidad exotérica

:::

3. Tercero, que la adhesión dinámica en el sendero elegido y una firme perseverancia para vencer y permanecer inconmovible ante todo lo que pueda acontecer, son requisitos indispensables que conducen al portal de acceso a un reino, a una dimensión y a un estado del ser, conocido interna o subjetivamente. Este estado de comprensión produce cambios en la forma y en el medio ambiente, comparables a su poder.

Estas tres sugerencias merecen un minucioso estudio y su significación deberá ser captada en cierta medida, antes de lograr un real progreso. No me corresponde indicar la aplicación individual y personal de las enseñanzas impartidas. Esto lo debe hacer cada estudiante por sí mismo.

Has conservado inteligentemente las enseñanzas, libre de toda autoridad extraña, y no hay en tus <Pin lang="en">4</Pin> libros principios esotéricos de autoridad o respaldo jerárquico, tales como los que han producido las estrechas limitaciones de ciertos organismos y grupos eclesiásticos tan diferentes como la Iglesia Católica, la Ciencia Cristiana y aquellos que creen en la inspiración verbal de las Escrituras y en numerosas asociaciones denominadas esotéricas. La desgracia de muchos grupos ha sido ese constante rumoreo: «Aquellos que saben, desean...» «El Maestro dice» «Los Grandes Seres Ordenan... » y el grupo, como rebaño de ovejas, se atropella ciegamente en el afán de obedecer. Creen que mediante su mal orientada devoción se relacionarán con ciertos personajes autorizados, acortando así el camino para llegar al cielo.

<p><Pin lang="es">16</Pin> Has sabido conservar y cuidar sabiamente los libros, de las reacciones de aquellos que pretenden ser maestros, adeptos e iniciados. Mi anonimato y estado deben ser respetados, y mi rango debe ser considerado sólo como el de un estudiante más avanzado, el de un aspirante a esa expansión de conciencia, que para mí significa un paso más. Sólo es importante la parte de verdad que pueda exponer; sólo es vital la inspiración y la ayuda que pueda dar a cualquier peregrino en el sendero; lo que he aprendido por medio de la experiencia está a disposición de todo aspirante sincero; y la amplitud de visión que puedo impartirles (debido a que he escalado la montaña un poco más), es mi principal aporte. Los estudiantes son libres de reflexionar sobre estos puntos y de prescindir de inútiles especulaciones acerca de las informaciones detalladas sobre personalidades insignificantes y condiciones ambientales.</p>

El tema a tratar será la Magia del Alma, y el pensamiento clave de todo lo que pueda aparecer en este libro, lo hallarán en las palabras del Bhagavad Gita:

> "Aunque soy el que no ha nacido, el alma que no muere; aunque soy el Señor de los Seres; no obstante, como señor de mi naturaleza, me manifiesto por medio del poder mágico del Alma". B. G., IV. 6. <Pin lang="en">5</Pin>

Lo estadístico y lo académico son bases necesarias y pasos preliminares en la mayoría de los estudios científicos, pero en este libro centraremos la atención sobre el aspecto vida y la aplicación práctica de la verdad a la vida diaria del aspirante. Estudiaremos cómo llegar a ser magos prácticos y en qué forma podemos vivir mejor la vida del hombre espiritual y la del aspirante al discipulado aceptado, en esta peculiar época, estado y medio ambiente.

Para lograrlo, tomaremos las Quince Reglas para la Magia, de mi libro anterior Tratado sobre Fuego Cósmico. Las comentaré sin ocuparme de su significado cósmico o solar, o de otras analogías y correspondencias; pero aplicándolas al trabajo del aspirante y dando sugerencias prácticas para desarrollar mejor el contacto y la manifestación del alma. Daré por sentado que los estudiantes poseen ciertos conocimientos, y supongo que podrán seguirme y comprender algunos términos técnicos que me veré obligado a emplear. No trato con infantes, sino con personas maduras que han elegido determinado camino y se han comprometido a "caminar en la luz".

En este libro me propongo hacer cuatro cosas y atraer tres tipos de personas. Referente a su enseñanza, se basa sobre cuatro postulados fundamentales que intentan:

1. Enseñar las leyes de la psicología espiritual como distintas de las de la psicología mental y emocional.
2. Aclarar la naturaleza del alma humana y sus relaciones con el sistema y el cosmos. Como paso preliminar esto incluirá su relación con el grupo.
3. Demostrar las relaciones entre el yo y las envolturas que ese yo pueda utilizar, y así aclarar el pensar general respecto a la constitución del hombre.
4. Elucidar el problema de los poderes supra normales <Pin lang="en">6</Pin> y dar las reglas para su desarrollo útil y sin peligro.

Nos hallamos al final de un gran período de transición, y los reinos más sutiles de la vida nunca estuvieron tan cercanos; los fenómenos inusitados y los acontecimientos inexplicables son ahora más comunes que en épocas anteriores, y lo telepático, lo síquico y lo peculiar, atraen la atención de los escépticos, de los científicos y de quienes estudian religión. Generalmente se buscan razones para explicar la aparición de lo fenoménico, y se forman asociaciones para su investigación y demostración. Además, muchas personas se desvían del camino en el afán de promover en sí mismas condiciones síquicas y factores que producen energía y dan origen a la manifestación de peculiares poderes. Este libro tratará de adaptar la información suministrada al esquema de vida tal como lo reconocemos hoy, y demostrar cuán básicamente natural y verídico es todo aquello que se califica de misterioso. Todas las cosas están sujetas a la ley, y las leyes deben ser explicadas, ahora que el hombre ha llegado a una etapa de desarrollo en que puede apreciar más exactamente su belleza y realidad.

Tres tipos de personas responderán a la enseñanza de este libro, y son:

1. Esos investigadores de mente abierta, dispuestos a aceptar los fundamentos como hipótesis aplicables, hasta demostrar que son erróneas. Serán francamente agnósticos, pero, en su búsqueda de la verdad, deben estar dispuestos temporariamente a ensayar los métodos y seguir las sugerencias presentadas a su consideración.
2. Los aspirantes y discípulos estudiarán este tratado a fin de comprenderse mejor a sí mismos para poder ayudar al prójimo. No aceptarán ciegamente sus dictámenes, sino que experimentarán, comprobarán y corroborarán, cuidadosamente las etapas <Pin lang="en">7</Pin> y pasos expuestos aquí en esta sección de las enseñanzas de la Sabiduría Eterna.
3. Los iniciados arribarán a un significado que no será <Pin lang="es">18</Pin> evidente para los del primer grupo, y sólo es sospechado por los miembros más avanzados del segundo. Internamente conocen la verdad de muchas de las afirmaciones, pero comprenderán la actuación subjetiva de muchas de las leyes. Estas leyes de la naturaleza producen efectos en tres esferas distintas:

   1. Físicamente, donde se demuestran como efectos en la forma densa.
   2. Etéricamente, donde se manifiestan como energía que subyace detrás de esos efectos.
   3. Mentalmente, donde conciernen a los impulsos que producen los otros dos.

Tratado sobre Fuego Cósmico trata especialmente del sistema solar y sólo superficialmente de los aspectos y analogías humanas, en lo que ellas demuestran la relación de la parte con el todo y la unidad con la totalidad.

Este libro se ocupará más específicamente del desarrollo y desenvolvimiento humanos y elucidará las causas responsables de los efectos actuales, señalando el futuro y sus posibilidades y la naturaleza de las potencialidades en desarrollo.

Este libro también versará sobre cuatro postulados fundamentales, que el estudiante tendrá que aceptar en carácter de hipótesis, digna de consideración y comprobación. A ningún investigador sincero de la Sabiduría Eterna se le exige ciega aceptación de cualquier presentación de la verdad; no obstante, se le pide que mantenga una mente abierta y seriamente valore y considere las teorías e ideales, las leyes y verdades, que han llevado a muchas personas de la oscuridad a la luz del conocimiento <Pin lang="en">8</Pin> y la experiencia. Los postulados podrían ser enumerados de la siguiente manera, por orden de importancia:

1. I. El primer postulado es que existe en nuestro universo manifestado la expresión de una Energía o Vida, causa responsable de las diversas formas y de la vasta jerarquía de seres sensibles que componen la totalidad de cuanto existe. Ésta es la denominada teoría hilozoísta, aunque el término sólo sirve para confundir. Esta gran Vida es la base del Monismo, y todos los hombres iluminados son monistas. "Dios es uno", es la expresión de la verdad. Una sola vida impregna todas las formas y éstas son las expresiones en tiempo y espacio, de la energía universal central. La Vida en manifestación produce existencia y ser, por lo tanto es la causa raíz de la dualidad. Esta dualidad, que se percibe cuando está presente la objetividad, y desaparece cuando el aspecto <Pin lang="es">19</Pin> forma se desvanece, tiene muchos nombres, de los cuales y para mayor claridad podríamos enumerar los más comunes:

 |           |          |
 | --------- | -------- |
 | Espíritu  | Materia  |
 | Vida      | Forma    |
 | Padre     | Madre    |
 | Positivo  | Negativo |
 | Oscuridad | Luz      |

 Los estudiantes deben mantener en la mente esta unidad esencial, aún cuando hablen (como deberán hablar) en términos finitos de esa dualidad, que cíclicamente se evidencia en todas partes.

2. II. El segundo postulado surge del primero, y afirma que la Vida Una, que se manifiesta a través de la materia, produce un tercer factor que es la conciencia. Esta conciencia, resultado de la unión de los dos polos, espíritu y materia, constituye el alma de todas las cosas; compenetra toda sustancia o energía objetiva; subyace en todas las formas, ya sea la de esa unidad de energía que llamamos átomo o la de un hombre, un planeta o un sistema solar. Ésta es La Teoría de Autodeterminación, <Pin lang="en">9</Pin> o la enseñanza de que todas las vidas, de las cuales está formada la vida una, cada una en su esfera y modo de ser, se embeben en la materia, por así decirlo, y asumen formas por cuyo intermedio su peculiar y específico estado de conciencia puede ser comprendido y su vibración estabilizada; así pueden conocerse a sí mismas como existencias. Nuevamente la vida una se convierte entonces en una entidad estabilizada y consciente mediante el sistema solar, siendo por lo tanto esencialmente la suma total de energías de todos los estados de conciencia y de todas las formas de existencia. Lo homogéneo se vuelve heterogéneo, y sin embargo permanece siendo una unidad; el uno se manifiesta en diversidad, y no obstante, es inmutable; la unidad central es conocida en tiempo y espacio, como compuesta y diferenciada, y sin embargo cuando no existan tiempo y espacio (pues no son más que estados de conciencia) sólo permanecerá la unidad y únicamente persistirá el espíritu, además de una acrecentada acción vibratoria y la capacidad para intensificar la luz cuando retorne el ciclo de manifestación.

 Dentro de la pulsación vibratoria de la Vida una en manifestación, todas las vidas inferiores repiten el proceso de ser Dioses, ángeles, hombres y miríadas de vidas que se expresan mediante las formas de los reinos de la naturaleza y las actividades del proceso evolutivo. Todo llega a ser auto centrado y autodeterminado.

3. III. El tercer postulado fundamental es que el desenvolvimiento de la conciencia o la revelación del alma, constituye el <Pin lang="es">20</Pin> objetivo por el cual la vida adquiere forma y también el propósito por el cual se manifiesta el ser. Esto puede ser denominado La Teoría de la Evolución de la Luz. Si se tiene en cuenta que el científico moderno sostiene que la luz y la materia son términos sinónimos, haciéndose eco de las enseñanzas de Oriente, es evidente que mediante la interacción de los polos y la fricción de los pares de opuestos, surge la luz. La meta de la evolución consiste en una serie graduada de manifestaciones de luz. Velada y <Pin lang="en">10</Pin> oculta en todas las formas se halla la luz. A medida que la evolución avanza, la materia se convierte en un buen conductor de luz, demostrando así la exactitud de la afirmación de Cristo, "Yo Soy la Luz del Mundo".
4. IV. El cuarto postulado sostiene que todas las vidas se manifiestan cíclicamente. Ésta es La Teoría del Renacimiento o de la reencarnación, demostración de la ley de periodicidad.

Tales son las grandes verdades subyacentes que constituyen la base de la Sabiduría Eterna o la existencia de la vida y el desarrollo de la conciencia, mediante la cíclica adquisición de la forma.

En este tratado se hará hincapié en la minúscula vida; el hombre "hecho a imagen de Dios", que mediante la reencarnación desarrolla su conciencia hasta florecer como alma perfeccionada, cuya naturaleza es luz y cuya comprensión es la de una identidad autoconsciente. Esta unidad desarrollada debe oportunamente fusionarse, participando con plena inteligencia en esa conciencia mayor de la cual forma parte.

Antes de abocarnos a nuestro tema quizás sea útil definir ciertas palabras que emplearemos con frecuencia, para entendernos mejor y conocer la significación de los términos que utilizamos.

1. **Oculto**. Este término se refiere a las fuerzas ocultas del ser y al origen de la conducta, que producen la manifestación objetiva. La palabra "conducta" se emplea deliberadamente, porque toda manifestación en los reinos de la naturaleza es la expresión de la vida, propósito y tipo de actividad, de algún ser o existencia, y es literalmente la conducta (o naturaleza externa o cualidad) de una vida. El origen de la acción está oculto tras los propósitos de cualquier vida, sea una vida solar, una entidad planetaria, un hombre, o ese Ser que es la totalidad de los estados de conciencia y de las formas de cualquier reino de la naturaleza.
2. **Ley**. Una ley presupone una entidad superior que, <Pin lang="en">11</Pin> dotada de propósito y ayudada por la inteligencia, coordina sus fuerzas de tal modo que va madurando un plan en forma secuencial y constante. Mediante el conocimiento claro de la meta, esa entidad <Pin lang="es">21</Pin> activa los pasos y las etapas que, si se realizan ordenadamente, llevan el plan a la perfección. La palabra "ley" tal como se entiende comúnmente, da la idea de sometimiento a una actividad reconocida como inexorable e inflexible, pero que no es comprendida por el que está sujeto a ella; abarca, desde cierto punto de vista, la actitud de la unidad sumergida en el impulso grupal, y la incapacidad de la misma para cambiar el impulso o eludir la consecuencia; produce inevitablemente en la conciencia del hombre que considera estas leyes, el sentimiento de ser una víctima impelida como una hoja a merced del viento, hacia un fin, del cual sólo es posible especular, regido por una fuerza que actúa aparentemente, ejerciendo una presión ineludible y produciendo resultados grupales a expensas de la unidad. Esta actitud mental se produce inevitablemente, hasta que la conciencia del hombre puede expandirse a tal grado que llega a ser consciente de asuntos más importantes. Cuando establece contacto con su yo superior, participa en el conocimiento de lo objetivo y escala la montaña de la visión, su perspectiva cambia y su horizonte se ensancha; entonces llega a comprender que una ley es únicamente el impulso espiritual: incentivo y manifestación de la vida de ese Ser en el cual vive y se mueve. Aprende que ese impulso expresa un propósito inteligente, sabiamente dirigido y basado en el amor. Luego, comienza él mismo a aplicar la ley, trasmitiendo sabia, amorosa e inteligentemente, a través de sí mismo, todo lo que recibe de ese impulso de vida espiritual al que su organismo puede responder, trasmitir y utilizar. Deja de ser un obstáculo y comienza a trasferir. Pone fin al ciclo de vida hermética y autocentrada, y abre de par en par las puertas a la energía espiritual. Al hacer esto descubre que la ley, <Pin lang="en">12</Pin> a la cual ha odiado y recelado, es el agente vitalizador y purificador que lo impele a él y a todas las criaturas de Dios, a una gloriosa consumación.
3. **Síquico**.En lo que concierne al reino humano hay, dos tipos en manifestación de esa fuerza mencionada, y deben ser claramente captados. Una fuerza anima a los reinos subhumanos de la naturaleza energía animadora que conjuntamente con la energía de la materia y del yo, produce todas las formas. El efecto de esta conjunción es agregar a la inteligencia embrionaria de la sustancia misma, la sensibilidad latente y la respuesta, lo cual produce ese algo subjetivo que llamamos alma animal. Existen cuatro grados o estados de percepción sensoria:
   1. La conciencia del reino mineral.
   2. La conciencia del reino vegetal.
   3. La conciencia del reino animal.
   4. La conciencia de la forma animal, a través de la cual actúa el hombre espiritual que, en última instancia, no es <Pin lang="es">22</Pin> más que un sector del grupo anterior en su presentación más elevada.

 Existe también esa fuerza síquica que es resultado de la unión del espíritu con la materia sensoria del reino humano, y produce el centro síquico denominado el alma del hombre, el cual es un centro de fuerza, y la fuerza que custodia o manifiesta, pone en actividad la respuesta y percepción del alma de la vida planetaria, conciencia grupal que trae consigo facultades y conocimientos de orden distintos de los del alma animal. Éstos, finalmente, reemplazan los poderes del alma animal que limitan, deforman y aprisionan, dando al hombre una esfera de contactos y conocimientos infalibles, libre de error, que le concede "la libertad de los cielos". Los resultados de la libre <Pin lang="en">13</Pin> acción del alma del hombre sirven para demostrar la falibilidad y la relativa inutilidad de los poderes del alma animal. Aquí deseo demostrar los dos sentidos en que se emplea la palabra "síquico". Luego me ocuparé del crecimiento y desarrollo de la naturaleza síquica inferior, o del alma de los vehículos en que el hombre funciona en los tres mundos; después trataré de elucidar la verdadera naturaleza del alma del hombre y los poderes que entrarán en juego una vez que pueda hacer contacto con su propio centro espiritual, el alma, y vivir en esa conciencia del alma.

4. **Desenvolvimiento**. La vida en el corazón del sistema solar produce un desarrollo evolutivo de las energías de ese universo, que el hombre finito aún no puede imaginar. Análogamente el centro de energía denominado aspecto espiritual del hombre (mediante la utilización de la materia o sustancia), produce el desarrollo evolutivo de aquello que denominamos alma, y es lo más elevado de las manifestaciones de la forma el reino humano. El hombre es el producto más elevado de la existencia en los tres mundos. Quiero significar por hombre, el hombre espiritual, un hijo de Dios en encarnación. Las formas de todos los reinos de la naturaleza humano, animal, vegetal y mineral contribuyen a esa manifestación. La energía del tercer aspecto de la divinidad tiende a la revelación del alma o segundo aspecto, que a su vez revela el aspecto más elevado. Debe recordarse que La Doctrina Secreta [^1], de H. P. Blavátsky, expresa con exactitud esta idea, en las siguientes palabras: "Consideramos la vida como la única forma de existencia, manifestándose en lo que llamamos materia, o que separándolas incorrectamente, denominamos espíritu, alma y materia, en el hombre. Materia es el vehículo para la manifestación del alma en este plano de existencia, y el alma es el vehículo, en un plano más elevado, para la manifestación del espíritu; los tres son una trinidad sintetizada por la vida <Pin lang="en">14</Pin> que los compenetra".

 <p><Pin lang="es">23</Pin> El alma se desarrolla mediante el empleo de la materia, y llega a su culminación en el alma del hombre. Este tratado versará sobre el desarrollo de esa alma y su descubrimiento por el hombre.</p>

5. **Conocimiento**. Podría ser dividido en tres categorías: Primero, el conocimiento teórico, incluye todo lo que el hombre conoce y percibe, y que ha aceptado debido a las afirmaciones de otras personas y de los especialistas en las distintas ramas del conocimiento. Se funda en autorizadas afirmaciones y contiene elementos que permiten confiar en los escritores, conferencistas e inteligencias entrenadas que actúan en cualesquiera de los numerosos y variados campos del pensamiento. Las verdades aceptadas como tales no han sido formuladas o verificadas por quien las acepta, pues carece del entrenamiento y equipo necesarios. Los dictámenes de la ciencia, de la teología y de la religión y los descubrimientos de los filósofos y pensadores de todas partes, matizan el punto de vista y hallan rápida aceptación en la mente no entrenada, la mente común.

 Segundo, tenemos el conocimiento discriminativo que contiene una cualidad de selección, y afirma la valoración inteligente y aplicación práctica del método más específicamente científico y la utilización de la prueba, la eliminación de lo que no puede ser probado y el aislamiento de esos factores susceptibles de investigación, de acuerdo a lo que se entiende por ley. La mente razonadora, argumentadora, escolástica y concreta, es puesta en actividad con el resultado de que gran parte de lo que es infantil, imposible e inverificable, es rechazado, trayendo como consecuencia el esclarecimiento en el campo de los resultados mentales. Este proceso discriminador y científico permitió al hombre conocer gran parte de la verdad respecto a los tres mundos. El método científico, en relación con la <Pin lang="en">15</Pin> mente de la humanidad, desempeña la misma función que el método ocultista de meditación (en sus dos primeras etapas de concentración y concentración prolongada o meditación) en relación con el individuo. Por su intermedio se engendran correctos procesos mentales, y finalmente es eliminado o corregido lo no esencial y las formulaciones incorrectas de la verdad, y el constante enfoque de la atención, sea sobre un pensamiento simiente, un problema científico, una filosofía o una situación mundial, dando por resultado el esclarecimiento final y la constante infiltración de ideas correctas y sólidas conclusiones. Los pensadores más destacados en cualesquiera de las grandes escuelas de pensamiento son simples exponentes de la meditación ocultista, y los brillantes descubrimientos de la ciencia, las correctas interpretaciones de las leyes <Pin lang="es">24</Pin> de la naturaleza y la formulación de las correctas conclusiones, ya sea en los campos de la ciencia, la economía, la filosofía, la psicología o en cualquier otro campo, sólo son lo que registra la mente (y en consecuencia el cerebro) de las verdades eternas, e indican que la raza comienza a eliminar la separación entre lo objetivo y lo subjetivo, entre el mundo de la forma y el mundo de las ideas.

 Esto conduce inevitablemente al surgimiento de la tercera rama del conocimiento, la intuición. En realidad, la intuición es sólo la apreciación mental de algún factor de la creación, de alguna ley de la manifestación y de cierto aspecto de la verdad, conocido por el alma, que emana del mundo de las ideas, siendo de la naturaleza de esas energías que producen todo lo conocido y visto. Estas verdades están siempre presentes y esas leyes eternamente activas; pero únicamente a medida que la mente está entrenada y desarrollada, enfocada y abierta, pueden ser reconocidas, posteriormente comprendidas y finalmente adaptadas a las necesidades y demandas del ciclo y de la época. Siempre han existido quienes entrenaron su mente en el arte del claro pensar, enfocaron la atención en la consiguiente receptividad de la verdad, pero hasta ahora fueron muy pocos y aparecieron de tarde en tarde. Constituyen <Pin lang="en">16</Pin> las mentes descollantes de las épocas. En la actualidad son numerosas y aparecen cada vez con mayor frecuencia. Las mentes de la raza están en proceso de entrenamiento, y muchas al borde de un nuevo conocimiento. La intuición, que guía a los pensadores avanzados hacia los nuevos campos del conocimiento, es sólo la vanguardia de esa omnisciencia que caracteriza al alma. La verdad de todas las cosas existe y se la denomina omnisciencia, infalibilidad y "correcto conocimiento" en la filosofía hindú. Cuando el hombre capta un fragmento de ella y la absorbe en la conciencia racial, se lo denomina formulación de una ley o descubrimiento de uno de los procesos de la naturaleza. Hasta ahora esto ha sido una empresa lenta y fragmentaria. Más adelante, y dentro de no mucho tiempo, la luz afluirá, la verdad será revelada y la raza tomará posesión de su herencia la del alma.

En algunas de nuestras consideraciones deberán forzosamente intervenir las conjeturas. A quienes perciben una visión, vedada a los que carecen del equipo necesario para su captación, se los considera fantasiosos e imaginativos. Cuando muchos la perciben, se acepta su posibilidad, pero cuando la humanidad haya despertado y abierto los ojos, ya no se hará hincapié sobre la visión, sino que se afirmará un hecho y se enunciará una ley. <Pin lang="es">25</Pin> Tal ha sido la historia en el pasado y así será el proceso en el futuro.

El pasado, desde el punto de vista del hombre común, es esencialmente especulativo; el futuro también, pero el hombre mismo es resultado de ese pasado, y el futuro surgirá de la suma total de sus actuales cualidades y características. Si esto es verdad respecto al individuo, también lo es respecto al género humano como un todo. Esa unidad de la naturaleza que denominamos cuarto reino o reino humano, representa aquello que es producto de su herencia física; sus características son el conjunto de su desarrollo emocional y mental, y su acervo es todo aquello que ha logrado acumular, durante los ciclos en que ha <Pin lang="en">17</Pin> luchado con su medio ambiente todos los otros reinos de la naturaleza. Por lo tanto, dentro del reino humano existen potencialidades, estados latentes, características y haberes, que el futuro revelará y que a su vez determinan ese futuro.

He decidido intencionalmente comenzar con lo indefinido y no reconocido. El alma es aún una cuantidad desconocida. No ocupa un real lugar en las teorías de los investigadores académicos y científicos. No ha sido comprobada, y es considerada aún por los académicos más liberales como una posible hipótesis, pero indemostrable. No es aceptada como una realidad en la conciencia de la raza. Sólo dos grupos de personas la aceptan como tal; uno de ellos el crédulo, no evolucionado, infantil, educado en las enseñanzas de cualesquiera de las Escrituras mundiales, estando religiosamente inclinado, acepta sin indagar los postulados de la religión, tales como el alma, Dios y la inmortalidad. El otro es ese pequeño grupo de Conocedores de Dios y de la realidad, que se agranda constantemente, que sabe que el alma es un hecho por propia experiencia, pero no puede probar satisfactoriamente su existencia al hombre que acepta únicamente lo que la mente concreta puede captar, analizar, criticar y comprobar.

Los ignorantes y los sabios se encuentran en un terreno común, como sucede siempre con los extremos. Entre ellos se hallan los que no son del todo ignorantes ni sabiamente intuitivos. Constituyen la masa de personas cultas que poseen conocimientos pero no comprensión, y aún tienen que aprender a diferenciar entre lo que puede captar la mente razonadora, lo que puede ser percibido por el ojo de la mente y aquello que sólo la mente superior o abstracta, puede formular y conocer. Esto finalmente se fusiona con la intuición, "facultad conocedora" del místico inteligente y práctico que relegando la naturaleza emotiva y afectiva al lugar que le corresponde utiliza la mente como punto <Pin lang="en">18</Pin> de enfoque, observando el mundo del alma a través de ese lente.

[^1]: La Doctrina Secreta, T. l., págs. 97 - 98.
