---
title: Regla 3
---

# <Pin lang="es">78</Pin><Pin lang="en">91</Pin> REGLA TRES

> La Energía circula. El punto de luz, producto de la labor de los cuatro, crece y aumenta. Miríadas se reúnen en torno de su calor resplandeciente, hasta que merma su luz y su fuego disminuye. Después será emitido el segundo sonido.

## LA LUZ DEL ALMA Y LA LUZ DEL CUERPO

<p><Pin lang="en">93</Pin> En estas Reglas de la Magia, se hallan incorporadas las leyes del trabajo creador y los medios por los cuales el hombre puede actuar como alma encarnada. No se ocupan principalmente de las reglas que rigen el desenvolvimiento del hombre. Mucho podrá aprenderse incidentalmente sobre esto, porque el hombre progresa mediante la comprensión y el trabajo creador, pero no es éste el objetivo principal de la enseñanza.</p>

A través de los procesos de meditación que creciente y gradualmente se van sintetizando, llevados a cabo por el alma en su propio plano y en el del aspirante, el hombre manifiesta (en el cerebro físico) un punto de luz que se ha encendido ocultamente en el plano de la mente. La luz significa siempre dos cosas, la energía y su manifestación en la forma, porque luz y materia son términos sinónimos. El pensamiento del hombre y la idea del alma han encontrado un punto de contacto y ha venido a la existencia el germen de una forma mental. Cuando esta forma mental se complete, incorporará esa parte del gran Plan (en el que está trabajando la Jerarquía) que el hombre puede visualizar, captar e incluir en el plano mental. Esto es lo que se comprende por la palabra "servicio", en las primeras etapas de la aspiración del hombre, en sus primeros pasos en el sendero del discipulado y en las dos primeras iniciaciones. Al principio capta a tientas la idea de la unidad de la Vida y su manifestación, como Hermandad, existente entre todas las formas de esa Vida divina. Este ideal subjetivo conduce paulatinamente a la apreciación de la forma en que esta relación esencial puede desarrollarse prácticamente. Puede observarse su expresión en los grandes esfuerzos humanitarios, en las <Pin lang="en">94</Pin> organizaciones destinadas al alivio del sufrimiento humano y animal, y en los esfuerzos mundiales para el mejoramiento de las relaciones internas de naciones, religiones y grupos.

<p><Pin lang="es">79</Pin> En la actualidad un gran número de unidades humanas han hecho ya contacto con el Plan jerárquico, de manera que puede deducirse sin peligro, que el cerebro colectivo de la familia humana (esa entidad que llamamos el cuarto reino de la naturaleza) es sensible a la visión y ha construido su forma iluminada en el plano mental. Más adelante, los conceptos acerca del servicio y del yo, serán inadecuados y se encontrará una forma más apropiada de expresión, pero por el momento, ésta es suficiente.</p>

Esta forma mental, creada por el aspirante, es llevada a la existencia por las energías enfocadas del alma y las fuerzas reorientadas de la personalidad. Esto abarca tres etapas:

1. El período en que el aspirante lucha para lograr esa quietud interna y atención dirigida, que le permitirá oír la Voz del Silencio. Esa voz le expresará, a través de símbolos y la interpretación correcta de las experiencias de la vida, los propósitos y planes con los cuales puede cooperar. De acuerdo a su etapa de desarrollo estos planes pueden expresar:
   1. Los planes ya materializados que adquieren forma grupal en el plano físico, con los cuales podrá cooperar, sumergiendo en ellos su propio interés.
   2. El plan o fracción de un plan, que es privilegio del individuo manifestar y materializar como actividad grupal en el plano físico. La función de algunos aspirantes es ayudar a esos grupos que están en actividad operante. La función de otros es iniciar esas formas de actividad que están todavía en el plano subjetivo. Sólo los aspirantes libres de ambición <Pin lang="en">95</Pin> personal podrán cooperar verdaderamente en este segundo aspecto del trabajo. Por lo tanto, "Matad la ambición".
2. El período en el que se habitúa a oír con claridad e interpretar correctamente la voz interna del alma y a reflexionar sobre el mensaje impartido. Durante este período "la energía circula". Se establece una constante respuesta rítmica con la energía mental del alma y, hablando figuradamente, hay un constante fluir de fuerza entre ese centro de energía que llamamos el alma en su propio plano, y ese centro de fuerza que es un ser humano. La energía fluye a través del "hilo" denominado sutratma, y establece una respuesta vibratoria entre el cerebro y el alma.

Aquí podría dar una interesante información, pues me propongo en estas instrucciones vincular las analogías que existen entre los diferentes aspectos de la divinidad, tal como se expresan en el hombre o en el macrocosmos, el Hombre celestial.

La antigua yoga de la época atlante (que ha llegado hasta <Pin lang="es">80</Pin> nosotros en la enseñanza necesariamente fragmentada de la yoga de los centros) nos informa que el reflejo del sutratma, en el organismo humano, se denomina la médula espinal, expresándose en tres canales de nervios, a los cuales se los denomina ida, pingala y, al canal central, sushuma. Cuando las fuerzas negativas y positivas del cuerpo, que se expresan por medio de los nervios ida y pingala, están equilibradas, las fuerzas pueden ascender y descender por el canal central al cerebro, y desde éste, pasando sin impedimento alguno, a través de los centros de la columna vertebral. Cuando esto sucede tenemos la perfecta expresión del alma en el hombre físico.

En realidad constituye la analogía del sutratma, cuando vincula al hombre físico con el alma, porque el sutratma a su vez expresa la energía positiva del espíritu, la energía negativa de la materia y la equilibrada energía <Pin lang="en">96</Pin> del alma, pues el objetivo actual de la humanidad es lograr el equilibrio. Durante el período de las iniciaciones posteriores, el empleo positivo de la energía espiritual reemplaza al empleo equilibrado de la fuerza del alma, pero de esta etapa posterior el aspirante no debe aún preocuparse. Que trate de descubrir el "noble sendero medio" entre los pares de opuestos, e incidentalmente descubrirá que las fuerzas que él usa en el plano físico, utilizarán el canal central nervioso de la columna vertebral. Esto ocurrirá cuando la transmisión de la luz y la verdad al cerebro físico, por intermedio del canal central del sutratma vinculador, llegue a ser de utilidad satisfactoria. Estos conceptos e ideas (hablando en símbolos) que vienen por el canal sutrátmico negativo, son bien intencionados, pero carecen de fuerza y quedan en la nada. Están matizados por la emoción y desprovistos de la forma organizada que la mente pura puede proporcionar. Los que llegan por el canal opuesto (hablando en sentido figurado) producen una concreción demasiado rápida y están motivados por la ambición personal de una mentalidad rectora. La mente es siempre egoísta, auto afirmativa y expresa la ambición personal, que lleva dentro de sí el germen de su propia destrucción.

Sin embargo, cuando se utiliza el sutrátmico sushuma, el canal nervioso central y su energía, el alma, como creador inteligente y magnético, trasmite sus energías. Entonces los planes pueden madurar según el propósito divino y seguir con sus actividades constructivas "en la luz". El punto de contacto egoico y lunar emite siempre un punto de luz, como ya hemos visto en las Reglas para la Magia, tiene su enfoque en un punto del sutratma que es la analogía de la luz en la cabeza del aspirante.

3. El período en que entona la Palabra Sagrada y - fusionándola con la voz del ego o alma - pone en movimiento <Pin lang="es">81</Pin> materia mental para la construcción de su forma mental. El hombre en el plano físico es el que entona ahora la Palabra, y lo hace en cuatro formas: <Pin lang="en">97</Pin>
   1. Se convierte en la Palabra encarnada, y trata de "ser lo que es".
   2. Entona la Palabra dentro de sí mismo tratando de hacerlo como alma. Se visualiza como el alma que exhala energía mediante esa Palabra, a través de todo el sistema que su alma anima - sus instrumentos mental, emocional, vital y físico.
   3. Entona la Palabra, literalmente hablando, en el plano físico, afectando así los tres grados de materia en su medio ambiente. Durante todo ese tiempo "se ocupa de mantener la mente firme en la luz", y sostener inamovible la conciencia en el reino del alma.
   4. Además lleva adelante (y esta es la etapa más difícil) una actividad paralela, de constante visualización de la forma mental, por medio de la cual espera expresar ese aspecto del plan con el que ha hecho contacto, y tiene la esperanza de llevarlo a la actividad por medio de su propia vida y en su propio medio ambiente.

Esto sólo es posible cuando se ha establecido una firme relación entre el alma y el cerebro. El proceso implica la capacidad del cerebro para registrar lo que el alma percibe, de lo cual es consciente en el reino del alma. Implica también una actividad paralela llevada a cabo en la mente, porque el aspirante tiene que interpretar la visión y utilizar la facultad concreta inteligente para la sabia adaptación del tiempo y de la forma, a la justa expresión de lo aprendido. Esto no es algo fácil de hacer, pero el aspirante debe aprender oportunamente a expresarse con plena conciencia, en diferentes maneras y en forma simultánea. Así comienza a aprender a realizar una triple actividad. Esto lo expresa El Antiguo Comentario, de la manera siguiente:

> <Pin lang="en">98</Pin> El Orbe solar resplandece con radiante esplendor. La mente iluminada refleja la gloria solar. El orbe lunar se eleva desde el centro hasta la cima y se transforma en radiante sol de luz. Cuando estos tres soles son uno, aparece Brahma. Nace un mundo iluminado

Esto literalmente significa que cuando el alma (simbolizada como el Orbe solar), la mente y la luz en la cabeza, forman una unidad, el poder creador del Ángel solar puede expresarse en los tres mundos y construir una forma por la cual su energía se manifieste activamente. El orbe lunar es una forma <Pin lang="es">82</Pin> simbólica de expresar el plexo solar, el cual oportunamente debe realizar dos cosas:

1. Mezclar y fusionar las energías de los dos centros inferiores de fuerza.
2. Elevar estas energías fusionadas y así, mezclándose con las energías de otros centros superiores, llegar a la cabeza.

Lo antedicho encierra una enseñanza y una teoría. Y debe ser elaborado por el experimento práctico, la experiencia y la actividad consciente del aspirante.

También quisiera señalar la naturaleza del servicio que la humanidad como un todo, está prestando en el plan general de evolución. La regla en consideración no se aplica sólo al hombre individual, sino a la actividad predestinada del cuarto reino de la naturaleza. Por medio de la meditación, la disciplina y el servicio, el hombre convierte en una luz radiante - que ilumina los tres mundos - ese punto de luz parpadeante que vino al ser en el momento de su individualización, en épocas pasadas. Tiene su reflejo en la luz de la cabeza. Así se establece esa relación que permite, no sólo la sincronización vibratoria, sino también la irradiación y el despliegue de fuerza magnética, y también su reconocimiento en los tres mundos del medio ambiente inmediato del hombre.

Lo mismo sucede con el reino humano. A medida que acrecienta su iluminación, y su luz se hace más potente, su efecto en los <Pin lang="en">99</Pin> reinos subhumanos es análogo al del alma individual - su reflejo - en el hombre en encarnación física. Digo que es análogo a una fuerza causativa, aunque no una analogía en sus efectos. Observen esta diferencia. La humanidad es macrocósmica en relación con los estados subhumanos de conciencia, y esto lo ha señalado muy bien H.P.B. El efecto producido sobre estos estados inferiores y materiales, es principalmente cuádruple.

1. La estimulación del aspecto espiritual que se expresa como alma en todas las formas, tales como la de un mineral, una flor o un animal. El aspecto positivo de la energía en todas estas formas se hará más fuerte, produciendo por ejemplo, acrecentada irradiación en el reino mineral. He aquí un indicio de la naturaleza del proceso que pondrá término a nuestra propia existencia planetaria y, finalmente, a nuestro sistema solar. En el reino vegetal traerá una acrecentada belleza y diversidad, y la evolución de nuevas especies con una finalidad inexplicable para quienes aún no son iniciados. Uno de los resultados será la <Pin lang="es">83</Pin> producción de formas nutritivas que servirán a las necesidades de los ángeles y devas menores.

 En el reino animal su efecto será la eliminación del dolor y el sufrimiento, y un retorno a las condiciones ideales del Jardín del Edén. Cuando el hombre actúa como alma, cura, estimula y vitaliza; transmite las fuerzas espirituales del universo, y todas las emanaciones nocivas y las fuerzas destructoras encuentran una barrera en el reino humano. El mal y sus efectos dependen mayormente de la humanidad como canal activo. La función de la humanidad consiste en transmitir y manejar fuerza. Esto, en las etapas primitivas e ignorantes, se efectúa en forma destructiva y con resultados perjudiciales. Después, cuando actúa bajo la influencia del alma, la fuerza es manejada correcta e inteligentemente con resultados benéficos. Es muy cierta que: "Toda la creación gime a una, y está en dolores de parto hasta ahora, aguardando la manifestación de los hijos de Dios". <Pin lang="en">100</Pin>

2. La introducción de la luz. La humanidad es el planetario portador de luz, trasmitiendo la luz del conocimiento, de la sabiduría y de la comprensión, en sentido esotérico. Estos tres aspectos de la luz llevan los tres aspectos de la energía del alma, al alma de todas las formas, mediante el ánima mundi, el alma del mundo. Físicamente hablando, podemos comprenderlo si apreciamos la diferencia entre nuestra iluminación planetaria actual y la de hace quinientos años - las ciudades y los distritos rurales intensamente iluminados que brillan en la noche con sus calles y hogares alumbrados; los aeródromos con sus reflectores y relucientes luces; los océanos salpicados de barcos iluminados, y los aviones resplandecientes de luz atravesando los cielos.

 Esto es sólo el resultado de la creciente iluminación del hombre. Su conocimiento de la luz lo ha traído a la existencia. ¿Quién puede predecir qué acontecerá cuando predomine el aspecto sabiduría? Cuando el conocimiento y la sabiduría estén fusionados por la comprensión, el alma controlará los tres mundos y todos los reinos de la naturaleza.

3. La transmisión de la energía. La clave de la significación de esto puede ser captada como un concepto, aunque todavía no será comprendida si se reconoce que el reino humano actúa sobre los tres reinos subhumanos y los afecta. El triángulo espiritual descendente y el triángulo material ascendente, unen sus vórtices en la humanidad cuando ha encontrado el punto de equilibrio. En la realización y espiritualización del hombre reside la esperanza del mundo. El género humano es el Salvador mundial, del cual todos los Salvadores mundiales han sido símbolo y garantía. <Pin lang="es">84</Pin>
4. La unión de la evolución dévica o angélica con la humana. Éste es un misterio que se solucionará a medida que el hombre adquiera la conciencia de su propio Ángel solar, sólo para descubrir que ella no es más que otra forma de vida que, <Pin lang="en">101</Pin> habiendo servido su propósito, debe ser dejada atrás. La evolución angélica o dévica, es una de las grandes líneas de fuerza contenidas en la expresión divina y en los Ángeles solares; los Agnishvattas de La Doctrina Secreta y de Tratado sobre Fuego Cósmico - en su aspecto forma - pertenecen a esa línea.

Así sirve la humanidad, y en el desarrollo de una aptitud consciente de servicio, en el acrecentamiento de una comprensión consciente de la parte individual que debe desempeñar en el desarrollo del plan y en el sometimiento de la personalidad al alma, se logrará el constante progreso de la humanidad hacia su meta de servicio mundial.

¿Podría decir algo aquí para que esta consumación llegue a ser una meta práctica en sus vidas? Las condiciones magnéticas perjudiciales, resultado del incorrecto manejo de la fuerza por el hombre, son las causas del mal que existe en el mundo circundante, incluyendo los tres reinos subhumanos. ¿Cómo podríamos cambiar esto individualmente? Por el desarrollo de nuestra propia Inofensividad. Por lo tanto, analícense a sí mismos desde este ángulo. Estudien su conducta diaria, sus palabras y pensamientos, hasta lograr ser completamente inofensivos. Oblíguense a pensar sobre esas ideas, respecto a ustedes y los demás, para que sean constructivas y positivas, y por lo tanto de efectos inofensivos. Examinen el efecto emocional que ustedes producen sobre otros, de manera que ningún estado de ánimo, depresión ni reacción emocional, puedan dañar al semejante. Recuerden en conexión con esto que la violenta aspiración espiritual y el entusiasmo mal aplicado o mal orientado, pueden fácilmente herir a un semejante; por lo tanto cuiden sus tendencias erróneas y no sólo sus virtudes.

Si la inofensividad es la nota clave de su vida, podrán producir más condiciones armónicas en la personalidad, que cualquier disciplina en otras líneas. La depuración drástica obtenida al alcanzar la inofensividad ayudará mucho a eliminar <Pin lang="en">102</Pin> estados erróneos de conciencia. Reflexionen sobre esto e introduzcan dicha idea en la recapitulación vespertina.

Quisiera urgir a quienes leen estas páginas a hacer un nuevo comienzo en el vivir espiritual. Les diría, olviden todo lo realizado en el pasado, tengan fervor y concéntrense en el Plan.

Ya habrán hecho algún progreso en la comprensión grupal, y se interesarán menos por el yo separado. Sin duda <Pin lang="es">85</Pin> adquirieron más fe en la Buena Ley que guía a toda la creación hacia la perfección final que ya habrán visualizado y, por medio de esta visión, pudieron apartar los ojos de los asuntos de la experiencia individual, dirigiéndolos al desarrollo del propósito para la totalidad. Tal es el objetivo y la meta. Amplitud de visión, comprensión incluyente y un horizonte más amplio, son los preliminares esenciales de todo trabajo que está bajo la guía de la Jerarquía de adeptos; la estabilización de la conciencia en la vida una y el reconocimiento de la unidad básica de toda la creación, tendrán que desarrollarse parcialmente antes de poder confiar a nadie ciertos conocimientos y Palabras de Poder, y el manejo de esas fuerzas que traen la realidad subjetiva a la manifestación externa.

En esta oportunidad les digo que yo - discípulo de más edad y quizás con mayor experiencia y trabajador en la gran viña del Señor - practico la inofensividad con celo y comprensión, porque (si realmente es practicada) destruye toda limitación. La ofensividad está basada en el egoísmo y en una actitud egocéntrica. Es la demostración de fuerzas concentradas en la auto imposición, el auto engrandecimiento y la autosatisfacción. Inofensividad es la expresión de la vida del hombre que se da cuenta que está en todas partes y vive conscientemente como alma, cuya naturaleza es amor y cuyo método es inclusividad, para quien todas las formas son iguales en el sentido de que velan y ocultan la luz y las simples exteriorizaciones del <Pin lang="en">103</Pin> Único Ser Infinito. Quisiera recordarles que este logro se demostrará verdaderamente como comprensión de la necesidad del hermano, sin ningún sentimiento y conveniencia. Conducirá a ese silencio que se produce al referirse al yo separado. Producirá respuesta instantánea a la verdadera necesidad, característica de los Grandes Seres, que (al ir más allá de la apariencia externa) perciben la causa interna que produce las condiciones observadas en la vida externa y, desde ese punto de sabiduría, puede darse verdadera ayuda y guía. La inofensividad produce en la vida, cautela en el juicio, reticencia al hablar, habilidad para abstenerse de toda acción impulsiva, y demuestra un espíritu exento de crítica. De esta manera las fuerzas del verdadero amor y también esas energías espirituales que parecen vitalizar la personalidad, pasarán libremente y en consecuencia conducirán a la correcta acción.

Que la inofensividad sea, por lo tanto, la nota clave de su vida. En estas líneas debe efectuarse la recapitulación vespertina, clasificar el trabajo de recapitulación en tres partes, considerando: <Pin lang="es">86</Pin>

1. El pensar inofensivo. Dará por resultado especialmente el control de la palabra.
2. La reacción emocional inofensiva. Traerá como resultado un canal para el aspecto amor del alma.
3. La acción inofensiva. Producirá equilibrio, capacidad en la acción y liberación de la voluntad creadora.

Estos tres acercamientos al tema deben ser estudiados a través del efecto que producen sobre nuestro propio yo y desarrollo y en aquellos con quienes nos ponemos en contacto y los asociados en nuestro medio ambiente.

Quisiera intercalar aquí la observación de que hago sugerencias basadas en las experiencias del trabajo esotérico. No es obligatorio obedecer. Tratamos de entrenar a servidores inteligentes de la raza, que se desarrollan mediante el esfuerzo <Pin lang="en">104</Pin> autoiniciado, la libertad de acción y el discernimiento en el método, y no por ciega obediencia, pasividad negativa y adhesión incondicional. Recuérdenlo. Si alguna vez el mandato surgido del grupo subjetivo de instructores, del cual soy un humilde miembro, imparte una orden que sea para seguir los dictados de la propia alma y las inspiraciones del yo superior.

Antes de analizar esta regla y la anterior, pues las Reglas Dos y Tres son mitades de un entero, quisiera recordarles que en esta serie de meditaciones sobre fórmulas antiguas, nos ocuparemos del trabajo mágico del aspirante como colaborador en las empresas de la Gran Logia Blanca. Me referiré a los métodos de magia blanca. También les recordaré que el trabajo mágico de nuestra Jerarquía planetaria consiste en cuidar la psiquis en el mundo de las formas, para que la flor del alma, a medida que se vaya abriendo, pueda ser nutrida y preservada en tal forma, que la gloria radiante, la fuerza magnética y, finalmente, la energía espiritual, puedan expresarse mediante la forma. Así se podrá percibir el poder de los tres Rayos de Manifestación divina.

:::note Recuerda

También les recordaré que el trabajo mágico de nuestra Jerarquía planetaria consiste en cuidar la psiquis en el mundo de las formas, para que la flor del alma, a medida que se vaya abriendo, pueda ser nutrida y preservada en tal forma, que la gloria radiante, la fuerza magnética y, finalmente, la energía espiritual, puedan expresarse mediante la forma.

:::

|              |                    |
| ------------ | ------------------ |
| Primer rayo  | energía espiritual |
| Segundo rayo | fuerza magnética   |
| Tercer rayo  | gloria radiante    |

Estos rayos tienen también sus reflejos microcósmicos en el aura del hombre perfecto.

|              |              |                    |                   |
| ------------ | ------------ | ------------------ | ----------------- |
| Primer rayo  | monádico     | energía espiritual | centro coronario. |
| Segundo rayo | egoico       | fuerza magnética   | centro cardíaco.  |
| Tercer rayo  | personalidad | gloria radiante    | plexo solar.      |

Quizá se pregunten, ¿por qué no menciono el centro laríngeo? Porque los centros abajo del diafragma simbolizan <Pin lang="es">87</Pin> principalmente el yo inferior personal, y su centro sintetizador, el plexo solar, expresa la fuerza magnética del aspecto materia en el hombre. A medida que la personalidad vibra para el alma, el centro laríngeo es impelido <Pin lang="en">105</Pin> a una creciente actividad creadora.

Consideraremos ahora las palabras finales de la regla anterior: "La luz inferior es proyectada hacia arriba; la luz superior ilumina a los tres, y el trabajo de los cuatro prosigue".

¿Qué sucede con esta luz inferior? El estudiante debería recordar que para los actuales propósitos debe considerar tres cuerpos de luz:

1. El cuerpo radiante del alma, en su propio plano, denominado frecuentemente Karana Sarira o cuerpo causal.
2. El cuerpo vital o etérico, el vehículo de prana, el cuerpo de luz dorada o, mejor dicho, el vehículo de color flamígero.
3. El cuerpo de "luz oscura" modo esotérico de referirse a la luz oculta del cuerpo físico y a la luz latente en el átomo mismo.

El Antiguo Comentario se refiere a estos tres tipos de energía con los términos simbólicos siguientes:

> Cuando, la radiante luz del Ángel solar se fusiona con la luz dorada del intermediario cósmico, despierta de la oscuridad a la ínfima llama de anu, la partícula.

"El intermediario cósmico" es el término aplicado al cuerpo etérico, parte integrante del éter universal. A través del cuerpo etérico fluyen todas las energías, ya emanen del alma, del sol o de un planeta. Por estas líneas vivientes de esencia ígnea pasan todos los contactos que no emanan específicamente del mundo tangible.

La oscura luz de los diminutos átomos de que está construido el vehículo físico, responde al estímulo que desde el alma desciende a su vehículo y, cuando el hombre está bajo el control del alma, resplandece la luz en todo el cuerpo. Ésta <Pin lang="en">106</Pin> se manifiesta como la irradiación que emana de los cuerpos de los adeptos y santos, produciendo el efecto de brillante y reluciente luz.

Cuando la radiante luz del alma se fusiona con la luz magnética del cuerpo vital, estimula los átomos del cuerpo físico a tal extremo, que cada uno de ellos a su vez se convierte en un pequeño centro radiante. Esto es sólo posible cuando los centros coronario, cardíaco, plexo solar y el de la base de la columna vertebral, están conectados en forma peculiar, siendo éstos uno de los secretos de la primera iniciación. Cuando los cuatro colaboran estrechamente, la "base del triángulo", según se la denomina simbólicamente, está preparada para el trabajo mágico. En otras palabras, se los puede enumerar de la manera siguiente: <Pin lang="es">88</Pin>

1. La forma física material, con su centro en la base de la columna vertebral.
2. El cuerpo vital, actuando por medio del centro cardíaco, donde radica el principio vida. Las actividades del cuerpo, debido a este estímulo se realizan por medio de la circulación de la sangre.
3. El cuerpo emocional, actuando mediante el centro plexo solar.
4. El centro coronario, agente directo del alma, y su intérprete, la mente. Los cuatro se hallan en completo acuerdo y alineamiento.

Cuando tal es el caso, es posible el trabajo de iniciación y sus períodos de discipulado activo. El trabajo no puede proseguir hasta lograrse esto, lo cual está previsto en el aspirante al efectuarse el acontecimiento simbólico de la luz en la cabeza, precursor de un estado posterior de la iniciación.

En esta etapa, la luz del alma penetra en la región de la glándula pineal, irradiando allí los éteres en la cabeza, los aires vitales, lo cual estimula los átomos del cerebro, de manera que su luz <Pin lang="en">107</Pin> se fusiona y mezcla con las otras dos, la etérica y la del alma; entonces se produce ese radiante sol interno del cual el aspirante es consciente en su cerebro físico. Frecuentemente los estudiantes hablan de una luz difusa o resplandor, luz de los átomos del plano físico de los cuales está compuesto el cerebro; posteriormente quizá digan que han visto en la cabeza algo parecido a un sol, lo cual significa hacer contacto con la luz etérica y la luz física atómica. Luego, perciben una luz eléctrica intensamente brillante; es la luz del alma, unida a la etérica y a la atómica. Cuando llegan a ver esto, son a menudo conscientes de un centro oscuro dentro del sol radiante. Ésta es la entrada en el sendero, revelada por "la luz enfocada en la puerta".

Los estudiantes deben recordar que puede alcanzarse una elevada etapa de conciencia espiritual sin haber visto esta irradiación del cerebro. Ello corresponde a la categoría de los fenómenos, y en gran parte lo determina la calidad del cuerpo físico, el karma pasado, lo que se ha realizado y la capacidad del aspirante para hacer descender el "poder de lo alto" y mantener esa energía firmemente en el centro cerebral, mientras que en su meditación se separa del aspecto forma, y puede contemplarla serenamente.

Logrado esto (que no es un objetivo a alcanzarse, sino simplemente la indicación de que debe ser registrado en la conciencia y luego olvidado), el consiguiente estímulo produce una <Pin lang="es">89</Pin> reacción en el cuerpo físico. El poder magnético de la luz en la cabeza y la fuerza radiante del alma provocan estímulo. Los centros comienzan a vibrar, y su vibración despierta los átomos del cuerpo material, hasta que, eventualmente, los poderes del vibrante cuerpo etérico han impelido al centro más bajo alinearse con el más elevado. Así los fuegos del cuerpo (suma total de la energía de átomos) son arrastrados a una acrecentada actividad, hasta el momento <Pin lang="en">108</Pin> de producirse un ascenso en la columna vertebral de esa energía ígnea. Se origina por el control magnético del alma, situada "en el trono entre las cejas".

Aquí interviene el trabajo de uno de los métodos de yoga, la abstracción o retraimiento. Cuando las tres luces se mezclan, los centros se activan y los átomos vibran, el hombre puede centrar a voluntad los tres en la cabeza. Entonces, mediante un acto de la voluntad y el conocimiento de ciertas palabras de Poder, podrá entrar en samadhi y retirarse de su cuerpo, llevando consigo la luz. La luz mayor (las tres fusionadas y mezcladas) ilumina así los tres mundos del esfuerzo humano, y "la luz es proyectada hacia arriba", e ilumina todas las esferas de la experiencia consciente e inconsciente del hombre. Sobre esto se habla en los escritos ocultos de los Maestros:

> Entonces el Toro de Dios lleva la luz en la frente y su ojo transmite la irradiación; la fuerza magnética de Su cabeza se asemeja al fulgurante sol y del loto de la cabeza sale el sendero de luz. Penetra en el Ser mayor, produciendo un fuego viviente. El Toro de Dios percibe al Ángel solar, y sabe que ese Ángel es la luz en la cual camina

Luego prosigue el trabajo de los cuatro. Los cuatro se unifican. El Ángel solar se identifica con su instrumento; la vida de los vehículos se subordina a la de la divinidad interna; la luz de los vehículos se fusiona con la luz del alma. La cabeza, el corazón y la base de la columna vertebral, se alinean geométricamente, entonces son posibles ciertos desarrollos.

En estas dos reglas se han sentado las bases del trabajo mágico del alma. Para mayor claridad enumeremos los pasos delineados:

1. El Ángel solar comienza el trabajo de iniciar a la Personalidad. <Pin lang="en">109</Pin>
2. Retira sus fuerzas de las empresas del alma en el reino espiritual, y centra su atención en el trabajo que debe realizarse.
3. Entra en profunda meditación.
4. Establece relación magnética con el instrumento en los tres mundos. <Pin lang="es">90</Pin>
5. El instrumento, el hombre, responde, y también entra en meditación.
6. El trabajo prosigue en etapas ordenadas y en cíclica actividad.
7. La luz del alma es proyectada hacia abajo.
8. La luz del cuerpo vital y de la forma física se sincroniza con la de la cabeza.
9. Los centros entran en actividad.
10. La luz del alma y los otros dos aspectos de la luz son tan intensos ahora que toda la vida de los tres mundos se ilumina.
11. El alineamiento tiene lugar y es posible el trabajo del discipulado y de la iniciación, prosiguiendo de acuerdo con la Ley del Ser.

### Principios y Personalidades

Ahora bien, existe un punto que merece ser considerado y puede encararse con un interrogante. El estudiante podría muy bien investigar la cuestión de la manera siguiente:

Algunas personas encaran el problema del Ser por la apreciación mental y otros por la comprensión del corazón; algunos están motivados por la cabeza y otros por el corazón; hay quienes hacen cosas o evitan hacerlas, no porque las sienten sino porque las saben, reaccionando a su medio ambiente en forma mental, en lugar de hacerlo emocionalmente.

Hay que buscar iluminación para saber si para algunos el sendero consiste en no prestar servicio, porque más bien conocen que aman a Dios, que después de todo no es más que su propio yo interno. <Pin lang="en">110</Pin> ¿No es éste el sendero del ocultista y del sabio más bien que el del místico y del santo? Después de lo dicho y hecho, ¿no es principalmente cuestión de saber el rayo a que uno pertenece y bajo qué Maestro se recibe el aprendizaje? ¿No es el verdadero conocimiento una especie de amor intelectual? Si un poeta puede escribir una oda a la belleza intelectual, ¿por qué no podemos expresar nuestro aprecio por una entidad concebida por la cabeza más que por el corazón. El corazón tiene su valor, pero no es adecuado para la rudeza del mundo.

¿Qué otra cosa puede hacerse sino aceptar las actuales limitaciones mientras se buscan las cosas trascendentales que le corresponde, según la Ley Divina de evolución? ¿No existe acaso aquello que (comparativamente) es como un complejo espiritual de inferioridad, de parte de quienes son sensibles (y quizás super sensibles), al hecho de que, si bien sus vidas están intelectualmente colmadas de interés, el desierto de sus corazones no han llegado a florecer como la rosa?

"En otras palabras, siempre que uno acuda a servir en el lugar designado, aceptando la Hermandad en Presencia de la Paternidad, ¿qué importa que el postulado fundamental sea para él una cosa de la cabeza, en vez de serlo del corazón?"

<p><Pin lang="es">91</Pin> Responderé a estas preguntas de la manera siguiente:</p>

No es cuestión de rayo ni de una diferencia básica entre el ocultista y el místico. En el individuo íntegro deben actuar con igual poder la cabeza y el corazón. No obstante, en tiempo y espacio y durante el proceso de evolución, los individuos se caracterizan por la tendencia que predomina en cualquier vida; hacemos estas diferencias transitorias porque no percibimos el conjunto. En determinada vida el hombre puede ser predominantemente mental, pues para él, el sendero del Amor de Dios no sería apropiado. El Amor de Dios afluye a su corazón y en considerable medida su acercamiento esotérico se basa en la percepción mística de sus vidas anteriores. Su problema es conocer a Dios, con la finalidad de interpretar ese conocimiento como amor a todo. Por lo tanto, <Pin lang="en">111</Pin> el amor responsable, expresado como deber hacia el grupo y la familia, es para él la línea de menor resistencia. El amor universal irradiado a toda la naturaleza y a todas las formas de vida, vendrá después de un mayor conocimiento de Dios, y será parte de su desarrollo en otra vida.

Quienes estudian la naturaleza humana (y esto deberían hacerlo todos los aspirantes) harían bien en tener presente que existen diferencias transitorias. Las personas difieren en:

1. El rayo (que afecta predominantemente al magnetismo de la vida).
2. El acercamiento a la verdad, teniendo mayor poder de atracción el sendero ocultista o el místico.
3. La polarización, que decide la intención emocional, mental o física, de una vida.
4. La etapa de evolución, que produce las diferencias observadas entre los hombres.
5. El signo astrológico, que determina la tendencia de determinada vida.
6. La raza, que pone a la personalidad bajo la peculiar forma mental racial.

El subrayo al que pertenece el hombre, ese rayo menor que varía de una encarnación a otra, colora mayormente su vida. Es su matiz secundario. Recuerden que el rayo primario de la mónada continúa durante el eón. No varía. Es uno de los tres rayos primarios que oportunamente los hijos de los hombres sintetizarán. El rayo egoico varía de ronda en ronda, y en las almas más evolucionadas de raza en raza, y comprende uno de los cinco rayos de nuestra actual evolución. Es el rayo predominante por el cual vibra el cuerpo causal del hombre. Puede corresponder al rayo de la mónada, o ser uno de los colores complementarios del primario. El rayo de la personalidad varía <Pin lang="en">112</Pin> vida tras vida, hasta <Pin lang="es">92</Pin> haber pasado por toda la gama de los siete subrayos del rayo monádico.

Por consiguiente, al tratar con personas cuyas mónadas están en un rayo similar o complementario, se hallará que se aproximan por simpatía. Sin embargo, conviene recordar que la evolución debe ser muy avanzada para que el rayo de la mónada influya ampliamente. De este modo la mayoría de los casos no pertenecen a esa categoría.

Referente al hombre común evolucionado, que lucha por aproximarse al ideal, la similitud del rayo egoico producirá una mutua comprensión, que lo llevará a la amistad. Es fácil para dos personas del mismo rayo egoico comprender sus puntos de vista y llegar a ser grandes amigos, con una mutua fe inquebrantable, pues cada uno reconoce en el otro el mismo modo de actuar.

Pero cuando (agregado a la similitud egoica de rayo) la personalidad pertenece al mismo rayo, entonces tenemos una de esas cosas poco frecuentes, una perfecta amistad, un casamiento feliz, un vínculo inquebrantable entre dos. Esto, en realidad, es sumamente raro.

Cuando se trata de dos personas cuya personalidad pertenece al mismo rayo, y a distinto rayo egoico, puede existir una de esas amistades y afinidades breves y repentinas, pero tan efímeras como una mariposa. Es menester tenerlo presente, pues reconociéndolo se obtiene la capacidad de adaptación. La claridad de visión da por resultado una actitud prudente.

Otra causa de disidencias puede deberse a la polarización de los cuerpos. A no ser que esto sea reconocido, al tratarse las personas, se producirá incomprensión. El empleo de los términos, "un hombre polarizado en su cuerpo astral", en realidad, significa el hombre cuyo ego actúa principalmente a través de dicho vehículo. La polaridad indica la claridad del canal. Permítaseme ilustrarlo. El ego del hombre <Pin lang="en">113</Pin> común tiene su morada en el tercer subplano del plano mental. Cuando el hombre posee un vehículo astral compuesto en su mayor parte de materia del tercer subplano astral, y el mental se encuentra mayormente en el quinto subplano, el ego centrará sus esfuerzos en el cuerpo astral. Si tiene un cuerpo mental de materia del cuarto subplano y un cuerpo astral del quinto subplano, la polarización será mental.

Cuando se habla que el ego controla más o menos al hombre, en realidad se quiere decir que ha incorporado en sus cuerpos materia de los subplanos superiores.

El ego controla con interés sólo cuando el hombre ha eliminado de sus vehículos casi toda la materia del séptimo, sexto y quinto subplanos. Cuando ha incorporado cierta cantidad de <Pin lang="es">93</Pin> materia del cuarto subplano, el ego amplía su control; cuando existe cierta cantidad del tercer subplano, entonces el hombre está en el sendero; cuando predomina materia del segundo subplano entonces recibe la iniciación, y cuando tiene solamente materia de sustancia atómica se convierte en Maestro. Por lo tanto, el subplano en el que se encuentra el hombre es importante, y el reconocimiento de su polarización dilucida la vida.

La tercera cosa a recordarse es que aunque se aceptan ambos puntos, la edad y la experiencia del alma con frecuencia originan incomprensión. Los dos puntos anteriores no nos llevan muy lejos, porque la capacidad de percibir el rayo del hombre no es aún para esta raza. Una aproximada suposición y el uso de la intuición, es todo lo que se puede hacer. Los pocos evolucionados no pueden comprender perfectamente a los muy evolucionados, y en menor grado el alma avanzada no comprende al iniciado. Lo mayor puede comprender lo menor, pero no lo contrario.

Respecto a la actividad de aquellos cuyo punto de realización trasciende el propio, sólo les pediré hacer tres cosas: <Pin lang="en">114</Pin>

1. No juzgar. Ellos tienen mayor visión. Recuerden que una de las mayores cualidades que han alcanzado los miembros de la Logia es su habilidad para considerar la destrucción de la forma como algo sin importancia. Les preocupa la vida en evolución.
2. Comprender que todos los acontecimientos son producidos por los Hermanos, teniendo en vista un sabio propósito. Los iniciados de grado inferior, aunque agentes absolutamente libres, encuadran en los planes de sus superiores, del mismo modo que lo hacen ustedes en escala menor. Tienen lecciones que aprender, y la regla del aprendizaje dice que la experiencia debe ser pagada. La captación viene a través del castigo que sigue a la acción irrazonable. Sus superiores permanecen preparados para sacar provecho de las situaciones producidas por los errores de quienes están en una etapa inferior de desarrollo.
3. Tener presente que la Ley de Renacimiento oculta en sí el secreto de la crisis actual. Los egos se reúnen en grupos para agotar cierto karma acumulado en el pasado, en el cual pecaron lastimosamente los hombres. El castigo y la transmutación son consecuencias naturales. La violencia y la crueldad anteriores traerán un pesado karma, pero ustedes tienen en sus manos la trasmutación de los antiguos errores.

Recuerden además que los principios son eternos y las personalidades transitorias. Los principios se verán a la luz de la eternidad, las personalidades desde el punto de vista del tiempo. <Pin lang="es">94</Pin> Lo malo es que, en muchas situaciones, están involucrados dos principios, uno de ellos secundario. La dificultad estriba en que (siendo ambos principios) los dos son correctos. Una buena regla para una guía segura, consiste en recordar siempre que generalmente los principios básicos (para una sabia comprensión y desarrollo fructífero) exigen el empleo de la intuición, mientras que los secundarios son más puramente mentales. Por eso los métodos difieren necesariamente. Al aferrarse a los principios básicos, los métodos más inteligentes son <Pin lang="en">115</Pin> el silencio y una alegre confianza en que la Ley actúa, evitando todas las insinuaciones personales, excepto los comentarios inteligentes y amorosos, tratando de ver todo a la luz de la eternidad y no del tiempo, conjuntamente con un constante afán de seguir la ley del amor y sólo ver lo divino en el hermano, aunque tenga ideas contrarias.

En los principios secundarios, que las fuerzas opuestas destacan en la actualidad, la utilización de la mente inferior encierra el peligro de crítica y el empleo de métodos sancionados por el tiempo en los tres mundos - métodos que involucran el ataque personal, la injuria y la pérdida de energía en cosas destructivas, además de un espíritu contrario a la ley del plano, de la unidad. El término "fuerzas opuestas", se emplea correctamente cuando se usa sólo en un sentido científico, y significa el polo opuesto que conduce al equilibrio. Por lo tanto, recuerden que aunque los grupos opuestos sean completamente sinceros, puede actuar en ellos la mente concreta como barrera para la libre acción de la visión superior. Su sinceridad es grande, pero su etapa de realización, en algunas líneas, es menor que la de aquellos que se adhieren a los principios básicos, vistos a la luz de la intuición.

Principio es aquello que encarna algún aspecto de la verdad en que está basado nuestro sistema; es la infiltración, en la conciencia del hombre, de una pequeña parte de la idea sobre la que nuestro Logos fundamenta todo lo que hace. La base de toda acción logoica es amor en actividad, y la idea fundamental sobre la cual Él basa la acción, conectada con la Jerarquía humana, es el poder del amor que impele hacia delante - llámese evolución, si desean, o impulso inherente, si prefieren, pero es amor que causa movimiento e impulsa a la consumación. Es el impulso impelente de uno y todos hacia una mayor expresión. De allí que este principio debería ser la base de toda actividad, y si la dirección de las organizaciones menores estuviera fundada sobre el amor que conduce a la actividad, crearía en todos sus miembros una urgencia divina, que análogamente los impelerá a una expresión más plena, a una <Pin lang="en">116</Pin> plenitud más adecuada y a un mayor y satisfactorio esfuerzo.

<p><Pin lang="es">95</Pin> Cuando un principio es verdaderamente fundamental, atrae inmediatamente a la intuición y demanda una inmediata reacción de asentimiento del yo superior del hombre. Para la personalidad tiene poca o ninguna atracción. Encierra un concepto del ego en su relación con los demás egos. Un principio es lo que rige siempre la acción del ego en su propio plano; sólo cuando entramos bajo la acrecentada guía de ese ego, nuestra personalidad concibe y responde a estas ideas. Éste es un punto que debe tenerse muy en cuenta en el trato con los demás, lo cual modificará nuestros juicios. La comprensión de un principio marca exactamente una etapa en la evolución.</p>

Un principio es aquello que da vida a la afirmación de que el mayor bien es para el mayor número. Que un hombre debe amar a su esposa es la afirmación de un principio que rige a la personalidad, pero más tarde debe ser trasmutado en un principio más grande, el de que el hombre debe amar a sus semejantes. Los principios son de tres tipos, y para llegar a los superiores se debe pasar por los inferiores:

1. Los principios que rigen al yo personal inferior, y tratan de las acciones o vida activa de ese yo inferior. Encarnan el tercer aspecto, el de la actividad de la manifestación logoica, siendo la base del progreso posterior. Controlan al hombre durante su etapa poco evolucionada y el período de irreflexividad; se comprendería con mayor facilidad si dijera que están incorporados en las comunes y aceptadas reglas para vivir decentemente. No matarás, no hurtarás, tienen mucho que ver con la vida activa del hombre y con la formación de su carácter.
2. Los principios que rigen al yo superior y tratan del aspecto amor o sabiduría. Éstos nos conciernen ahora, y la mitad de las dificultades <Pin lang="en">117</Pin> del mundo surgen en la actualidad porque estos principios más elevados, teniendo que ver con el amor o la sabiduría en toda su plenitud, recién están empezando a ser comprendidos por el vulgo. Debido al rápido reconocimiento de su veracidad y de la tentativa de convertirlos en hechos, sin haber realizado un previo reajuste del medio ambiente a esos ideales, provienen los frecuentes choques y luchas entre los que están condicionados por principios que rigen a la personalidad y quienes lo están por los que gobiernan al yo superior. Hasta que un mayor porcentaje de la raza no se rija por la conciencia del alma, esta lucha será inminente e inevitable. Cuando el plano emocional esté dominado por el intuicional, sobrevendrá entonces la comprensión universal.

 <p><Pin lang="es">96</Pin> El hombre aprende la primera serie de principios por medio de la codicia y el consiguiente desastre que ella produce. Robó, sufrió el castigo, y dejó de robar. El principio se forjó en él mediante el dolor y aprendió que sólo podía gozar de lo que era suyo por derecho y no por posesión. El mundo va ahora aprendiendo esta lección en forma grupal, porque a medida que los rebeldes se apoderan y retienen ilegalmente lo robado, encuentran que no les es suficiente y que les trae sufrimiento. Así, con el tiempo, van aprendiendo los principios.</p>

 La segunda serie de principios se aprende mediante la renunciación y el servicio. El hombre se aparta (después de aprender los primeros principios) de las cosas de la personalidad, y por medio del servicio aprende el poder del amor en su significado oculto. Da, y por lo tanto recibe; vive la vida de renunciación, y las riquezas del cielo afluyen a él; da lo que posee, y a su vez es colmado hasta la saciedad; nada pide para sí, y es el hombre más rico de la tierra.

 Los primeros principios se relacionan con la unidad diferenciada y con la evolución a través de la heterogeneidad. Los principios que aprende actualmente la raza tienen que ver con los grupos; el <Pin lang="en">118</Pin> interrogante no es "¿Qué será lo mejor para el hombre?" sino "¿Qué será lo mejor para los muchos?", y sólo a quienes les es posible pensar en la totalidad y visualizarla como una unidad, pueden enunciar estos principios satisfactoriamente. Son los más importantes, pues constituyen los principios básicos de este sistema de amor. La dificultad actual se debe a que los hombres están confundidos. Algunos de los primeros principios y fundamentos de la actividad inferior son innatos y están actualmente muy arraigados, sólo unos pocos de los principios egoicos superiores o del amor, se están infiltrando en sus confusos cerebros, originando un aparente y momentáneo choque de ideas. Se preguntan como Pilatos: "¿Cuál es la verdad?". Si recordaran solamente que los principios superiores conciernen al bien del grupo y los inferiores al bien del individuo, tal vez surgiría la claridad. La actividad inferior de la vida personal, por buena o digna que sea, a la larga tendrá que ser trascendida por la vida superior del amor que busca el bien del grupo y no el del ente.

 Todo lo que tiende a la síntesis y a la expresión divina en el conjunto de unidades, se aproxima más al ideal y se acerca a los principios superiores. Si se piensa profundamente sobre estas ideas puede llegar alguna ayuda. Un ejemplo de lo que se dijo lo tienen en el hecho de que muchas de las luchas que surgen dentro de las organizaciones se basan en que algunas personas dignas siguen a determinadas personalidades, sacrificándose por un principio; sí, efectivamente, pero un principio que rige la <Pin lang="es">97</Pin> vida de la personalidad. Otros, vislumbrando vagamente algo superior y buscando el bien de los grupos y no el de una persona, tropiezan con un principio superior y al hacerlo introducen, la fuerza del ego. Trabajan para otros con el objeto de ayudar a su grupo. Cuando existen roces entre los egos y las personalidades, la victoria de lo superior es segura; el principio inferior debe ceder su lugar al superior. Uno se concentra en lo que le parece de supremo valor, el cumplimiento del deseo de la vida personal, y (en este período) está <Pin lang="en">119</Pin> interesado sólo en forma secundaria por el bien de la mayoría, aunque podrá tener momentos en los que piensa que ésa es su intención principal. A otro no le importa nada de lo que le acontece al yo personal y sólo le interesa ayudar a la mayoría. Utilizando una expresión apropiada, todo se reduce a un móvil egoísta o altruista y, como bien lo saben, los móviles varían a medida que pasa el tiempo y el hombre se aproxima a la meta del sendero de probación.

3. Los principios más elevados son los que capta el espíritu, y sólo son comprendidos fácilmente por la conciencia monádica. Únicamente a medida que el hombre trasciende su vida activa personal y sustituye la vida de amor o sabiduría, de acuerdo a como el ego la guía, puede empezar a comprender el alcance de esa vida de amor y conocerla como poder manifestado. Así como la personalidad trata de los principios que rigen la vida activa del yo inferior, y el ego actúa con la ley del amor, manifestada en el trabajo grupal o demostrada en la síntesis de los muchos en los pocos, así la mónada se ocupa de la vida activa del amor que se expresa en poder, por la síntesis de los pocos en uno solo.

El primero se ocupa de la vida del hombre en el plano físico en los tres mundos; el segundo, de su vida en niveles causales, y el último, de su vida después de haber alcanzado la meta del esfuerzo humano actual. Uno trata con entes, otro con grupos y el último con la unidad. Uno se ocupa de la diferenciación en sus formas más diversas; el segundo, de los muchos trasformados en grupos egoicos, mientras que el tercero percibe la diferenciación trasformada nuevamente en los siete, que señala la unidad de la jerarquía humana.

Todos estos factores y muchos otros producen diferencias entre los seres humanos, y al valorarse a sí mismo, el hombre debe tenerlos en consideración.

Por consiguiente, debe recordarse que un discípulo de cualquier Maestro tendrá su bagaje propio y sus acerbos y diferencias individuales. Sin embargo, puede <Pin lang="en">120</Pin> estar seguro que hasta no haber incorporado al sendero del Conocimiento el sendero del Amor, <Pin lang="es">98</Pin> no podrá recibir las iniciaciones mayores, porque éstas se reciben en los niveles superiores del plano mental. Hasta que el sendero de luz no se haya unido al de la vida, no podrá efectuarse la gran transición del cuarto reino al quinto. Son posibles ciertas expansiones de conciencia; pueden pasarse iniciaciones en el plano astral y en el plano mental inferior, percibirse algo de la visión y sentir la Presencia; puede llegarse al Bien Amado por medio del amor y la beatitud, y la alegría de este contacto puede traer consigo una alegría permanente; pero esa clara percepción proveniente de la experiencia pasada en el Monte de la Iluminación, es muy distinta de la alegría experimentada en el Monte de la Bendición. En uno, el Corazón es el guía, y en otro, la Cabeza.

Para responder más categóricamente: el sendero del conocimiento es el del ocultista y del sabio; el del amor es el del místico y del santo. El acercamiento por medio de la cabeza o del corazón no depende del rayo, pues ambos caminos deben ser conocidos; el místico deberá convertirse en ocultista; el ocultista blanco ha sido el místico santificado. El verdadero conocimiento es amor inteligente, porque es la fusión del intelecto y la devoción. La unidad se siente en el corazón; su aplicación inteligente a la vida debe ser desarrollada mediante el conocimiento.

Es de gran valor reconocer la tendencia del propósito de la vida, y saber si el objetivo de una vida constituye el método de la cabeza o del corazón. Aquí se requiere, sin embargo, un sutil discernimiento espiritual, porque el espejismo de la ilusión puede tentar a seguir el sendero de la inercia. Reflexionen detenidamente sobre estas palabras y asegúrense que la cuestión tenga una base sólida y que no provenga de un complejo de inferioridad, ni de la iniciativa de un hermano y su consiguiente envidia, o de una plácida inercia que niega toda actividad.

<p><Pin lang="en">121</Pin> Como regla general para el aspirante común al discipulado, se supondrá, sin lugar a dudas, que en el pasado se aplicó muchas veces el método del corazón, y en esta encarnación el desenvolvimiento mental es de primordial importancia.</p>

Una antigua escritura dice:

> No trates, oh, dos veces bendito Uno, de alcanzar la esencia espiritual antes de que la mente absorba. No es así como se busca la sabiduría. Sólo a quien tiene la mente sujeta y percibe el mundo como un espejo, se le puede confiar plenamente los sentidos internos. Sólo a quien sabe que los cinco sentidos son una ilusión y que nada permanece, excepto los dos que están adelante, se le podrá revelar el secreto de la trasposición del Cruciforme.
>
> El sendero hollado por el servidor es el sendero de fuego que atraviesa su corazón y conduce a la cabeza. No es en el sendero del placer ni en el del dolor donde se alcanza la liberación ni se obtiene la sabiduría. Mediante la trascendencia de ambos, por la fusión del <Pin lang="es">99</Pin> dolor y el placer, se alcanza la meta, esa meta que está por delante como un punto de luz en la oscuridad de una noche de invierno. Este punto de luz puede recordarnos el pequeño candil de alguna triste buhardilla, pero - a medida que se sigue el sendero que conduce a dicha luz, mediante la fusión de los pares de opuestos - ese punto diminuto, frío y tembloroso, aumenta con firme irradiación y le recuerda al errante viajero la cálida luz de alguna ardiente lámpara.
>
> Sigue tu camino, oh Peregrino, con firme perseverancia, No existe candil ni lámpara terrenal alimentada con aceite. Acrecienta continuamente la irradiación hasta que el sendero termine en una llamarada de gloria, y el viajero de la noche se convierta en el hijo del sol y atraviese los portales de ese radiante orbe.
