---
title: Conferencia IV - La evolución del hombre, el pensador
---

# <Pin lang="es">55</Pin> <Pin lang="en">75</Pin> LA EVOLUCION DEL HOMBRE, EL PENSADOR

## CUARTA CONFERENCIA

<p><Pin lang="es">57</Pin> <Pin lang="en">77</Pin> Esta es la cuarta de una serie de conferencias dadas este último mes, y por su intermedio se tendrá una idea de uno de los fundamentales principios de la evolución, viéndolo actuar en el sistema solar.</p>

Recapitulemos brevemente lo expuesto, a fin de encarar el tema de esta noche con ciertas ideas claramente formuladas. Vimos que la interpretación del proceso de la naturaleza implica un concepto triple que concierne a los aspectos vida y sustancia y a su estrecha interrelación mediante la facultad de la inteligencia, manifestándose como grado de conciencia. Dicha interrelación producirá finalmente la perfecta expresión (por medio de la materia) del consciente propósito de alguna entidad interna. Trato de destacar que mi objetivo es presentar una hipótesis y sugerir que quizás contenga el germen de una posible <Pin lang="en">78</Pin> verdad, y que para algunos parece ser la forma más clara de explicar el misterio del universo. Vimos que las tres partes de un gran todo son: Espíritu o Vida, manifestándose por medio de un segundo factor llamado sustancia o materia, que utiliza un tercero, la inteligencia. En la gradual síntesis de los tres aspectos componentes de la Deidad puede verse la evolución de la conciencia.

Después llegamos, en forma más técnica, a discutir el tema de la sustancia, sin tratar las sustancias o los elementos diferenciados, sino el concepto de una sustancia primordial, retrotrayéndonos todo lo posible a lo que Sir Williams Crookes llamó "protilo", o sea lo subyacente en todo lo tangible u objetivo. Consideramos el átomo, y vimos que recientemente fue definido como una unidad de fuerza o <Pin lang="es">58</Pin> energía; consistiendo en una carga de electricidad positiva que energetiza cierto número de partículas negativas. Evidenciase que el minúsculo átomo químico y físico es en sí un sistema solar con la misma conformación general del sistema mayor, con análoga actividad y regido por leyes similares, y hallamos que tiene un sol central en cuyo torno giran en definidas órbitas los electrones. También observamos que los elementos químicos sólo difieren <Pin lang="en">79</Pin> según el número y disposición de los electrones, alrededor de la positiva carga central. De allí pasamos a considerar el alma o siquis del átomo, y encontramos que los científicos reconocen que el átomo posee cualidades, denota vestigios de mente o inteligencia, y es capaz de discernir, seleccionar y elegir.

Seguidamente procedimos a relatar lo que parece un cuento de hadas. Nos imaginamos al ser humano como un átomo, y vimos la semejanza de ambos y que atrae y mantiene dentro de su esfera de influencia, la materia de sus cuerpos físico, emocional y mental, del mismo modo que los electrones se mantienen girando alrededor de su punto focal central. Fue factible expandir aún más la idea y fijamos nuestra atención sobre el planeta, imaginándolo de naturaleza análoga a la del átomo humano y al del ultérrimo átomo de sustancia, que sólo es la expresión de una vida que se manifiesta por medio de una forma esferoidal y lleva a cabo un propósito inteligente. Entonces llegamos a la culminación, consideramos al sistema solar como un átomo cósmico energetizado por la vida del Logos.

Por lo tanto, hemos considerado cuatro clases de átomos:

1. Primero, el átomo químico y físico.
2. Segundo, el átomo humano u hombre.
3. <Pin lang="en">80</Pin>Tercero, el átomo planetario, energetizado por el Logos planetario u Hombre celestial.
4. Cuarto, el átomo solar habitado por el Logos o Deidad solar.

<p><Pin lang="es">59</Pin> Si es correcto nuestro concepto fundamental, si hay algo de realidad en nuestra hipótesis y si existe un fondo de verdad en nuestra idea de que el átomo compone los elementos, debemos reconocerlo como una vida que actúa inteligentemente por medio de una forma. Quizás así podrá demostrarse que el hombre es también una vida o centro de energía, manifestándose por medio de sus cuerpos, y, además, que un planeta es asimismo el medio de expresión de un centro mayor de energía, y que de acuerdo a la Ley de analogía llegaremos a probar en el futuro que existe un Dios o Vida central detrás de la naturaleza material, y una Entidad que actúa conscientemente a través del sistema solar.</p>

En la conferencia anterior consideramos otra fase de la manifestación. Estudiamos el átomo en sí, vimos cuando entra en relación con otros átomos, y que por mutua coherencia forman grupos o conglomerados de átomos; en otras palabras, lo consideramos como elemento constructor de las distintas formas de los reinos de la naturaleza, y observamos que en el proceso de evolución los átomos gravitan como electrones hacia puntos centrales, convirtiéndose a su vez en <Pin lang="en">81</Pin> electrones. Así cada forma es un conglomerado de vidas menores.

Consideramos después sucintamente, los diferentes reinos de la naturaleza y trazamos el desarrollo del alma o siquis, en todos ellos. Ya habíamos dicho que el átomo posee inteligencia o poder de discernir y que en la construcción de las formas de los reinos mineral, vegetal y animal, aparece lo que entendemos por sensación, teniendo así los rudimentos de la emoción o sentimiento en embrión -reflejo del amor en el plano físico. Éste es un aspecto de la triple naturaleza de Dios, la inteligencia, manifestándose en el átomo; y por medio de la forma se manifiesta el amor o cualidad de atracción. Esto también puede explicarse como el reconocimiento de que en estos dos aspectos de la vida divina central, existe la tercera persona de la Trinidad logoica colaborando con la segunda; tenemos también la actividad inteligente de la divinidad o el aspecto Espíritu Santo, <Pin lang="es">60</Pin> actuando en conexión con el segundo aspecto, el Hijo, constructor de las formas. La Biblia, en Prov. 8, expresa esto en forma interesante, donde la sabiduría clama en voz alta (la sabiduría representa al aspecto crístico en el Antiguo Testamento), y después de señalar que Él era con Dios antes de la creación, dice: "... estableció los cimientos de la tierra, con Él <Pin lang="en">82</Pin> estaba como maestro trabajador o constructor". Los estudiosos harían bien en estudiar este capítulo en relación con las ideas expuestas, asegurándose de que la traducción sea exacta.

Vamos a considerar ahora el tema de la evolución del hombre, el pensador. Veremos que en el hombre interviene otro aspecto de la divinidad. Browning, en Paracelsus, abarca el tema en forma interesante, resumiéndolo de la manera siguiente:

> Él (Dios) mora en todo.
> Desde el ínfimo comienzo de la vida hasta el fin,
> el hombre -culminación de este esquema
> del ser, la culminación de esta esfera
> de la vida: cuyos atributos han sido por doquier
> diseminados en el mundo visible,
> pudiendo ser combinados estos tenues fragmentos,
> destinados a ser unidos en un todo maravilloso,
> cualidades imperfectas en la creación,
> que sugieren una criatura increada,
> alguna etapa donde todos esos rayos diseminados
> deberían converger en las facultades del hombre.

Por lo tanto, habiendo descubierto dos aspectos de la divinidad, en el átomo y en la forma, hallaremos la perfecta triplicidad en el hombre. Sabemos que el hombre está hecho a imagen de Dios, y por eso debemos verlo reflejarse <Pin lang="en">83</Pin> en la triple naturaleza del Logos. Debe demostrar inteligencia, expresar amor y manifestar voluntad. Consideremos algunas definiciones del hombre en diccionarios y libros. El Standard Dictionary da una definición muy poco interesante: el <Pin lang="es">61</Pin> hombre es "un individuo de la raza humana", y sigue una larga serie de sugestivas derivaciones de la palabra hombre, en diferentes idiomas, y concluye diciendo que muchas de ellas son improbables. A mi entender, la etimología más satisfactoria es la que deriva de la palabra de raíz sánscrita "man", hombre, que significa "el que piensa". Annie Besant, en una de sus obras, da la siguiente definición excepcionalmente clara: "El hombre es el ser en que el supremo espíritu y la ínfima materia están vinculados por la inteligencia". Esta definición describe al hombre como el punto de convergencia de las tres líneas de evolución: el espíritu, la materia y el intelecto vinculador. Unifica el yo y el no-yo, mediante la relación entre ambos. Es el conocedor, lo conocido y el conocimiento. ¿Cuál es, pues, el propósito del intelecto y del conocimiento? Con toda seguridad su propósito consiste en adaptar la forma material a las necesidades y exigencias del espíritu inmanente; permite al pensador que reside en el cuerpo, ser utilizado inteligentemente y para algún propósito definido; también que debe existir <Pin lang="en">84</Pin> con el fin de que la central unidad energetizadora pueda controlar constructivamente su aspecto negativo. Todos somos entidades animadoras de una forma, que por medio de la inteligencia procuramos utilizarla para un especial propósito existente en la consciente voluntad del verdadero ser.

En un libro esotérico muy antiguo - tan antiguo que no es posible asegurar su fecha - hallamos una ilustradora definición del hombre, de acuerdo con el concepto que estamos explicando. Define al hombre como "la Vida y las vidas". Hemos visto que el átomo es una vida que se manifiesta por intermedio de una minúscula esfera, de la cual es el centro. Vimos también que toda forma mineral, vegetal y animal, es un conglomerado de vidas. Pasemos a la siguiente etapa de la gran escala de evolución, y hallaremos que el ser humano es la lógica secuencia de estos precedentes desarrollos. Primeramente, la sustancia primordial que en esencia es energía inteligente; después la materia atómica, con <Pin lang="es">62</Pin> toda su variada actividad, formando la combinación elemental; luego la forma o conglomerado de átomos, hasta llegar al que mora en la forma, que no sólo es de activa inteligencia e inherente atracción y amor, sino también resuelta voluntad. El "morador interno" tomó posesión de la forma cuando ya tuvo cierto grado de preparación y las vidas componentes <Pin lang="en">85</Pin> habían alcanzado cierta capacidad vibratoria. Ahora la está utilizando y repite dentro de su propia esfera de influencia, la obra de un átomo de materia, aunque no se manifiesta de una manera ni dos, sino de tres. Por lo tanto, en el hombre tenemos realmente y en verdad, lo que el cristiano llama "imagen de Dios". Para todos los pensadores debe ser evidente que la única manera de conocer a Dios es por el estudio de Su naturaleza o Su cualidad síquica. Sabernos que Dios es inteligencia, que es amor, o la gran fuerza atractiva del sistema solar y la enorme voluntad o propósito detrás de todo lo manifestado. Las Escrituras del mundo representan a la Deidad bajo estos tres aspectos y Se manifiesta triplemente en la naturaleza.

La evolución de la materia se desarrolla gradualmente, siendo a su vez complementada por la lenta acción de la interna cualidad subjetiva de la vida de Dios, cuya esencial naturaleza queda así demostrada. Primeramente, tenemos un aspecto, luego otro y finalmente un tercero, teniendo así la maravillosa combinación y consumación, el ser humano, que sintetiza los tres aspectos y es la totalidad de los divinos atributos, aunque todavía muy embrionarios, y que debe repetir en su ciclo <Pin lang="en">86</Pin> evolutivo el idéntico proceso seguido por el átomo. Así como el átomo sigue su curso interno y posteriormente debe ser atraído por otros átomos, para fusionarse y mezclarse y formar un grupo, análogamente el átomo humano debe hallar el lugar que le corresponde dentro de una forma mayor.

Por consiguiente, consideremos brevemente el proceso evolutivo del ser humano. Hemos visto que en él convergen las tres líneas, que es un punto de síntesis, que aún <Pin lang="es">63</Pin> predomina un aspecto, el de la inteligencia, y que el segundo aspecto de amor-sabiduría recién está haciendo sentir su presencia, teniendo en embrión el aspecto Superior, la voluntad espiritual.

A casi todos se nos ha enseñado a creer en el concepto bíblico de "la caída del hombre", pero pocos son hoy los que creen en este relato tal como aparece en el tercer capitulo del Génesis, y para la mayoría es una interpretación alegórica. ¿Qué oculta verdad subyace en esa curiosa historia? Sencillamente, que la verdad acerca del descenso del espíritu en la materia, le es impartida a la infantil mentalidad del hombre por medio de un cuadro simbólico. La convergencia de las tres líneas supone un doble proceso. Por una parte, tenemos el descenso de la entidad, la vida central, a la materia, y la encarnación del espíritu; por <Pin lang="en">87</Pin> otra, el ascenso fuera de la materia de esa vida o espíritu, más todo lo adquirido mediante la utilización de la forma. Experimentar la materia, morar en la forma, energetizar la sustancia, abandonar el Jardín del Edén (donde no hay lugar para el necesario desenvolvimiento) y el deambular del Hijo Pródigo en un país lejano, constituyen las distintas etapas representadas en la Biblia cristiana, donde el hombre descubre que él no es la forma, sino la entidad que la utiliza. Es inteligencia y, por lo tanto, está hecho a imagen de la tercera Persona de la Trinidad; es amor, y en él se manifestará algún día perfectamente el aspecto amor de la Deidad, y podrá exclamar con su hermano mayor el Cristo, en respuesta a la demanda: "Señor, muéstranos al Padre", y así "el que me ha visto a mí, ha visto al Padre", porque Dios es amor y, finalmente, por medio del hombre se manifestará el superior aspecto de la voluntad de Dios, y será entonces perfecto como perfecto es Su Padre en los cielos. Así como en la evolución de la sustancia podemos ver tres etapas - la energía atómica, la coherencia grupal y la eventual síntesis - las mismas etapas aparecen en la evolución del hombre. En las primeras etapas de la evolución humana, que podríamos llamar atómica, el <Pin lang="es">64</Pin> hombre reconoce gradualmente que es una <Pin lang="en">88</Pin> unidad autoconsciente, con individualidad propia. Quien ha educado niños, conoce bien esta etapa. En la constante repetición de "mío, mío, mío", puede observarse la etapa de apropiación para sí, sin pensar en los demás. Los niños son por naturaleza, sensata e inteligentemente egoístas. Es la etapa del gradual reconocimiento de la existencia separatista, y la cada vez más potente utilización, por el átomo humano, de su interna fuerza atómica. El niño se rebela contra la forzada vigilancia de quienes tratan de protegerlo, pues cree bastarse a sí mismo. Esto se observa en el individuo y en la raza.

A medida que la vida transcurre, el hombre pasa de la etapa atómica a otra superior y mejor, donde reconoce sus relaciones grupales, se da cuenta que tiene responsabilidades grupales y debe desempeñar funciones con otros átomos. Empieza a hacerse sentir la conciencia grupal. Así el átomo humano encuentra su lugar en el grupo, en la unidad mayor a que pertenece, y comienza el aspecto amor. El hombre ha pasado de la etapa atómica a la etapa de la coherencia grupal.

Posteriormente llega a la etapa en que se da cuenta de que no sólo tiene responsabilidades con el grupo, sino que existe algo mayor, <Pin lang="en">89</Pin> tiene conciencia de que es parte de una gran vida universal, subyacente en todas las agrupaciones; que no es un átomo universal ni tan sólo parte de un grupo, sino que al sumergirse en el grupo sin perder su identidad, el grupo mismo debe fusionarse nuevamente con la conciencia de esa gran Identidad, la síntesis de todo. Así llega a la etapa final de la inteligente apreciación de la divina unidad.

Esta triple idea está sintetizada en la notable frase donde Jehová le dice a Moisés, el hombre representativo: "Yo soy ese yo soy". Si dividimos en tres partes esta frase tendremos la idea de lo que he tratado de exponer hoy: primero, la conciencia atómica YO SOY; después el grupo, YO SOY ÉSE, la conciencia de que él no es una individualidad separada ni <Pin lang="es">65</Pin> sólo una unidad autocentrada, tampoco una entidad autoconsciente, sino algo aún superior. Entonces el hombre alcanza ese reconocimiento que lo conducirá a sacrificar su identidad al servicio del grupo y a sumergir su conciencia en la del grupo. De esta consciente unión nada sabemos todavía. Esto ocurrirá cuando esa etapa superior del YO SOY ESE YO SOY no constituya un ideal imposible, un concepto visionario, sino una realidad fundamental; cuando los hombres en conjunto se reconozcan como expresión de la vida universal, <Pin lang="en">90</Pin> y la conciencia grupal misma se fusione con la conciencia de todo el conjunto de grupos.

Supongo y tengo la esperanza de que salimos rápidamente de la etapa atómica y que nuestra esfera de influencia e interés no está limitada por un muro atómico, sino que nos estamos haciendo radiactivos, utilizando un término familiar. Cuando así sea, no estaremos circunscritos ni limitados por nuestros propios cascarones ni por los estrechos confines de nuestra vida personal, contrariamente comenzaremos a irradiar y hacer contacto con otros átomos, llegando así a la segunda etapa, la de atracción.

Por lo tanto, ¿Cuál es la meta para cada uno de nosotros? ¿Cuál la de estos diferentes átomos de los que nos ocupamos? Las antiguas Escrituras orientales dicen que la meta del átomo de la sustancia es la autoconciencia. ¿Cuál es, por lo tanto, la meta del átomo humano que ya es autoconsciente, se ha individualizado y se guía a sí mismo por medio de su voluntad? ¿Qué tiene el hombre por delante? Sencillamente la expansión de su conciencia hasta incluir la conciencia de la excelsa Vida o Ser, en cuyo cuerpo es una célula. Nuestro cuerpo físico está, por ejemplo, constituido por innumerables vidas menores o átomos, cada uno separado del otro, y caracterizado por su propia e inherente actividad, y <Pin lang="en">91</Pin> cada uno forma una esfera, que contiene dentro de su periferia otras esferas menores o electrones.

Hemos visto que el hombre es la carga positiva, que mantiene a su multiplicidad de átomos o vidas menores, <Pin lang="es">66</Pin> energetizados y unidos en formas coherentes. Cuando en la muerte se retira el aspecto espíritu, la forma se desintegra y disuelve, y estas pequeñas vidas conscientes, habiendo cumplido su función, se dispersan. La conciencia del átomo dentro del cuerpo es muy distinta de la conciencia del hombre, y esto lo comprenderemos si reflexionamos un poco. Si aceptamos que el hombre es una célula, en una esfera mayor, ¿no sería posible la existencia de una conciencia que fuera para el hombre lo que su conciencia es para las células de su cuerpo? ¿No sería posible que nuestra meta inmediata fuera obtener esa conciencia, en el mismo sentido en que el átomo de la sustancia tendrá que lograr algún día la conciencia de un ser humano? Sería esto lo que pensaba Browning cuando dijo: "El género humano está constituido por cada uno de los hombres, y en dicha síntesis termina el relato". Nos presenta aquí el concepto de un hombre superior, síntesis o suma total de todas las unidades menores. Esta síntesis podría ser la gran Vida o Entidad planetaria que está detrás de nuestra manifestación planetaria y es la suma total de la conciencia grupal. Sugiero que así como la autoconciencia es la meta para todas <Pin lang="en">92</Pin> las formas subhumanas de vida, y la conciencia grupal o la del Hombre celestial es la meta del ser humano, así también existirá para Él una meta, y la realización puede ser el desarrollo de la conciencia de Dios; de manera que Él debe luchar para lograr el conocimiento que posee el Logos solar.

De este modo podemos ver la unidad de conciencia desde el más diminuto átomo hasta la Deidad misma, abriendo ante nosotros una admirable perspectiva de posibilidades, pudiendo verse también la vida de Dios en Su triple y esencial manifestación, desarrollándose en una conciencia siempre en expansión, expresándose en el átomo de sustancia, ampliándose por medio de la forma, hasta llegar al punto culminante en el hombre y, luego, continuar su curso hasta manifestarse como la conciencia planetaria, suma total de <Pin lang="es">67</Pin> todos los estados de conciencia en nuestro planeta Tierra, hasta llegar a la Vida fundamental y básica que sintetiza todas las evoluciones planetarias, dentro de Su esfera mayor, el sistema solar. En resumen, tenemos cuatro estados de inteligente actividad que podemos o denominar: conciencia, autoconciencia, conciencia grupal y conciencia de Dios, que se manifiestan respectivamente mediante los cuatro tipos de átomo: primero, el átomo químico y todas las formas atómicas; segundo, el átomo humano; tercero, el átomo planetario, y, <Pin lang="en">93</Pin> finalmente, el omniabarcante átomo solar. Animando a estas formas atómicas, podemos ver la manifestación de todos los tipos de vida subhumana, desde la vida del átomo de la sustancia, hasta la vida animadora de los animales superiores; luego esa vida denominada humana, el hombre, el pensador; después el Hombre celestial, y, finalmente, la excelsa Vida del sistema solar, que los cristianos denominan Dios o Logos.

Browning expresa la idea de la gradual expansión de la conciencia de un ser humano hacia algo mayor y más vasto, con las palabras siguientes:

> Cuando la raza llegue a ser perfecta,
> es decir, como un hombre; todo lo dado al género humano,
> y hasta ahora producido por el hombre, habrá llegado a su fin;
> pero en el hombre íntegro se inicia nuevamente una tendencia hacia Dios.
> Las predicciones auguraron el acercamiento del Hombre;
> en el yo del hombre surgen augustas anticipaciones, símbolos,
> tipos de tenue esplendor siempre existentes
> en ese eterno círculo perseguido por la vida.
> Los hombres comienzan a cruzar los límites de la naturaleza,
> <Pin lang="es">68</Pin> descubriendo nuevas esperanzas y obligaciones, que rápidamente suplantan
> sus propias alegrías y pesares; llegan a ser demasiado grandes
> para los estrechos credos del mal y del bien, que se desvanecen
> ante la inmensurable sed de bien; en tanto
> surge de ellos la paz en forma creciente.
> <Pin lang="en">94</Pin> Estos hombres se hallan ya en la tierra,
> serenos en medio de las criaturas semi formadas que los rodean,
> que deberían ser salvadas por ellos y unirse a ellos
