---
title: Géminis -  Espejismo e Ilusión
---

# Paz de la sustancia mental o chitta

> [Los Trabajos de Hércules](/los-trabajos-de-hercules/trabajo3-parte2#la-lección-del-trabajo)

## La Lección del Trabajo

El total de esta historia significa realmente la lección que es la primera que todos los aspirantes tienen que dominar, y la que es imposible aprender, hasta que se haya pasado por las pruebas en Aries y en Tauro. Entonces, en el plano físico, en el campo del cerebro y en su estado de conciencia despierta, el discípulo tiene que registrar contactos con el alma y reconocer sus cualidades. El no debe ser más el místico visionario, sino que debe agregar a la realización mística el conocimiento oculto de la realidad. Esto es olvidado a menudo por los aspirantes. Ellos descansan contentos con la aspiración, con la visión de la meta celestial. Han forjado en el crisol de la vida, un equipaje que se caracteriza por las sinceridad, el buen deseo, el carácter agradable, y son conscientes de la pureza del motivo, buena voluntad para cumplir los requerimientos, y la satisfacción de que ellos han alcanzado un cierto estado de desarrollo que los autoriza a seguir. Pero una cosa falta aún: no tienen lo que podría llamarse "la técnica de la presencia"; no tienen privilegio y prerrogativa para poseer. Ellos creen en la realidad del alma, en la posibilidad de la perfección, en el sendero que debe ser hollado; pero la creencia no ha sido todavía trasmutada en conocimiento del reino espiritual. ¡Y no saben cómo lograr su meta! Por lo tanto, como lo hizo Hércules, emprenden la quíntuple búsqueda.

<p>
<Pin lang="en">71</Pin> La primera etapa de la búsqueda está llena de estímulo para ellos, habiendo sido capaces de reconocer el acontecimiento. Como Hércules, se encuentran <Pin lang="es">67</Pin> con Nereo, el símbolo del yo superior, y más tarde en la historia del discípulo, él es el símbolo del Maestro que enseña. Una vez puestos en contacto, especialmente en las primitivas etapas de la búsqueda, el yo superior se manifestará como un destello de iluminación y ¡he aquí! ha desaparecido; como una repentina comprensión de la verdad, tan elusiva, huidiza, que al principio el discípulo no puede asirla; como una sugerencia que se deja caer en el estado consciente en momentos de una concentrada atención, cuando la mente se mantiene firme y las emociones temporalmente cesan de controlar.
</p>

En el caso de un discípulo más avanzado que ha establecido contacto con su alma y que, por consiguiente, se puede suponer que está listo para recibir instrucción de uno de los grandes Maestros de la Raza, se encontrará que el Maestro trabaja exactamente como lo hizo Nereo. No se puede entrar siempre en contacto con Él, y sólo ocasionalmente el discípulo entra en comunicación con Él. Cuando lo hace, no necesita esperar felicitaciones por su magnífico progreso, ni encontrará una cuidadosa explicación de su problema, ni el prolijo diseño del trabajo que deberá hacer. El Maestro dará una sugerencia y desaparecerá. Hará una insinuación y no dirá más. Corresponde al discípulo actuar lo mejor que pueda y llevar hasta el fin la sugerencia, la cual él deberá juzgar si es sabia.

Muchos ocultistas bien intencionados lo conducirían a uno a creer que los Maestros de Sabiduría se toman un interés personal con ellos, que los sobrecargados Guías de la Raza, no tienen mejor ocupación que decirles personalmente cómo vivir, cómo resolver sus problemas y cómo, minuciosamente, guiar sus empresas. Me gustaría aquí registrar mi protesta contra cualquier intento de rebajar el trabajo de los Grandes. Las razones por las cuales Nereo, el Maestro, es elusivo y no da sino un destello de pensamiento o de momentánea atención al aspirante, son dos:

Primero, el aspirante individual no es de interés personal para el Maestro hasta que ha llegado el punto en su evolución en que está en tan estrecha relación con su alma, que llega a ser un servidor <Pin lang="en">72</Pin> magnético en el mundo. Entonces, y sólo entonces, le será beneficioso al Maestro enviarle un pensamiento, y darle una sugerencia. Entonces, a medida que esas sugerencias son seguidas, Él puede darle más, pero, y éste es el punto que debe ser enfatizado, sólo en conexión con el trabajo que debe hacer en el campo del servicio del mundo. Los aspirantes necesitan recordar que ellos llegan a ser maestros sólo dominando, y que se nos enseña a ser maestros y se nos lleva a la posición de miembro en el grupo de servidores del mundo, a través de los esfuerzos de nuestra propia alma. Esa alma es un divino hijo de Dios, omnisciente y <Pin lang="es">68</Pin> omnipotente. A medida que el gemelo inmortal aumenta en poder y esplendor el hermano mortal disminuye.

Segundo, los cuerpos físicos de los aspirantes no están en condición de soportar la elevada vibración de aquél que se ha realizado. El cuerpo sería destrozado y el cerebro sería sometido a demasiado esfuerzo, si uno de los Maestros hiciera constante contacto con un discípulo, antes de que él hubiera aún aprendido a conocer a Nereo como el símbolo de su propio yo superior. Cuando por nuestros propios esfuerzos estemos empezando a vivir como almas, y cuando por nuestro propio autoiniciado empeño estemos aprendiendo a servir y a ser canales de energía espiritual, entonces conoceremos a Nereo más íntimamente; y entonces, casi inevitablemente, nuestro conocimiento del trabajo que los Grandes tienen que hacer, será tan vital y tan real, que renunciaremos a nuestro propio deseo por el contacto y buscaremos sólo levantar la carga que ellos llevan.

Al principio de su búsqueda, Hércules se encontró con Nereo; pero no se sintió impresionado y por lo tanto se extravió por otras partes, buscando furiosamente satisfacer su aspiración. Al fin de su búsqueda él se encuentra con Atlas, soportando la carga del mundo, y se siente tan impresionado con el peso de esa responsabilidad y la carga que Atlas, el gran Maestro, está llevando, que olvida todo acerca de la meta y su búsqueda de las manzanas de oro, y se esfuerza por levantar la carga de los hombros de Atlas. Cuando los aspirantes en el campo religioso y en la iglesia, en el campo teosófico, en el campo de los rosacruces, y en los muchos grupos en los cuales ellos gravitan, hayan aprendido a olvidarse de ellos mismos para <Pin lang="en">73</Pin> servir, y a perder de vista su egoísmo espiritual ayudando a la humanidad, habrá una más rápida reunión de los iniciados a través del portal en el Sendero que conduce de la oscuridad hacia la Luz, y de lo ilusorio a lo Real. Uno de los Grandes ha dicho que "hay personas que, sin tener nunca ningún signo externo de egoísmo, son intensamente egoístas en su interna aspiración espiritual". (p. 360, The Mahatma Letters to A. P. Sinnett). Y más tarde ofrecen ante nosotros un estupendo ideal que hace un corte en la raíz del egoísmo espiritual: "Si en nuestra visión de las más altas aspiraciones por el bienestar de la humanidad, éstas se manchan con egoísmo, en la mente del filántropo, acecha la sombra del deseo por el propio beneficio..."

Hércules, el discípulo, ha conocido el toque del yo superior, pero no lo conocía lo suficiente para permanecer con Nereo. Por lo tanto, se volvió al sur, o de regreso al mundo. Él ha tenido su momento supremo, cuando trascendió el estado consciente de su cerebro y platicó con su alma. Pero esto no dura, y se abandona nuevamente al estado de conciencia del cerebro y <Pin lang="es">69</Pin> entra en otra experiencia. Tiene que luchar con Anteo, la serpiente (o gigante). Pero, esta vez, es la serpiente del espejismo astral y no principalmente la serpiente del deseo. Es con los hechizos del psiquismo inferior que él tiene que luchar, y éstos parecen, en las primeras etapas, atraen inevitablemente el interés de los aspirantes. Cualquier maestro que haya trabajado con aquéllos que están buscando el Camino, conoce el hechizo bajo el cual ellos pueden caer tan fácilmente. Según el temperamento del aspirante así será el hechizo. Algunos se desvían por los fenómenos espiritistas. En el esfuerzo para penetrar el velo, se sienten absorbidos por el lado inferior del espiritismo y pasan mucho tiempo en la sala de sesiones, estudiando una y otra vez los mismos viejos fenómenos de materialización, comunicación con los espíritus y manifestaciones, no hago aquí referencias a las verdaderas investigaciones científicas de aquellos que ahondan en su indagación, y que están dotados para hacer esto. Me refiero a la participación del ignorante en ciertos tipos de trabajo en la sala de sesiones. Esto intriga al hombre y a la mujer comunes <Pin lang="en">74</Pin> y los pone a merced del igualmente ignorante médium o del charlatán, pues ellos no están equipados para verificar de ninguna manera lo que ven y oyen.

La serpiente puede tomar la forma del aspecto más común de los fenómenos psíquicos. El aspirante se interesa en la escritura automática, o aprende a sentarse y escuchar "voces", se vuelve astralmente clarividente y clariaudiente, se une a la confusión del plano psíquico, y así cae dentro de las trampas y peligros latentes del astralismo. Se vuelve negativo, porque está todo el tiempo tratando de oír o ver lo que no es físico. Porque nosotros compartimos con los gatos y los perros la capacidad de ser clarividentes y clariaudientes, a su debido tiempo seguramente veremos y oiremos, si no en realidad, al menos a través del poder de esa facultad creadora que todos poseemos, la imaginación creadora. Pero en una forma y otra, el aspirante que ha dejado a Nereo, se encontrará con la serpiente y tendrá que luchar con ella. Como el mito lo expresa, por un largo tiempo Hércules no pudo vencer, pero cuando levantó a la serpiente en el aire triunfó.

Hay gran verdad debajo de este simbolismo. El aire ha sido siempre mirado como el símbolo del elemento relacionado con el plano de Cristo, llamado en la terminología teosófica y en el oriente, el plano búdico. El plano astral es el reflejo distorsionado del plano búdico, y sólo cuando elevemos el espejismo dentro de la clara luz del alma de Cristo, veremos la verdad como es, y nos volveremos invencibles. Solemnemente, yo me esforzaría por convencer a todos los aspirantes, a renunciar a todo interés en los fenómenos psíquicos, y a excluir tan firmemente como puedan el plano astral, hasta que hayan desarrollado el poder de ser intuitivos, y de <Pin lang="es">70</Pin> interpretar sus intuiciones por medio de una mente bien desarrollada, bien provista y bien entrenada.

La próxima etapa de la búsqueda de Hércules es igualmente aplicable a la humanidad en conjunto. El cayó en las garras de Busiris, que pretendía ser un gran maestro. Por un largo período de <Pin lang="en">75</Pin> tiempo Hércules fue mantenido en cautiverio. El mundo hoy en día está lleno de maestros, y, como Busiris, ellos basan su enseñanza en portentosas pretensiones; afirman que son iniciados, que son los custodios de la verdad, y que tienen un camino seguro y cierto de desarrollo que debe, inevitablemente, capacitar al aspirante para realizarse. Ellos sostienen su posición con promesas; crean la atmósfera para una fuerte relación de la personalidad, y utilizando la sinceridad y la aspiración del buscador tras la verdad, reúnen a su alrededor grupos de hombres y mujeres que inocente y sinceramente creen en la verdad de lo que ellos pretenden, y los atan al altar del sacrificio por un mayor o menor período de tiempo. El verdadero iniciado es conocido por su vida y actos, está demasiado ocupado sirviendo a la raza, para perder el tiempo en interesar a la gente sobre sí mismo, y no puede hacer promesas más allá que decir a cada aspirante: "Éstas son las reglas antiguas, éste es el camino que todos los santos y Maestros de Sabiduría han recorrido, ésta es la disciplina a la cual deben sujetarse, y si sólo tratan de resistir y tener paciencia, la meta seguramente será alcanzada".

Pero Hércules se liberó, como lo hacen todos los buscadores sinceros; y habiendo escapado del mundo psíquico y pseudo‑espiritual empezó a servir. Primero se liberó a sí mismo bajo el símbolo de Prometeo, el que significa Dios encarnado, liberándolo de la tortura de los buitres de lo antiguo. El plexo solar, el estómago y el hígado son exteriorizaciones, si puedo expresarlo así, de la naturaleza del deseo, y Hércules se liberó a sí mismo de los buitres del deseo, que por largo tiempo lo habían torturado. Dejó de ser egoísta, y de buscar su propia satisfacción. Había tenido dos amargas lecciones en este signo y por este ciclo en particular estaba relativamente libre. Prometeo, el Dios interior, podría adelantarse al servicio del mundo y levantar la carga de Atlas.

Después del sacrificio viene la recompensa, y Hércules recibió su gran sorpresa después de liberar a Prometeo y Atlas. Habiendo abandonado su búsqueda para ayudar al mundo, Atlas fue en su lugar al jardín y le trajo las manzanas <Pin lang="en">76</Pin> de oro, poniéndole en contacto con las tres hermosas doncellas, los tres aspectos del alma.

Al principio de su trabajo él se pone en contacto con su alma como Nereo; al final de su trabajo, habiendo superado muchos espejismos logra una visión grandemente acrecentada de su alma y la ve en sus tres aspectos, cada uno, <Pin lang="es">71</Pin> conteniendo en sí, la potencia de los tres principios de la divinidad. Eglé simboliza la gloria de la vida y el esplendor del sol poniente, la magnificencia de la manifestación en el plano físico. Ella le da una manzana a Hércules, diciendo, "El camino hacia nosotros es, siempre, a través de actos de amor". Erythena cuida la puerta, el alma, que está siempre abierta por Amor-Sabiduría, y le da a Hércules una manzana marcada con la palabra dorada Servicio. Hesperis, la estrella vespertina, la estrella de la iniciación, representa la Voluntad. Ella le dice a Hércules, "Recorre el Camino". Cuerpo, alma y espíritu; Inteligencia, Amor y Voluntad, avistados y contactados por el aspirante desinteresado a través del Servicio.
