---
title: Los tres objetivos del probacionista
---

# Los tres objetivos del probacionista

> [Cartas de meditación ocultista](/carta8#197-los-tres-objetivos-del-probacionista)

Durante el período en que el aspirante se halla en probación se espera que desarrolle tres cosas:

1. La aptitud de hacer contacto con su grupo o, en otras palabras, ser sensible a la vibración del grupo, del cual un determinado Maestro es el punto focal. Al principio establece contacto a raros intervalos. Durante la primera parte de su período de probación, mientras está bajo observación, sólo es capaz de sentir y retener la vibración del grupo (que es la vibración del Maestro) durante un periodo muy breve. En un momento de elevación se vinculará con el Maestro y el grupo; todo su ser será inundado con esa elevada vibración que surgirá como una explosión del color del grupo. Luego se apaciguará, volverá a su estado anterior y perderá el contacto. Sus cuerpos no están suficientemente refinados y su vibración es demasiado inestable para retenerla durante mucho tiempo.
 Pero a medida que transcurre el tiempo (períodos extensos o breves, de acuerdo al anhelo del estudiante) la frecuencia de los momentos de contacto aumenta, puede retener la vibración mayor tiempo y no vuelve a su estado normal tan fácilmente. Llega por fin el momento en que puede mantener el contacto regularmente estable. Entonces pasa a la segunda etapa.

2. <Pin lang="en">268</Pin> La facultad de pensar en forma abstracta, o el poder de hacer contacto con la mente superior, vía el cuerpo causal. Debe aprender a hacer contacto con la mente inferior, simplemente como un instrumento para llegar a la superior, y así trascendería hasta polarizarse en el cuerpo causal. Después, por medio del cuerpo causal, se vinculará con los niveles abstractos. Hasta no realizar esto le resultará imposible establecer contacto con el Maestro, pues, como ya se ha dicho, el estudiante debe elevarse desde su mundo (el inferior) al mundo del Maestro (el superior).

 Ahora bien, ambas cosas -el poder de llegar al Maestro y a Su grupo y el poder de polarizarse en el cuerpo causal y llegar a niveles abstractos- son definidamente el resultado de la meditación, como ha sido aclarado en cartas anteriores. Por lo tanto, no es necesario recapitular la información dada, excepto indicar que por la meditación constante y la facultad de concentrarse en el inmediato deber (que después de todo sólo es el fruto de la meditación practicada en la vida diaria) vendrá la creciente facultad para retener firmemente la vibración más elevada. He de reiterar una y <Pin lang="es">198</Pin> otra vez esta aparentemente sencilla verdad, que únicamente la similitud de vibración atraerá al aspirante al grupo superior a que pueda pertenecer, al Maestro que representa para él el Señor de su rayo, al Instructor del Mundo que le administrará los misterios, al Único Iniciador que efectuará la liberación final y al Centro del Hombre celestial en Cuyo cuerpo el aspirante halla su lugar. La actuación de la Ley de Atracción y Repulsión, en todos los planos, extrae la vida divina del reino mineral, del vegetal y del animal y también de la Deidad latente, limitada por el reino humano, <Pin lang="en">269</Pin> afiliando al hombre con su grupo divino. La misma ley lo libera de las formas sutiles que análogamente lo atan y lo fusionan de nuevo con su fuente animadora, el Señor de Rayo en cuyo Cuerpo se halla su Mónada. En consecuencia, el trabajo del probacionista consiste en armonizar su vibración con la del Maestro, purificar sus tres cuerpos inferiores para que no entorpezcan dicho contacto, y controlar su mente inferior en tal forma que no obstaculice el descenso de luz desde el triple Espíritu. Así puede hacer contacto con esa Tríada y con el grupo en el subplano mental superior, al cual pertenece por derecho y karma. Todo esto se logra por la meditación, y no existe ningún otro medio para alcanzar dichos objetivos.

 :::note Recuerda

 Por la meditación constante y la facultad de concentrarse en el inmediato deber (que después de todo sólo es el fruto de la meditación practicada en la vida diaria) vendrá la creciente facultad para retener firmemente la vibración más elevada. He de reiterar una y <Pin lang="es">198</Pin> otra vez esta aparentemente sencilla verdad, que únicamente la similitud de vibración atraerá al aspirante al grupo superior a que pueda pertenecer, al Maestro que representa para él el Señor de su rayo, al Instructor del Mundo que le administrará los misterios, al Único Iniciador que efectuará la liberación final y al Centro del Hombre celestial en Cuyo cuerpo el aspirante halla su lugar.

 :::

3. Equiparse emocional y mentalmente, **comprender y comprobar que tiene algo que dar al grupo al cual está afiliado esotéricamente**. Reflexionen sobre lo siguiente: a veces se hace demasiado hincapié en lo que el estudiante recibirá cuando sea un discípulo aceptado o probacionista. Diré con toda seriedad, el aspirante no dará los pasos deseados hasta que tenga algo para dar, algo que agregar para aumentar la belleza del grupo, algo que aportar a ese equipo disponible que el Maestro necesita para ayudar a la raza, y que acrecentará la riqueza del colorido grupal. Esto puede realizarse de dos maneras que interactúan mutuamente:
   1. Equipando, por el estudio y la aplicación, el contenido de los cuerpos mental y emocional.
   2. Utilizando ese equipo para servir a La raza en el plano físico, demostrando así a la Jerarquía observadora que el estudiante tiene algo que dar. También debe <Pin lang="en">270</Pin> demostrar que su único deseo es ser benefactor y servidor, más bien que codiciar y adquirir para sí. Esta vida de adquisición con el propósito de dar, debe tener por incentivo los ideales alcanzados en la meditación y por inspiración la afluencia de los niveles mentales superiores y de los <Pin lang="es">199</Pin> niveles búdicos, como resultado de la meditación ocultista.

Cuando se han obtenido estos tres resultados y la vibración superior alcanzada es más frecuente y estable, el probacionista da el siguiente paso y se convierte en discípulo aceptado.
