---
title: Flujo y reflujo
---

# Flujo y reflujo

> [Tratado sobre magia blanca](/tratado-sobre-magia-blanca/regla-1#en62)

Esto me lleva a considerar el séptimo punto que traté en mí anterior análisis de la Regla Uno. Dije que "la meditación del alma es de naturaleza rítmica y cíclica, como lo es todo en el cosmos. El alma respira y su forma vive por ello". La naturaleza rítmica de la meditación del alma no debe ser pasada por alto en la vida del aspirante. Hay un flujo y reflujo en toda la naturaleza, y en la marea del océano vemos la maravillosa representación de una ley eterna. A medida que el aspirante se ajusta a las mareas de la vida del alma, empieza a darse cuenta que existe un constante flujo, vitalización y estímulo, seguido por el reflujo inevitable y seguro de las inmutables leyes de la fuerza. Este flujo y reflujo puede verse actuar en los procesos de la muerte y de la reencarnación <Pin lang="es">58</Pin>. También se puede ver en el proceso de las vidas del hombre, porque alguna vidas son aparentemente pasivas e intrascendentes, lentas e inertes, desde el ángulo de la experiencia del alma, mientras que otras son vibrantes, plenas de experiencia y desarrollo. Esto deben recordarlo todos los trabajadores cuando procuran ayudar a otros a vivir correctamente. ¿Se hallan éstos en el reflujo, o están sometidos a la afluencia de la energía del alma? ¿Pasan por un período de pasividad temporaria, preparatorio de un mayor impulso y esfuerzo, donde el trabajo que debe realizar consiste en el fortalecimiento y la estabilización, con el objeto de capacitarse para poder "permanecer en el ser espiritual", o están sometidos a un influjo cíclico de fuerzas? En este caso el trabajador debe ayudar a dirigir y utilizar la energía, pues si está mal dirigida terminará arruinando vidas, pero si es utilizada sabiamente, dará como resultado un servicio pleno y fructífero.

Quien estudia a la humanidad puede también aplicar dichos pensamientos a los grandes ciclos raciales, y así descubrirá muchas cosas que son de gran interés. Estos impulsos cíclicos son también más frecuentes, rápidos y fuertes, en la vida del discípulo que en la vida del hombre común, algo muy importante <Pin lang="en">63</Pin> para nosotros, los cuales alternan con penosa rapidez. La conocida experiencia del místico en la montaña y en el valle, es sólo una forma de expresar este flujo y reflujo. A veces el discípulo camina en la luz del sol y otras en la oscuridad; unas veces conoce la alegría de la plena comunión y otras todo es oscuro y estéril; otras veces su servicio es una experiencia satisfactoria y fructífera, y cree que realmente puede ayudar, pero en otros casos siente que no tiene nada que dar y que su servicio es infecundo y sin resultado. Hay días en que todo lo ve claro y tiene la sensación de estar en la cima de la montaña, contemplando un paisaje bañado por el sol, donde todo se presenta nítido ante su vista. Sabe y siente que es un hijo de Dios; sin embargo, después descienden las nubes, pierde toda su seguridad y le parece no saber nada. Camina a la luz del sol, está abrumado por la luminosidad y el calor de los rayos solares y piensa cuánto tiempo durará esta experiencia desigual y este violento alternar de opuestos.

No obstante, una vez captado el hecho observa el efecto de los impulsos cíclicos y de la meditación del alma sobre su naturaleza-forma, se le aclara el significado, comprende que el aspecto-forma falla en responder, y su reacción a la energía es despareja. Entonces aprende que cuando pueda vivir en la conciencia del alma y alcanzar a voluntad esa "altitud elevada" (si puede expresarse así), las fluctuaciones de la vida-forma ya no lo afectarán. De este modo percibe el estrecho sendero del filo de la navaja que lo lleva desde el plano de la vida física al reino del <Pin lang="es">59</Pin> alma, y descubre que cuando pueda hollar el sendero con firmeza, será conducido fuera del mutable mundo de los sentidos, hacia la clara luz del día y al mundo de la realidad.

El aspecto forma de la vida se convierte entonces para él en <Pin lang="en">64</Pin> el campo de servicio y no en el de la percepción sensoria. El estudiante debe reflexionar sobre esta última frase y tratar de vivir como alma. Él mismo es responsable de los impulsos cíclicos emanados del alma, y entonces se conoce a sí mismo como la causa iniciadora y no está sujeto a los efectos.

:::note Recuerda

El aspecto forma de la vida se convierte entonces para él en <Pin lang="en">64</Pin> el campo de servicio y no en el de la percepción sensoria. El estudiante debe reflexionar sobre esta última frase y tratar de vivir como alma. Él mismo es responsable de los impulsos cíclicos emanados del alma, y entonces se conoce a sí mismo como la causa iniciadora y no está sujeto a los efectos.

:::

Visto desde otro ángulo tenemos dos factores, el aliento y la forma a la que el aliento energetiza e impele a la actividad. Un estudio detenido evidenciará que durante innumerables eones nos identificamos con la forma y hemos acentuado los efectos de la actividad impartida, pero no comprendimos la naturaleza del aliento ni conocido la naturaleza del Uno que respira. Ahora nos ocuparemos en este estudio de ese Uno, Quien, al respirar rítmicamente, impelerá a la forma a una correcta acción y control. Tal es nuestro objetivo y meta. Sin embargo, es necesaria la correcta comprensión si queremos apreciar inteligentemente nuestra tarea y sus efectos.

Una apreciación de los pensamientos mencionados debería dar al aspirante cierta comprensión del valor de su trabajo de meditación, en tanto que la idea de la respuesta cíclica al impulso del alma, se halla detrás de las actividades de la meditación matutina, del recogimiento del mediodía y de la recapitulación vespertina. En los dos aspectos de la Luna nueva y la Luna llena, tenemos un mayor flujo y reflujo. Tengan esto presente.

¡Que haya un constante y pleno fluir de fuerzas cíclicas, desde el reino del espíritu, sobre cada uno de nosotros, llamándonos al reino de la luz, del amor y del servicio y evocando en cada uno <Pin lang="en">65</Pin> una respuesta cíclica! ¡Qué haya un constante intercambio entre quienes enseñan y el discípulo que busca instrucción!
