---
title: Servicio y meditación
---

# Servicio y meditación

> [Tratado sobre magia blanca](/tratado-sobre-magia-blanca/regla-3#en93)

A través de los procesos de meditación que creciente y gradualmente se van sintetizando, llevados a cabo por el alma en su propio plano y en el del aspirante, el hombre manifiesta (en el cerebro físico) un punto de luz que se ha encendido ocultamente en el plano de la mente. La luz significa siempre dos cosas, la energía y su manifestación en la forma, porque luz y materia son términos sinónimos. El pensamiento del hombre y la idea del alma han encontrado un punto de contacto y ha venido a la existencia el germen de una forma mental. Cuando esta forma mental se complete, incorporará esa parte del gran Plan (en el que está trabajando la Jerarquía) que el hombre puede visualizar, captar e incluir en el plano mental. Esto es lo que se comprende por la palabra "servicio", en las primeras etapas de la aspiración del hombre, en sus primeros pasos en el sendero del discipulado y en las dos primeras iniciaciones. Al principio capta a tientas la idea de la unidad de la Vida y su manifestación, como Hermandad, existente entre todas las formas de esa Vida divina. Este ideal subjetivo conduce paulatinamente a la apreciación de la forma en que esta relación esencial puede desarrollarse prácticamente. Puede observarse su expresión en los grandes esfuerzos humanitarios, en las <Pin lang="en">94</Pin> organizaciones destinadas al alivio del sufrimiento humano y animal, y en los esfuerzos mundiales para el mejoramiento de las relaciones internas de naciones, religiones y grupos.

<p><Pin lang="es">79</Pin> En la actualidad un gran número de unidades humanas han hecho ya contacto con el Plan jerárquico, de manera que puede deducirse sin peligro, que el cerebro colectivo de la familia humana (esa entidad que llamamos el cuarto reino de la naturaleza) es sensible a la visión y ha construido su forma iluminada en el plano mental. Más adelante, los conceptos acerca del servicio y del yo, serán inadecuados y se encontrará una forma más apropiada de expresión, pero por el momento, ésta es suficiente.</p>

Esta forma mental, creada por el aspirante, es llevada a la existencia por las energías enfocadas del alma y las fuerzas reorientadas de la personalidad. Esto abarca tres etapas:

1. El período en que el aspirante lucha para lograr esa quietud interna y atención dirigida, que le permitirá oír la Voz del Silencio. Esa voz le expresará, a través de símbolos y la interpretación correcta de las experiencias de la vida, los propósitos y planes con los cuales puede cooperar. De acuerdo a su etapa de desarrollo estos planes pueden expresar:
   1. Los planes ya materializados que adquieren forma grupal en el plano físico, con los cuales podrá cooperar, sumergiendo en ellos su propio interés.
   2. El plan o fracción de un plan, que es privilegio del individuo manifestar y materializar como actividad grupal en el plano físico. La función de algunos aspirantes es ayudar a esos grupos que están en actividad operante. La función de otros es iniciar esas formas de actividad que están todavía en el plano subjetivo. Sólo los aspirantes libres de ambición <Pin lang="en">95</Pin> personal podrán cooperar verdaderamente en este segundo aspecto del trabajo. Por lo tanto, "Matad la ambición".
2. El período en el que se habitúa a oír con claridad e interpretar correctamente la voz interna del alma y a reflexionar sobre el mensaje impartido. Durante este período "la energía circula". Se establece una constante respuesta rítmica con la energía mental del alma y, hablando figuradamente, hay un constante fluir de fuerza entre ese centro de energía que llamamos el alma en su propio plano, y ese centro de fuerza que es un ser humano. La energía fluye a través del "hilo" denominado sutratma, y establece una respuesta vibratoria entre el cerebro y el alma.

Aquí podría dar una interesante información, pues me propongo en estas instrucciones vincular las analogías que existen entre los diferentes aspectos de la divinidad, tal como se expresan en el hombre o en el macrocosmos, el Hombre celestial.

La antigua yoga de la época atlante (que ha llegado hasta <Pin lang="es">80</Pin> nosotros en la enseñanza necesariamente fragmentada de la yoga de los centros) nos informa que el reflejo del sutratma, en el organismo humano, se denomina la médula espinal, expresándose en tres canales de nervios, a los cuales se los denomina ida, pingala y, al canal central, sushuma. Cuando las fuerzas negativas y positivas del cuerpo, que se expresan por medio de los nervios ida y pingala, están equilibradas, las fuerzas pueden ascender y descender por el canal central al cerebro, y desde éste, pasando sin impedimento alguno, a través de los centros de la columna vertebral. Cuando esto sucede tenemos la perfecta expresión del alma en el hombre físico.

En realidad constituye la analogía del sutratma, cuando vincula al hombre físico con el alma, porque el sutratma a su vez expresa la energía positiva del espíritu, la energía negativa de la materia y la equilibrada energía <Pin lang="en">96</Pin> del alma, pues el objetivo actual de la humanidad es lograr el equilibrio. Durante el período de las iniciaciones posteriores, el empleo positivo de la energía espiritual reemplaza al empleo equilibrado de la fuerza del alma, pero de esta etapa posterior el aspirante no debe aún preocuparse. Que trate de descubrir el "noble sendero medio" entre los pares de opuestos, e incidentalmente descubrirá que las fuerzas que él usa en el plano físico, utilizarán el canal central nervioso de la columna vertebral. Esto ocurrirá cuando la transmisión de la luz y la verdad al cerebro físico, por intermedio del canal central del sutratma vinculador, llegue a ser de utilidad satisfactoria. Estos conceptos e ideas (hablando en símbolos) que vienen por el canal sutrátmico negativo, son bien intencionados, pero carecen de fuerza y quedan en la nada. Están matizados por la emoción y desprovistos de la forma organizada que la mente pura puede proporcionar. Los que llegan por el canal opuesto (hablando en sentido figurado) producen una concreción demasiado rápida y están motivados por la ambición personal de una mentalidad rectora. La mente es siempre egoísta, auto afirmativa y expresa la ambición personal, que lleva dentro de sí el germen de su propia destrucción.

Sin embargo, cuando se utiliza el sutrátmico sushuma, el canal nervioso central y su energía, el alma, como creador inteligente y magnético, trasmite sus energías. Entonces los planes pueden madurar según el propósito divino y seguir con sus actividades constructivas "en la luz". El punto de contacto egoico y lunar emite siempre un punto de luz, como ya hemos visto en las Reglas para la Magia, tiene su enfoque en un punto del sutratma que es la analogía de la luz en la cabeza del aspirante.

3. El período en que entona la Palabra Sagrada y - fusionándola con la voz del ego o alma - pone en movimiento <Pin lang="es">81</Pin> materia mental para la construcción de su forma mental. El hombre en el plano físico es el que entona ahora la Palabra, y lo hace en cuatro formas: <Pin lang="en">97</Pin>
   1. Se convierte en la Palabra encarnada, y trata de "ser lo que es".
   2. Entona la Palabra dentro de sí mismo tratando de hacerlo como alma. Se visualiza como el alma que exhala energía mediante esa Palabra, a través de todo el sistema que su alma anima - sus instrumentos mental, emocional, vital y físico.
   3. Entona la Palabra, literalmente hablando, en el plano físico, afectando así los tres grados de materia en su medio ambiente. Durante todo ese tiempo "se ocupa de mantener la mente firme en la luz", y sostener inamovible la conciencia en el reino del alma.
   4. Además lleva adelante (y esta es la etapa más difícil) una actividad paralela, de constante visualización de la forma mental, por medio de la cual espera expresar ese aspecto del plan con el que ha hecho contacto, y tiene la esperanza de llevarlo a la actividad por medio de su propia vida y en su propio medio ambiente.

Esto sólo es posible cuando se ha establecido una firme relación entre el alma y el cerebro. El proceso implica la capacidad del cerebro para registrar lo que el alma percibe, de lo cual es consciente en el reino del alma. Implica también una actividad paralela llevada a cabo en la mente, porque el aspirante tiene que interpretar la visión y utilizar la facultad concreta inteligente para la sabia adaptación del tiempo y de la forma, a la justa expresión de lo aprendido. Esto no es algo fácil de hacer, pero el aspirante debe aprender oportunamente a expresarse con plena conciencia, en diferentes maneras y en forma simultánea. Así comienza a aprender a realizar una triple actividad. Esto lo expresa El Antiguo Comentario, de la manera siguiente:

> <Pin lang="en">98</Pin> El Orbe solar resplandece con radiante esplendor. La mente iluminada refleja la gloria solar. El orbe lunar se eleva desde el centro hasta la cima y se transforma en radiante sol de luz. Cuando estos tres soles son uno, aparece Brahma. Nace un mundo iluminado

Esto literalmente significa que cuando el alma (simbolizada como el Orbe solar), la mente y la luz en la cabeza, forman una unidad, el poder creador del Ángel solar puede expresarse en los tres mundos y construir una forma por la cual su energía se manifieste activamente. El orbe lunar es una forma <Pin lang="es">82</Pin> simbólica de expresar el plexo solar, el cual oportunamente debe realizar dos cosas:

1. Mezclar y fusionar las energías de los dos centros inferiores de fuerza.
2. Elevar estas energías fusionadas y así, mezclándose con las energías de otros centros superiores, llegar a la cabeza.

Lo antedicho encierra una enseñanza y una teoría. Y debe ser elaborado por el experimento práctico, la experiencia y la actividad consciente del aspirante.

También quisiera señalar la naturaleza del servicio que la humanidad como un todo, está prestando en el plan general de evolución. La regla en consideración no se aplica sólo al hombre individual, sino a la actividad predestinada del cuarto reino de la naturaleza. Por medio de la meditación, la disciplina y el servicio, el hombre convierte en una luz radiante - que ilumina los tres mundos - ese punto de luz parpadeante que vino al ser en el momento de su individualización, en épocas pasadas. Tiene su reflejo en la luz de la cabeza. Así se establece esa relación que permite, no sólo la sincronización vibratoria, sino también la irradiación y el despliegue de fuerza magnética, y también su reconocimiento en los tres mundos del medio ambiente inmediato del hombre.

Lo mismo sucede con el reino humano. A medida que acrecienta su iluminación, y su luz se hace más potente, su efecto en los <Pin lang="en">99</Pin> reinos subhumanos es análogo al del alma individual - su reflejo - en el hombre en encarnación física. Digo que es análogo a una fuerza causativa, aunque no una analogía en sus efectos. Observen esta diferencia. La humanidad es macrocósmica en relación con los estados subhumanos de conciencia, y esto lo ha señalado muy bien H.P.B. El efecto producido sobre estos estados inferiores y materiales, es principalmente cuádruple.

1. La estimulación del aspecto espiritual que se expresa como alma en todas las formas, tales como la de un mineral, una flor o un animal. El aspecto positivo de la energía en todas estas formas se hará más fuerte, produciendo por ejemplo, acrecentada irradiación en el reino mineral. He aquí un indicio de la naturaleza del proceso que pondrá término a nuestra propia existencia planetaria y, finalmente, a nuestro sistema solar. En el reino vegetal traerá una acrecentada belleza y diversidad, y la evolución de nuevas especies con una finalidad inexplicable para quienes aún no son iniciados. Uno de los resultados será la <Pin lang="es">83</Pin> producción de formas nutritivas que servirán a las necesidades de los ángeles y devas menores.

 En el reino animal su efecto será la eliminación del dolor y el sufrimiento, y un retorno a las condiciones ideales del Jardín del Edén. Cuando el hombre actúa como alma, cura, estimula y vitaliza; transmite las fuerzas espirituales del universo, y todas las emanaciones nocivas y las fuerzas destructoras encuentran una barrera en el reino humano. El mal y sus efectos dependen mayormente de la humanidad como canal activo. La función de la humanidad consiste en transmitir y manejar fuerza. Esto, en las etapas primitivas e ignorantes, se efectúa en forma destructiva y con resultados perjudiciales. Después, cuando actúa bajo la influencia del alma, la fuerza es manejada correcta e inteligentemente con resultados benéficos. Es muy cierta que: "Toda la creación gime a una, y está en dolores de parto hasta ahora, aguardando la manifestación de los hijos de Dios". <Pin lang="en">100</Pin>

2. La introducción de la luz. La humanidad es el planetario portador de luz, trasmitiendo la luz del conocimiento, de la sabiduría y de la comprensión, en sentido esotérico. Estos tres aspectos de la luz llevan los tres aspectos de la energía del alma, al alma de todas las formas, mediante el ánima mundi, el alma del mundo. Físicamente hablando, podemos comprenderlo si apreciamos la diferencia entre nuestra iluminación planetaria actual y la de hace quinientos años - las ciudades y los distritos rurales intensamente iluminados que brillan en la noche con sus calles y hogares alumbrados; los aeródromos con sus reflectores y relucientes luces; los océanos salpicados de barcos iluminados, y los aviones resplandecientes de luz atravesando los cielos.

 Esto es sólo el resultado de la creciente iluminación del hombre. Su conocimiento de la luz lo ha traído a la existencia. ¿Quién puede predecir qué acontecerá cuando predomine el aspecto sabiduría? Cuando el conocimiento y la sabiduría estén fusionados por la comprensión, el alma controlará los tres mundos y todos los reinos de la naturaleza.

3. La transmisión de la energía. La clave de la significación de esto puede ser captada como un concepto, aunque todavía no será comprendida si se reconoce que el reino humano actúa sobre los tres reinos subhumanos y los afecta. El triángulo espiritual descendente y el triángulo material ascendente, unen sus vórtices en la humanidad cuando ha encontrado el punto de equilibrio. En la realización y espiritualización del hombre reside la esperanza del mundo. El género humano es el Salvador mundial, del cual todos los Salvadores mundiales han sido símbolo y garantía. <Pin lang="es">84</Pin>
4. La unión de la evolución dévica o angélica con la humana. Éste es un misterio que se solucionará a medida que el hombre adquiera la conciencia de su propio Ángel solar, sólo para descubrir que ella no es más que otra forma de vida que, <Pin lang="en">101</Pin> habiendo servido su propósito, debe ser dejada atrás. La evolución angélica o dévica, es una de las grandes líneas de fuerza contenidas en la expresión divina y en los Ángeles solares; los Agnishvattas de La Doctrina Secreta y de Tratado sobre Fuego Cósmico - en su aspecto forma - pertenecen a esa línea.

Así sirve la humanidad, y en el desarrollo de una aptitud consciente de servicio, en el acrecentamiento de una comprensión consciente de la parte individual que debe desempeñar en el desarrollo del plan y en el sometimiento de la personalidad al alma, se logrará el constante progreso de la humanidad hacia su meta de servicio mundial.

¿Podría decir algo aquí para que esta consumación llegue a ser una meta práctica en sus vidas? Las condiciones magnéticas perjudiciales, resultado del incorrecto manejo de la fuerza por el hombre, son las causas del mal que existe en el mundo circundante, incluyendo los tres reinos subhumanos. ¿Cómo podríamos cambiar esto individualmente? Por el desarrollo de nuestra propia Inofensividad. Por lo tanto, analícense a sí mismos desde este ángulo. Estudien su conducta diaria, sus palabras y pensamientos, hasta lograr ser completamente inofensivos. Oblíguense a pensar sobre esas ideas, respecto a ustedes y los demás, para que sean constructivas y positivas, y por lo tanto de efectos inofensivos. Examinen el efecto emocional que ustedes producen sobre otros, de manera que ningún estado de ánimo, depresión ni reacción emocional, puedan dañar al semejante. Recuerden en conexión con esto que la violenta aspiración espiritual y el entusiasmo mal aplicado o mal orientado, pueden fácilmente herir a un semejante; por lo tanto cuiden sus tendencias erróneas y no sólo sus virtudes.

Si la inofensividad es la nota clave de su vida, podrán producir más condiciones armónicas en la personalidad, que cualquier disciplina en otras líneas. La depuración drástica obtenida al alcanzar la inofensividad ayudará mucho a eliminar <Pin lang="en">102</Pin> estados erróneos de conciencia. Reflexionen sobre esto e introduzcan dicha idea en la recapitulación vespertina.

Quisiera urgir a quienes leen estas páginas a hacer un nuevo comienzo en el vivir espiritual. Les diría, olviden todo lo realizado en el pasado, tengan fervor y concéntrense en el Plan.

Ya habrán hecho algún progreso en la comprensión grupal, y se interesarán menos por el yo separado. Sin duda <Pin lang="es">85</Pin> adquirieron más fe en la Buena Ley que guía a toda la creación hacia la perfección final que ya habrán visualizado y, por medio de esta visión, pudieron apartar los ojos de los asuntos de la experiencia individual, dirigiéndolos al desarrollo del propósito para la totalidad. Tal es el objetivo y la meta. Amplitud de visión, comprensión incluyente y un horizonte más amplio, son los preliminares esenciales de todo trabajo que está bajo la guía de la Jerarquía de adeptos; la estabilización de la conciencia en la vida una y el reconocimiento de la unidad básica de toda la creación, tendrán que desarrollarse parcialmente antes de poder confiar a nadie ciertos conocimientos y Palabras de Poder, y el manejo de esas fuerzas que traen la realidad subjetiva a la manifestación externa.

En esta oportunidad les digo que yo - discípulo de más edad y quizás con mayor experiencia y trabajador en la gran viña del Señor - practico la inofensividad con celo y comprensión, porque (si realmente es practicada) destruye toda limitación. La ofensividad está basada en el egoísmo y en una actitud egocéntrica. Es la demostración de fuerzas concentradas en la auto imposición, el auto engrandecimiento y la autosatisfacción. Inofensividad es la expresión de la vida del hombre que se da cuenta que está en todas partes y vive conscientemente como alma, cuya naturaleza es amor y cuyo método es inclusividad, para quien todas las formas son iguales en el sentido de que velan y ocultan la luz y las simples exteriorizaciones del <Pin lang="en">103</Pin> Único Ser Infinito. Quisiera recordarles que este logro se demostrará verdaderamente como comprensión de la necesidad del hermano, sin ningún sentimiento y conveniencia. Conducirá a ese silencio que se produce al referirse al yo separado. Producirá respuesta instantánea a la verdadera necesidad, característica de los Grandes Seres, que (al ir más allá de la apariencia externa) perciben la causa interna que produce las condiciones observadas en la vida externa y, desde ese punto de sabiduría, puede darse verdadera ayuda y guía. La inofensividad produce en la vida, cautela en el juicio, reticencia al hablar, habilidad para abstenerse de toda acción impulsiva, y demuestra un espíritu exento de crítica. De esta manera las fuerzas del verdadero amor y también esas energías espirituales que parecen vitalizar la personalidad, pasarán libremente y en consecuencia conducirán a la correcta acción.

Que la inofensividad sea, por lo tanto, la nota clave de su vida. En estas líneas debe efectuarse la recapitulación vespertina, clasificar el trabajo de recapitulación en tres partes, considerando: <Pin lang="es">86</Pin>

1. El pensar inofensivo. Dará por resultado especialmente el control de la palabra.
2. La reacción emocional inofensiva. Traerá como resultado un canal para el aspecto amor del alma.
3. La acción inofensiva. Producirá equilibrio, capacidad en la acción y liberación de la voluntad creadora.

Estos tres acercamientos al tema deben ser estudiados a través del efecto que producen sobre nuestro propio yo y desarrollo y en aquellos con quienes nos ponemos en contacto y los asociados en nuestro medio ambiente.

Quisiera intercalar aquí la observación de que hago sugerencias basadas en las experiencias del trabajo esotérico. No es obligatorio obedecer. Tratamos de entrenar a servidores inteligentes de la raza, que se desarrollan mediante el esfuerzo <Pin lang="en">104</Pin> autoiniciado, la libertad de acción y el discernimiento en el método, y no por ciega obediencia, pasividad negativa y adhesión incondicional. Recuérdenlo. Si alguna vez el mandato surgido del grupo subjetivo de instructores, del cual soy un humilde miembro, imparte una orden que sea para seguir los dictados de la propia alma y las inspiraciones del yo superior.
