---
title: Principios y Personalidades
---

# Principios y Personalidades

> [Tratado sobre magia blanca](/tratado-sobre-magia-blanca/regla-3#principios-y-personalidades)

Ahora bien, existe un punto que merece ser considerado y puede encararse con un interrogante. El estudiante podría muy bien investigar la cuestión de la manera siguiente:

Algunas personas encaran el problema del Ser por la apreciación mental y otros por la comprensión del corazón; algunos están motivados por la cabeza y otros por el corazón; hay quienes hacen cosas o evitan hacerlas, no porque las sienten sino porque las saben, reaccionando a su medio ambiente en forma mental, en lugar de hacerlo emocionalmente.

Hay que buscar iluminación para saber si para algunos el sendero consiste en no prestar servicio, porque más bien conocen que aman a Dios, que después de todo no es más que su propio yo interno. <Pin lang="en">110</Pin> ¿No es éste el sendero del ocultista y del sabio más bien que el del místico y del santo? Después de lo dicho y hecho, ¿no es principalmente cuestión de saber el rayo a que uno pertenece y bajo qué Maestro se recibe el aprendizaje? ¿No es el verdadero conocimiento una especie de amor intelectual? Si un poeta puede escribir una oda a la belleza intelectual, ¿por qué no podemos expresar nuestro aprecio por una entidad concebida por la cabeza más que por el corazón. El corazón tiene su valor, pero no es adecuado para la rudeza del mundo.

¿Qué otra cosa puede hacerse sino aceptar las actuales limitaciones mientras se buscan las cosas trascendentales que le corresponde, según la Ley Divina de evolución? ¿No existe acaso aquello que (comparativamente) es como un complejo espiritual de inferioridad, de parte de quienes son sensibles (y quizás super sensibles), al hecho de que, si bien sus vidas están intelectualmente colmadas de interés, el desierto de sus corazones no han llegado a florecer como la rosa?

"En otras palabras, siempre que uno acuda a servir en el lugar designado, aceptando la Hermandad en Presencia de la Paternidad, ¿qué importa que el postulado fundamental sea para él una cosa de la cabeza, en vez de serlo del corazón?"

<p><Pin lang="es">91</Pin> Responderé a estas preguntas de la manera siguiente:</p>

No es cuestión de rayo ni de una diferencia básica entre el ocultista y el místico. En el individuo íntegro deben actuar con igual poder la cabeza y el corazón. No obstante, en tiempo y espacio y durante el proceso de evolución, los individuos se caracterizan por la tendencia que predomina en cualquier vida; hacemos estas diferencias transitorias porque no percibimos el conjunto. En determinada vida el hombre puede ser predominantemente mental, pues para él, el sendero del Amor de Dios no sería apropiado. El Amor de Dios afluye a su corazón y en considerable medida su acercamiento esotérico se basa en la percepción mística de sus vidas anteriores. Su problema es conocer a Dios, con la finalidad de interpretar ese conocimiento como amor a todo. Por lo tanto, <Pin lang="en">111</Pin> el amor responsable, expresado como deber hacia el grupo y la familia, es para él la línea de menor resistencia. El amor universal irradiado a toda la naturaleza y a todas las formas de vida, vendrá después de un mayor conocimiento de Dios, y será parte de su desarrollo en otra vida.

Quienes estudian la naturaleza humana (y esto deberían hacerlo todos los aspirantes) harían bien en tener presente que existen diferencias transitorias. Las personas difieren en:

1. El rayo (que afecta predominantemente al magnetismo de la vida).
2. El acercamiento a la verdad, teniendo mayor poder de atracción el sendero ocultista o el místico.
3. La polarización, que decide la intención emocional, mental o física, de una vida.
4. La etapa de evolución, que produce las diferencias observadas entre los hombres.
5. El signo astrológico, que determina la tendencia de determinada vida.
6. La raza, que pone a la personalidad bajo la peculiar forma mental racial.

El subrayo al que pertenece el hombre, ese rayo menor que varía de una encarnación a otra, colora mayormente su vida. Es su matiz secundario. Recuerden que el rayo primario de la mónada continúa durante el eón. No varía. Es uno de los tres rayos primarios que oportunamente los hijos de los hombres sintetizarán. El rayo egoico varía de ronda en ronda, y en las almas más evolucionadas de raza en raza, y comprende uno de los cinco rayos de nuestra actual evolución. Es el rayo predominante por el cual vibra el cuerpo causal del hombre. Puede corresponder al rayo de la mónada, o ser uno de los colores complementarios del primario. El rayo de la personalidad varía <Pin lang="en">112</Pin> vida tras vida, hasta <Pin lang="es">92</Pin> haber pasado por toda la gama de los siete subrayos del rayo monádico.

Por consiguiente, al tratar con personas cuyas mónadas están en un rayo similar o complementario, se hallará que se aproximan por simpatía. Sin embargo, conviene recordar que la evolución debe ser muy avanzada para que el rayo de la mónada influya ampliamente. De este modo la mayoría de los casos no pertenecen a esa categoría.

Referente al hombre común evolucionado, que lucha por aproximarse al ideal, la similitud del rayo egoico producirá una mutua comprensión, que lo llevará a la amistad. Es fácil para dos personas del mismo rayo egoico comprender sus puntos de vista y llegar a ser grandes amigos, con una mutua fe inquebrantable, pues cada uno reconoce en el otro el mismo modo de actuar.

Pero cuando (agregado a la similitud egoica de rayo) la personalidad pertenece al mismo rayo, entonces tenemos una de esas cosas poco frecuentes, una perfecta amistad, un casamiento feliz, un vínculo inquebrantable entre dos. Esto, en realidad, es sumamente raro.

Cuando se trata de dos personas cuya personalidad pertenece al mismo rayo, y a distinto rayo egoico, puede existir una de esas amistades y afinidades breves y repentinas, pero tan efímeras como una mariposa. Es menester tenerlo presente, pues reconociéndolo se obtiene la capacidad de adaptación. La claridad de visión da por resultado una actitud prudente.

Otra causa de disidencias puede deberse a la polarización de los cuerpos. A no ser que esto sea reconocido, al tratarse las personas, se producirá incomprensión. El empleo de los términos, "un hombre polarizado en su cuerpo astral", en realidad, significa el hombre cuyo ego actúa principalmente a través de dicho vehículo. La polaridad indica la claridad del canal. Permítaseme ilustrarlo. El ego del hombre <Pin lang="en">113</Pin> común tiene su morada en el tercer subplano del plano mental. Cuando el hombre posee un vehículo astral compuesto en su mayor parte de materia del tercer subplano astral, y el mental se encuentra mayormente en el quinto subplano, el ego centrará sus esfuerzos en el cuerpo astral. Si tiene un cuerpo mental de materia del cuarto subplano y un cuerpo astral del quinto subplano, la polarización será mental.

Cuando se habla que el ego controla más o menos al hombre, en realidad se quiere decir que ha incorporado en sus cuerpos materia de los subplanos superiores.

El ego controla con interés sólo cuando el hombre ha eliminado de sus vehículos casi toda la materia del séptimo, sexto y quinto subplanos. Cuando ha incorporado cierta cantidad de <Pin lang="es">93</Pin> materia del cuarto subplano, el ego amplía su control; cuando existe cierta cantidad del tercer subplano, entonces el hombre está en el sendero; cuando predomina materia del segundo subplano entonces recibe la iniciación, y cuando tiene solamente materia de sustancia atómica se convierte en Maestro. Por lo tanto, el subplano en el que se encuentra el hombre es importante, y el reconocimiento de su polarización dilucida la vida.

La tercera cosa a recordarse es que aunque se aceptan ambos puntos, la edad y la experiencia del alma con frecuencia originan incomprensión. Los dos puntos anteriores no nos llevan muy lejos, porque la capacidad de percibir el rayo del hombre no es aún para esta raza. Una aproximada suposición y el uso de la intuición, es todo lo que se puede hacer. Los pocos evolucionados no pueden comprender perfectamente a los muy evolucionados, y en menor grado el alma avanzada no comprende al iniciado. Lo mayor puede comprender lo menor, pero no lo contrario.

Respecto a la actividad de aquellos cuyo punto de realización trasciende el propio, sólo les pediré hacer tres cosas: <Pin lang="en">114</Pin>

1. No juzgar. Ellos tienen mayor visión. Recuerden que una de las mayores cualidades que han alcanzado los miembros de la Logia es su habilidad para considerar la destrucción de la forma como algo sin importancia. Les preocupa la vida en evolución.
2. Comprender que todos los acontecimientos son producidos por los Hermanos, teniendo en vista un sabio propósito. Los iniciados de grado inferior, aunque agentes absolutamente libres, encuadran en los planes de sus superiores, del mismo modo que lo hacen ustedes en escala menor. Tienen lecciones que aprender, y la regla del aprendizaje dice que la experiencia debe ser pagada. La captación viene a través del castigo que sigue a la acción irrazonable. Sus superiores permanecen preparados para sacar provecho de las situaciones producidas por los errores de quienes están en una etapa inferior de desarrollo.
3. Tener presente que la Ley de Renacimiento oculta en sí el secreto de la crisis actual. Los egos se reúnen en grupos para agotar cierto karma acumulado en el pasado, en el cual pecaron lastimosamente los hombres. El castigo y la transmutación son consecuencias naturales. La violencia y la crueldad anteriores traerán un pesado karma, pero ustedes tienen en sus manos la trasmutación de los antiguos errores.

Recuerden además que los principios son eternos y las personalidades transitorias. Los principios se verán a la luz de la eternidad, las personalidades desde el punto de vista del tiempo. <Pin lang="es">94</Pin> Lo malo es que, en muchas situaciones, están involucrados dos principios, uno de ellos secundario. La dificultad estriba en que (siendo ambos principios) los dos son correctos. Una buena regla para una guía segura, consiste en recordar siempre que generalmente los principios básicos (para una sabia comprensión y desarrollo fructífero) exigen el empleo de la intuición, mientras que los secundarios son más puramente mentales. Por eso los métodos difieren necesariamente. Al aferrarse a los principios básicos, los métodos más inteligentes son <Pin lang="en">115</Pin> el silencio y una alegre confianza en que la Ley actúa, evitando todas las insinuaciones personales, excepto los comentarios inteligentes y amorosos, tratando de ver todo a la luz de la eternidad y no del tiempo, conjuntamente con un constante afán de seguir la ley del amor y sólo ver lo divino en el hermano, aunque tenga ideas contrarias.

En los principios secundarios, que las fuerzas opuestas destacan en la actualidad, la utilización de la mente inferior encierra el peligro de crítica y el empleo de métodos sancionados por el tiempo en los tres mundos - métodos que involucran el ataque personal, la injuria y la pérdida de energía en cosas destructivas, además de un espíritu contrario a la ley del plano, de la unidad. El término "fuerzas opuestas", se emplea correctamente cuando se usa sólo en un sentido científico, y significa el polo opuesto que conduce al equilibrio. Por lo tanto, recuerden que aunque los grupos opuestos sean completamente sinceros, puede actuar en ellos la mente concreta como barrera para la libre acción de la visión superior. Su sinceridad es grande, pero su etapa de realización, en algunas líneas, es menor que la de aquellos que se adhieren a los principios básicos, vistos a la luz de la intuición.

Principio es aquello que encarna algún aspecto de la verdad en que está basado nuestro sistema; es la infiltración, en la conciencia del hombre, de una pequeña parte de la idea sobre la que nuestro Logos fundamenta todo lo que hace. La base de toda acción logoica es amor en actividad, y la idea fundamental sobre la cual Él basa la acción, conectada con la Jerarquía humana, es el poder del amor que impele hacia delante - llámese evolución, si desean, o impulso inherente, si prefieren, pero es amor que causa movimiento e impulsa a la consumación. Es el impulso impelente de uno y todos hacia una mayor expresión. De allí que este principio debería ser la base de toda actividad, y si la dirección de las organizaciones menores estuviera fundada sobre el amor que conduce a la actividad, crearía en todos sus miembros una urgencia divina, que análogamente los impelerá a una expresión más plena, a una <Pin lang="en">116</Pin> plenitud más adecuada y a un mayor y satisfactorio esfuerzo.

<p><Pin lang="es">95</Pin> Cuando un principio es verdaderamente fundamental, atrae inmediatamente a la intuición y demanda una inmediata reacción de asentimiento del yo superior del hombre. Para la personalidad tiene poca o ninguna atracción. Encierra un concepto del ego en su relación con los demás egos. Un principio es lo que rige siempre la acción del ego en su propio plano; sólo cuando entramos bajo la acrecentada guía de ese ego, nuestra personalidad concibe y responde a estas ideas. Éste es un punto que debe tenerse muy en cuenta en el trato con los demás, lo cual modificará nuestros juicios. La comprensión de un principio marca exactamente una etapa en la evolución.</p>

Un principio es aquello que da vida a la afirmación de que el mayor bien es para el mayor número. Que un hombre debe amar a su esposa es la afirmación de un principio que rige a la personalidad, pero más tarde debe ser trasmutado en un principio más grande, el de que el hombre debe amar a sus semejantes. Los principios son de tres tipos, y para llegar a los superiores se debe pasar por los inferiores:

1. Los principios que rigen al yo personal inferior, y tratan de las acciones o vida activa de ese yo inferior. Encarnan el tercer aspecto, el de la actividad de la manifestación logoica, siendo la base del progreso posterior. Controlan al hombre durante su etapa poco evolucionada y el período de irreflexividad; se comprendería con mayor facilidad si dijera que están incorporados en las comunes y aceptadas reglas para vivir decentemente. No matarás, no hurtarás, tienen mucho que ver con la vida activa del hombre y con la formación de su carácter.
2. Los principios que rigen al yo superior y tratan del aspecto amor o sabiduría. Éstos nos conciernen ahora, y la mitad de las dificultades <Pin lang="en">117</Pin> del mundo surgen en la actualidad porque estos principios más elevados, teniendo que ver con el amor o la sabiduría en toda su plenitud, recién están empezando a ser comprendidos por el vulgo. Debido al rápido reconocimiento de su veracidad y de la tentativa de convertirlos en hechos, sin haber realizado un previo reajuste del medio ambiente a esos ideales, provienen los frecuentes choques y luchas entre los que están condicionados por principios que rigen a la personalidad y quienes lo están por los que gobiernan al yo superior. Hasta que un mayor porcentaje de la raza no se rija por la conciencia del alma, esta lucha será inminente e inevitable. Cuando el plano emocional esté dominado por el intuicional, sobrevendrá entonces la comprensión universal.

 <p><Pin lang="es">96</Pin> El hombre aprende la primera serie de principios por medio de la codicia y el consiguiente desastre que ella produce. Robó, sufrió el castigo, y dejó de robar. El principio se forjó en él mediante el dolor y aprendió que sólo podía gozar de lo que era suyo por derecho y no por posesión. El mundo va ahora aprendiendo esta lección en forma grupal, porque a medida que los rebeldes se apoderan y retienen ilegalmente lo robado, encuentran que no les es suficiente y que les trae sufrimiento. Así, con el tiempo, van aprendiendo los principios.</p>

 La segunda serie de principios se aprende mediante la renunciación y el servicio. El hombre se aparta (después de aprender los primeros principios) de las cosas de la personalidad, y por medio del servicio aprende el poder del amor en su significado oculto. Da, y por lo tanto recibe; vive la vida de renunciación, y las riquezas del cielo afluyen a él; da lo que posee, y a su vez es colmado hasta la saciedad; nada pide para sí, y es el hombre más rico de la tierra.

 Los primeros principios se relacionan con la unidad diferenciada y con la evolución a través de la heterogeneidad. Los principios que aprende actualmente la raza tienen que ver con los grupos; el <Pin lang="en">118</Pin> interrogante no es "¿Qué será lo mejor para el hombre?" sino "¿Qué será lo mejor para los muchos?", y sólo a quienes les es posible pensar en la totalidad y visualizarla como una unidad, pueden enunciar estos principios satisfactoriamente. Son los más importantes, pues constituyen los principios básicos de este sistema de amor. La dificultad actual se debe a que los hombres están confundidos. Algunos de los primeros principios y fundamentos de la actividad inferior son innatos y están actualmente muy arraigados, sólo unos pocos de los principios egoicos superiores o del amor, se están infiltrando en sus confusos cerebros, originando un aparente y momentáneo choque de ideas. Se preguntan como Pilatos: "¿Cuál es la verdad?". Si recordaran solamente que los principios superiores conciernen al bien del grupo y los inferiores al bien del individuo, tal vez surgiría la claridad. La actividad inferior de la vida personal, por buena o digna que sea, a la larga tendrá que ser trascendida por la vida superior del amor que busca el bien del grupo y no el del ente.

 Todo lo que tiende a la síntesis y a la expresión divina en el conjunto de unidades, se aproxima más al ideal y se acerca a los principios superiores. Si se piensa profundamente sobre estas ideas puede llegar alguna ayuda. Un ejemplo de lo que se dijo lo tienen en el hecho de que muchas de las luchas que surgen dentro de las organizaciones se basan en que algunas personas dignas siguen a determinadas personalidades, sacrificándose por un principio; sí, efectivamente, pero un principio que rige la <Pin lang="es">97</Pin> vida de la personalidad. Otros, vislumbrando vagamente algo superior y buscando el bien de los grupos y no el de una persona, tropiezan con un principio superior y al hacerlo introducen, la fuerza del ego. Trabajan para otros con el objeto de ayudar a su grupo. Cuando existen roces entre los egos y las personalidades, la victoria de lo superior es segura; el principio inferior debe ceder su lugar al superior. Uno se concentra en lo que le parece de supremo valor, el cumplimiento del deseo de la vida personal, y (en este período) está <Pin lang="en">119</Pin> interesado sólo en forma secundaria por el bien de la mayoría, aunque podrá tener momentos en los que piensa que ésa es su intención principal. A otro no le importa nada de lo que le acontece al yo personal y sólo le interesa ayudar a la mayoría. Utilizando una expresión apropiada, todo se reduce a un móvil egoísta o altruista y, como bien lo saben, los móviles varían a medida que pasa el tiempo y el hombre se aproxima a la meta del sendero de probación.

3. Los principios más elevados son los que capta el espíritu, y sólo son comprendidos fácilmente por la conciencia monádica. Únicamente a medida que el hombre trasciende su vida activa personal y sustituye la vida de amor o sabiduría, de acuerdo a como el ego la guía, puede empezar a comprender el alcance de esa vida de amor y conocerla como poder manifestado. Así como la personalidad trata de los principios que rigen la vida activa del yo inferior, y el ego actúa con la ley del amor, manifestada en el trabajo grupal o demostrada en la síntesis de los muchos en los pocos, así la mónada se ocupa de la vida activa del amor que se expresa en poder, por la síntesis de los pocos en uno solo.

El primero se ocupa de la vida del hombre en el plano físico en los tres mundos; el segundo, de su vida en niveles causales, y el último, de su vida después de haber alcanzado la meta del esfuerzo humano actual. Uno trata con entes, otro con grupos y el último con la unidad. Uno se ocupa de la diferenciación en sus formas más diversas; el segundo, de los muchos trasformados en grupos egoicos, mientras que el tercero percibe la diferenciación trasformada nuevamente en los siete, que señala la unidad de la jerarquía humana.

Todos estos factores y muchos otros producen diferencias entre los seres humanos, y al valorarse a sí mismo, el hombre debe tenerlos en consideración.

Por consiguiente, debe recordarse que un discípulo de cualquier Maestro tendrá su bagaje propio y sus acerbos y diferencias individuales. Sin embargo, puede <Pin lang="en">120</Pin> estar seguro que hasta no haber incorporado al sendero del Conocimiento el sendero del Amor, <Pin lang="es">98</Pin> no podrá recibir las iniciaciones mayores, porque éstas se reciben en los niveles superiores del plano mental. Hasta que el sendero de luz no se haya unido al de la vida, no podrá efectuarse la gran transición del cuarto reino al quinto. Son posibles ciertas expansiones de conciencia; pueden pasarse iniciaciones en el plano astral y en el plano mental inferior, percibirse algo de la visión y sentir la Presencia; puede llegarse al Bien Amado por medio del amor y la beatitud, y la alegría de este contacto puede traer consigo una alegría permanente; pero esa clara percepción proveniente de la experiencia pasada en el Monte de la Iluminación, es muy distinta de la alegría experimentada en el Monte de la Bendición. En uno, el Corazón es el guía, y en otro, la Cabeza.

Para responder más categóricamente: el sendero del conocimiento es el del ocultista y del sabio; el del amor es el del místico y del santo. El acercamiento por medio de la cabeza o del corazón no depende del rayo, pues ambos caminos deben ser conocidos; el místico deberá convertirse en ocultista; el ocultista blanco ha sido el místico santificado. El verdadero conocimiento es amor inteligente, porque es la fusión del intelecto y la devoción. La unidad se siente en el corazón; su aplicación inteligente a la vida debe ser desarrollada mediante el conocimiento.

Es de gran valor reconocer la tendencia del propósito de la vida, y saber si el objetivo de una vida constituye el método de la cabeza o del corazón. Aquí se requiere, sin embargo, un sutil discernimiento espiritual, porque el espejismo de la ilusión puede tentar a seguir el sendero de la inercia. Reflexionen detenidamente sobre estas palabras y asegúrense que la cuestión tenga una base sólida y que no provenga de un complejo de inferioridad, ni de la iniciativa de un hermano y su consiguiente envidia, o de una plácida inercia que niega toda actividad.

<p><Pin lang="en">121</Pin> Como regla general para el aspirante común al discipulado, se supondrá, sin lugar a dudas, que en el pasado se aplicó muchas veces el método del corazón, y en esta encarnación el desenvolvimiento mental es de primordial importancia.</p>

Una antigua escritura dice:

> No trates, oh, dos veces bendito Uno, de alcanzar la esencia espiritual antes de que la mente absorba. No es así como se busca la sabiduría. Sólo a quien tiene la mente sujeta y percibe el mundo como un espejo, se le puede confiar plenamente los sentidos internos. Sólo a quien sabe que los cinco sentidos son una ilusión y que nada permanece, excepto los dos que están adelante, se le podrá revelar el secreto de la trasposición del Cruciforme.
>
> El sendero hollado por el servidor es el sendero de fuego que atraviesa su corazón y conduce a la cabeza. No es en el sendero del placer ni en el del dolor donde se alcanza la liberación ni se obtiene la sabiduría. Mediante la trascendencia de ambos, por la fusión del <Pin lang="es">99</Pin> dolor y el placer, se alcanza la meta, esa meta que está por delante como un punto de luz en la oscuridad de una noche de invierno. Este punto de luz puede recordarnos el pequeño candil de alguna triste buhardilla, pero - a medida que se sigue el sendero que conduce a dicha luz, mediante la fusión de los pares de opuestos - ese punto diminuto, frío y tembloroso, aumenta con firme irradiación y le recuerda al errante viajero la cálida luz de alguna ardiente lámpara.
>
> Sigue tu camino, oh Peregrino, con firme perseverancia, No existe candil ni lámpara terrenal alimentada con aceite. Acrecienta continuamente la irradiación hasta que el sendero termine en una llamarada de gloria, y el viajero de la noche se convierta en el hijo del sol y atraviese los portales de ese radiante orbe.
