---
title: El discípulo y el maestro
---

# El discípulo y el maestro

> [Tratado sobre magia blanca](/tratado-sobre-magia-blanca/regla-5#en167)

Segundo, cuando el hombre utiliza voluntariamente el instrumento subjetivo y sabe cómo utilizarlo, cuándo lo debe utilizar, y puede dejar de hacerlo y volver a emplearlo a voluntad, entonces cambia totalmente su estado y aumenta su utilidad. Por el empleo de la mente, la humanidad ha llegado a percibir los propósitos y la utilización del mecanismo físico. Ahora, mediante el empleo de una facultad más elevada, característica del alma, obtiene un control voluntario e inteligente de su instrumento, y aprende a comprender los propósitos para los cuales dicho instrumento existe. Esta facultad superior es la intuición.

Quisiera agregar en forma destacada, que únicamente cuando el hombre llega a ser intuitivo es de utilidad en el grupo de un Maestro, y recomiendo a todos los aspirantes que estudien muy detenidamente el significado y significación de la intuición. Cuando ésta comienza a actuar, entonces el discípulo puede pasar de la etapa de probación a la de aceptación, en el grupo de un Maestro.

uizás se pregunten cómo puede conocer y comprobar esto el probacionista. Al probacionista se le da mucho entrenamiento sin que conscientemente lo reconozca. Se le indican las tendencias erróneas, a medida que trata sinceramente de entrenarse para el servicio, y cuando el análisis del móvil se hace con honestidad, <Pin lang="es">129</Pin> sirve en forma asombrosa para sacar al seudo discípulo del mundo astral o emocional, y elevarlo al mundo de la mente. Es en este mundo mental donde por primera vez se hace contacto con los Maestros, y es allí donde hay que buscarlos.

Pero ha llegado el momento en que la Luz en la cabeza no sólo está presente, sino que puede ser utilizada en cierta medida. El karma del aspirante es de tal naturaleza que puede, mediante el esfuerzo esmeradamente aplicado, manejar su vida, <Pin lang="en">168</Pin> de manera que no sólo cumple con su karma, desempeñando sus obligaciones, sino que tiene la suficiente determinación para permitirle solucionar los problemas y cumplir también con las obligaciones del discipulado. Desempeña con correcto móvil su servicio en bien de los demás; comienza a ejercer y a hacer sentir su poder; pierde de vista su propio interés por el ajeno. Cuando esto sucede se producen ciertos acontecimientos esotéricos.

El Maestro consulta con algunos de Sus discípulos más avanzados, si es aconsejable admitir al aspirante dentro del aura del grupo, y mezclar su vibración con la del grupo. Si se llega a alguna decisión, en el término de dos años, un discípulo avanzado actúa entonces como intermediario entre el Maestro y el aspirante recientemente aceptado. Trabaja con el nuevo discípulo aminorando (si así puede expresarse) la vibración del Maestro para acostumbrar a los cuerpos de aquél a las aceleradas vibraciones superiores. Plasma en la mente del discípulo, por medio de su ego, los planes e ideales del grupo, y observa su reacción a los acontecimientos y oportunidades de la vida. Podría decirse que asume por el momento y en forma práctica, los deberes y la posición del Maestro.

El aspirante ignora durante todo este tiempo lo que ha sucedido, y es inconsciente de sus contactos subjetivos. Sin embargo, reconoce en sí mismo tres cosas:

Acrecentada actividad mental. Al principio esto le traerá mucha dificultad y le parecerá como si estuviera perdiendo el control de la mente en vez de adquirirlo, pero sólo es un estado transitorio, y gradualmente asumirá el mando.

Acrecentada respuesta a las ideas y creciente capacidad para visualizar el Plan de la Jerarquía. Esto, hasta cierto punto, lo convertirá en un fanático en las primeras etapas. Continuamente será arrastrado por ideales, ismos, modos de vivir y nuevos sueños, en bien del mejoramiento de la raza. Se afiliará a un culto tras otro, porque quizás ello posibilitará la llegada del milenio. Pero después <Pin lang="en">169</Pin> de un tiempo recobrará su equilibrio y el propósito asumirá el control de su vida. Trabajará en su propia ocupación, <Pin lang="es">130</Pin> y contribuirá a la actividad del todo, de acuerdo a su capacidad.

Acrecentada sensibilidad psíquica. Indica crecimiento y al mismo tiempo una prueba. Puede ser seducido por los poderes psíquicos y tentado a desviar su esfuerzo del servicio especializado a la raza, hacia la explotación de los poderes psíquicos, utilizándolos para el propio engrandecimiento. El aspirante debe progresar simultáneamente en todos los aspectos de su naturaleza, pero hasta no actuar conscientemente como alma o psiquis, y emplear la inteligencia cooperadora, los poderes inferiores deben estar pasivos, los cuales pueden ser utilizados sin peligro por los discípulos avanzados e iniciados. Son armas e instrumentos de servicio que deben ser empleados en los tres mundos por quienes aún están atados a esos mundos por la Ley de Renacimiento. Quienes han pasado por la gran Liberación y "cruzado ocultamente el puente", no necesitan emplear los poderes inherentes a los vehículos inferiores, pueden utilizar el conocimiento infalible de la intuición y la iluminación del principio Luz.

Existen falsos conceptos, en las mentes de las personas, respecto a la forma en que el Maestro permite al discípulo darse cuenta que ha sido aceptado. Se ha generalizado la idea de que se le comunica y se le acuerda una entrevista, en la cual el Maestro lo acepta y le designa un trabajo. Pero no es así. La Ley oculta rige tanto para el discipulado como para la iniciación, y el hombre progresa ciegamente. Espera pero no sabe, pero tiene la esperanza de que así sea; aunque no tiene ninguna seguri-dad tangible, llega a la conclusión, por el estudio de sí mismo y de los requisitos, que quizá ha alcanzado el estado de discípulo aceptado. Por lo tanto, actúa sobre tal suposición y vigila sus actos, cuida sus palabras y controla sus pensamientos, de modo que ninguna acción, palabra innecesaria o pensamiento <Pin lang="en">170</Pin> maléfico, rompan el ritmo que él cree haber establecido. Sigue con su trabajo, pero intensifica la meditación; investiga sus móviles; trata de equipar su cuerpo mental; coloca ante sí el ideal de servicio, procurando siempre servir; entonces (cuando está tan absorbido en el trabajo que tiene entre manos, que se ha olvidado de sí mismo) repentinamente un día ve a Aquél que durante tanto tiempo lo ha estado observando.

Esto puede acontecer en dos formas: ya sea en plena conciencia vigílica, o porque el cerebro físico registra la entrevista tal como participó en ella durante las horas de sueño.

Paralelamente al reconocimiento de este evento los discípulos llegarán a otros reconocimientos:

1. El acontecimiento se reconoce como un hecho, fuera de <Pin lang="es">131</Pin> toda controversia. Ninguna duda queda en la mente del discípulo.
2. Sabe que no debe mencionarlo. Pasarán meses o años, antes de hacerlo, y entonces lo dirá sólo a quienes son también reconocidos como discípulos o a un compañero de tarea que está bajo la misma influencia grupal, cuyo derecho es saberlo, derecho sancionado por el Maestro del grupo.
3. Ciertos factores que rigen la relación del Maestro con el discípulo son gradualmente reconocidos y empiezan a regir cada vez más la vida del discípulo:
   1. Reconoce que los puntos de contacto con su Maestro están regidos por la emergencia y la necesidad grupales, y tienen que ver con su servicio grupal. Paulatinamente se da cuenta que su Maestro podrá interesarse por él, sólo hasta donde su ego pueda ser utilizado en el servicio, por medio de la personalidad en el plano físico. Empieza a darse cuenta que Él trabaja con su alma y que ésta y no el yo personal, está en relación con el Maestro. Por lo tanto su problema, problema de todos los discípulos, se va aclarando cada vez más, el cual consiste en mantener <Pin lang="en">171</Pin> abierto el canal de comunicación entre el alma y el cerebro, mediante la mente, de modo que el Maestro pueda comunicarse inmediatamente y con facilidad. A veces tiene que esperar varias semanas antes de poder ser oído por el discípulo, porque el canal ascendente está cerrado y el alma no está en relación con el cerebro. Esto sucede especialmente en las primeras etapas del discipulado.
    
    :::note Recuerda

    Por lo tanto su problema, problema de todos los discípulos, se va aclarando cada vez más, el cual consiste en mantener <Pin lang="en">171</Pin> abierto el canal de comunicación entre el alma y el cerebro, mediante la mente, de modo que el Maestro pueda comunicarse inmediatamente y con facilidad. 

    :::
   
   2. Descubre que él mismo cierra la puerta en la mayoría de los casos, mediante el psiquismo inferior, la incapacidad física y la falta de control mental; en consecuencia halla que debe trabajar constante e incesantemente con su yo inferior.
   3. Percibe que una de las primeras cosas que debe hacer es aprender a discriminar entre:
      1. La vibración de su propia alma.
      2. La vibración del grupo de discípulos con quienes está asociado.
      3. La vibración del Maestro.
    
    Los tres son indiferentes y es fácil confundirlos especialmente al principio. La guía más segura para los aspirantes cuando hacen contacto con una vibración y estímulo superiores, consiste en suponer que quien hace contacto con ellos es su propia alma, el Maestro en el corazón, y no (algo muy halagador para orgullo de la personalidad) que el Maestro trata de llegar a ellos.

   4. Descubre además que no es costumbre de los Maestros adular o hacer promesas a sus discípulos. Están muy ocupados y son demasiado sabios; tampoco les dicen que están destinados a desempeñar <Pin lang="es">132</Pin> altos cargos, ni que son sus intermediarios y que de ellos depende la Jerarquía. La ambición, el amor al poder y la autosuficiencia, características de muchos tipos mentales, ponen a prueba al aspirante luchador, y recibe de su personalidad todo lo que necesita en ese sentido. Estas cualidades lo engañan y desvían, forzándolo <Pin lang="en">172</Pin> a situarse en un pedestal de donde finalmente tendrá que descender. Los Maestros no dicen nada que pueda nutrir el orgullo en Sus discípulos, ni pronuncian palabras que fomenten en sus chelas el espíritu de separatividad.
   5. El discípulo muy pronto se da cuenta que los Maestros no son fácilmente accesibles. Se hallan tan ocupados, que difícilmente disponen de tiempo para comunicarse con el discípulo, y únicamente una emergencia, en el caso de un principiante en el sendero del discipulado, utilizan la energía necesaria para ponerse en contacto. Con los discípulos antiguos y probados, los contactos son más frecuentes, se logran con más facilidad y tienen resultados más rápidos. Sin embargo, debe recordarse que cuanto más nuevo es el discípulo exige mayor atención y considera que debe recibirla. Los servidores antiguos y más experimentados tratan de cumplir con sus obligaciones y llevar a cabo el trabajo mediante el menor contacto posible con el Maestro. Procuran ahorrarle tiempo y, frecuentemente, consideran que una entrevista con Él es una demostración de fracaso de su parte, y por lo tanto les produce desazón ocupar el valioso tiempo del Maestro, obligándolo a emplear Su energía en proteger el trabajo de cualquier error, y al discípulo de algún daño. El objetivo de todo discípulo avanzado es desempeñar su tarea y relacionarse con el centro de fuerza espiritual, su grupo, y estar así en continuo contacto con el Maestro, sin entrevistas ni contactos fenoménicos. La mayoría sólo espera establecer contacto con Su Maestro una vez al año, generalmente en la época del plenilunio de mayo.
   6. Encuentra también que la relación entre Maestro y discípulo está regida por la ley y que existen grados y etapas definidos de contacto en la relación deseada. Éstos pueden ser enumerados, pero no dilucidados:
      1. La etapa en que el Maestro hace contacto con el discípulo por medio de otro chela en el plano físico. Ésta es la etapa de "el breve período de chela". <Pin lang="en">173</Pin>
      2. La etapa en que un discípulo más avanzado dirige al chela desde el nivel egoico. Ésta es la etapa denominada "el chela en la Luz".
      3. La etapa en que, según la necesidad, el Maestro hace contacto con el chela, mediante: <Pin lang="es">133</Pin>
         1. Una vívida experiencia en el sueño.
         2. Una enseñanza simbólica.
         3. La utilización de una forma mental del Maestro.
         4. Un contacto en la meditación.
         5. Una definida y recordada entrevista en el ashrama del Maestro. Ésta es definidamente, la etapa de discípulo aceptado. 
      4. La etapa en que habiendo demostrado su sabiduría en el trabajo y apreciado el problema del Maestro, se le enseña al discípulo cómo (en una emergencia) atraer la atención del Maestro y así extraer Su fuerza y conocimiento y recibir consejos. Esto es algo instantáneo y no le ocupa prácticamente tiempo al Maestro. Esta etapa recibe el nombre peculiar de "el chela en el Hilo o Sutratma".
      5. La etapa donde se le permite conocer el método por el cual puede originar una vibración y un llamado que le otorgará una entrevista con el Maestro. Esto únicamente se le concede a esos chelas dignos de confianza, de quienes se puede esperar la utilización del conocimiento sólo para las necesidades del trabajo; ninguna razón ni aflicción personal los impelería a utilizarlo. El chela es denominado en esta etapa "el discípulo dentro del aura".
      6. La etapa en que puede atraer la atención del Maestro en cualquier momento. Se halla siempre en estrecho contacto. En esta etapa el chela es preparado definidamente para una iniciación inmediata, o habiendo recibido ya la iniciación, se le da trabajo especializado para hacerlo en colaboración con su... Esta etapa se describe como "el discípulo dentro del corazón de Su Maestro".

<p><Pin lang="en">174</Pin> Existe una etapa posterior de identificación aún más íntima, donde se produce una mezcla de Luces, pero no hay términos adecuados para expresar el nombre. Las seis etapas mencionadas han sido parafraseadas para la comprensión occidental y en ningún sentido deben considerarse como traducción de palabras antiguas.</p>

Éstas son algunas de las enseñanzas que conciernen a los discípulos y su reconocimiento, y es de valor que los aspirantes reflexionen sobre ellas. Se ha de comprender que aunque el buen carácter, la elevada ética, la sana moral y la aspiración espiritual, son requisitos básicos inalterables, sin embargo, es necesario algo más para adquirir el derecho de entrar en el ashrama del Maestro.

Haber adquirido el privilegio de ser, una avanzada de la conciencia del Maestro, requiere altruismo y la entrega de sí mismo, <Pin lang="es">134</Pin> para lo cual pocas personas están preparadas; el hecho de ser atraído dentro de Su aura, de manera de formar parte integrante del aura grupal, presupone una pureza que pocos pueden cultivar; poder escuchar al Maestro y merecer el derecho de ponerse en contacto con Él a voluntad, requiere sensibilidad y fina discriminación, y pocos están dispuestos a pagar el precio. No obstante hay una puerta abierta de par en par para todos los que quieran llegar, y ningún alma dedicada y sincera que llene todos estos requisitos será rechazada.

No existe ninguna duda, en la actualidad, de que quienes han avanzado algo en la evolución, están acelerando esa evolución como no ha sucedido hasta ahora en la historia del mundo. La crisis es tan grave y la necesidad tan grande, que quienes están en condiciones de entrar en contacto con el aspecto interno de la vida, aunque sientan levemente las vibraciones de los discípulos más avanzados y de los Hermanos Mayores de la raza y puedan hacer descender los ideales, tal como son conocidos en los planos superiores, son entrenados cuidadosa, ardua y enérgicamente. Es necesario que sean capaces de actuar exacta y adecuadamente como transmisores e intérpretes.
