---
title: Sobre el desaliento
---

# Sobre el desaliento

> [Tratado sobre magia blanca](/tratado-sobre-magia-blanca/regla-10-2#en341)

Quiero agregar ciertas palabras de advertencia, como también un resumen de lo dicho anteriormente:

Primero, no se aferren a la forma, no importa cual sea. Todas las formas sólo son experimentos y llegan al punto de equilibrio - para luego ser descartadas o vivificadas.

Segundo, recuerden que todas las personalidades (incluso la propia) tienen, de acuerdo a la ley, sus períodos de flujo y reflujo. Los períodos de reflujo, en el caso de quienes mantienen una posición destacada, producen a veces consternación a todos los adictos a sus propias personalidades y no al Dios interno, dentro de su propio corazón.

Tercero, no olviden que así como en la vida del individuo hay períodos en que la visión se oscurece, se atraviesa el valle y la niebla vela las estrellas, lo mismo sucederá en conexión con los grupos. Así mismo, recuerden que después de recorrer el valle (para todos los aspirantes y grupos verdaderamente espirituales) se percibe y asciende al Monte de la Iniciación; después de la oscuridad viene la visión; después de la noche viene el día. En los grandes ciclos que afectan a los grupos cósmicos también puede observarse esto; en los ciclos menores que <Pin lang="es">249</Pin> controlan la raza, sucede lo mismo y persisten iguales leyes en todos los grupos menores, descendiendo hasta los grupos de diminutas vidas que predominan en los vehículos del hombre. Debe ponerse énfasis sobre esto.

Cuarto, no se dejen dominar por el desaliento. El desaliento se debe a tres causas, siendo la principal el descenso de la vitalidad del organismo corpóreo. Cuando ello ocurre, el cuerpo astral exige demasiado al físico, y en el esfuerzo por responder y en la presentida incapacidad de hacerlo adecuadamente, reside una de las causas del desaliento. A menudo ataca a quienes poseen un vehículo físico refinadamente organizado. La cura para este tipo de <Pin lang="en">342</Pin> desaliento es evidente. El descanso y el relajamiento, reconstruyen y dan tiempo a la naturaleza para reajustar la dificultad. También el sol revitaliza con prana y debe tenerse esto en cuenta. Después de todo, el sentido común es el requisito especial, y también la comprensión de que nuestro trabajo se ajusta a la propia capacidad y no a la abrumadora necesidad. Reflexionen sobre esto.

Otra base del desaliento es el excesivo desarrollo de la mente concreta, que a su vez exige demasiado a la naturaleza emocional y, en consecuencia, al físico. La capacidad demasiado grande exigida para ver lo que abarca un tema, la comprensión excesivamente desproporcionada respecto a la comprensión de la necesidad del mundo y la captación demasiado rápida de las consecuencias involucradas, en relación con un asunto determinado, producen una vibración violenta en el cuerpo astral. Esto conduce al desmoronamiento del vehículo físico, y al efecto sentido se lo denomina desaliento. Aquí se debe cultivar el sentido de proporción y entra en juego la facultad de equiparar inteligentemente y también de adquirir el equilibrio mental. El restablecimiento reside en comprender que el tiempo, la eternidad, la evolución (llámenlo como quieran), hace que todas las cosas pasen, y que no todo dependa del esfuerzo individual. Es posible que las almas sabias aceleren el buen trabajo, pero no obstante el fin es seguro. Si las almas sabias no aparecen, la fuerza de la evolución hará que todas las cosas sucedan, aunque con mayor lentitud. No olviden esto, pero cuando los domine el desaliento, proveniente de causas mentales, adquieran tranquilidad y perciban en la contemplación, la realización final de ese gran factor, el Tiempo.

Una tercera causa reside en reinos más esotéricos, mediante el equilibrio de los pares de opuestos. Cuando oscila el péndulo - y debe oscilar y lo hace - hacia lo que llamamos oscuro, maligno e indeseable, produce tensión en quienes están orientados hacia la luz, trayendo como resultado malestar en todos los <Pin lang="es">250</Pin> cuerpos, y es <Pin lang="en">343</Pin> sentido especialmente como depresión por el cuerpo físico. Cuanto más sensible es el cuerpo, mayor su respuesta a esta forma de tentación. Es una de las cosas que más obstaculiza al aspirante. El aspecto forma lo hace negativo y receptivo y aminora su vibración. Impide la realización, y como consecuencia sufre el servicio que debe prestar al mundo. El remedio para el desaliento no se encuentra en el cultivo de una vibración violenta contraria, reside en el inteligente empleo del cuerpo mental, en la capacidad del razonamiento lógico y en ver que la causa de las condiciones se halla en su propia personalidad o en su medio ambiente. Así se logra equilibrio, y, como ya se ha dicho, hay que saber considerar que el Tiempo lo resuelve todo. También radica en el aquietamiento de la mente concreta y la consiguiente vinculación con el alma y, por intermedio del alma, con el grupo egoico, y en consecuencia con el Maestro. Nunca se debe olvidar que el contacto con el Maestro se efectúa en este orden, y quien se halla cada vez más guiado por el alma, penetra progresivamente en la conciencia de su Maestro.

Después de haberse unido desinteresadamente con el Maestro, viene el esfuerzo deliberado y concentrado para trabajar con desapasionamiento y sin ningún deseo de ver el fruto de la acción. Si se continúa durante mucho tiempo y se insiste con paciencia en este procedimiento, traerá como resultado un equilibrio que nada podrá quebrar.
