---
title: Liberación de las formas mentales
---

# Liberación de las formas mentales

> [Tratado sobre magia blanca](/tratado-sobre-magia-blanca/regla-11#la-liberación-de-nuestras-formas-mentales)

Hablo ahora para los aspirantes que, mediante la concentración y la meditación, están adquiriendo poder mental. Hablo para los pensadores del mundo que, por su centralizada atención y devoción hacia los negocios, la ciencia, la religión o los diversos modos de actividad humana, han orientado sus mentes (no las emociones, sino las mentes) hacia una constante actividad que lógicamente es parte de la actividad divina en un amplio sentido.

Precisamente aquí, en la utilización del pensamiento, puede verse la diferencia entre la magia negra y la magia blanca. Egoísmo, crueldad, odio e impiedad, caracterizan al trabajador en sustancia mental, cuyos móviles están centralizados, durante muchas vidas, en su propio engrandecimiento, enfocados en la adquisición personal de posesiones y dirigidos por entero al logro de placeres y satisfacciones, no importa lo que acontezca a los demás. Tales hombres son afortunadamente pocos, pero el camino hacia ese punto de vista es fácilmente asequible y muchos necesitan protegerse para no encaminarse irreflexivamente hacia el materialismo.

El gradual y constante crecimiento de la conciencia y responsabilidad grupales; el sometimiento de los deseos del <Pin lang="en">482</Pin> yo personal y la manifestación de un espíritu amoroso, caracterizan a quienes están orientados hacia la vida del divino todo. Puede decirse que los seres humanos tienen cabida en tres grupos principales:

1. La gran mayoría no siendo buenos ni malos, son simplemente irreflexivos y están completamente sumergidos en la <Pin lang="es">350</Pin> marea evolutiva, en el trabajo de desarrollar una verdadera conciencia del yo y en la necesidad de capacitarse.
2. Un pequeño, muy pequeño número, que definida y conscientemente trabaja en el aspecto materialista o del mal - si prefieren expresarlo así. Son poderosos en el plano físico, pero su poder es temporal y no eterno. La ley del universo, que es la ley del amor, está eternamente contra ellos, y del mal aparente surgirá el bien.
3. Un número considerable de precursores del reino del alma, exponentes de las ideas de la nueva era y custodios de ese aspecto de la Sabiduría Eterna, que será próximamente revelado a la humanidad. Este grupo está constituido por hombres y mujeres altruistas e inteligentes en todos los campos del esfuerzo humano, por los aspirantes y discípulos, por los iniciados que emiten la nota para los distintos grupos y tipos y por la oculta Jerarquía misma. La influencia de este grupo de místicos y conocedores es excesivamente grande y la oportunidad de trabajar en colaboración con él en esta época, es más fácil de obtener que en cualquier otra época en la historia de la raza.

El primer grupo es irreflexivo, los otros dos grupos comienzan a pensar y a emplear las leyes del pensamiento. Me ocuparé del empleo del pensamiento por el aspirante. Mucho sobre el pensamiento encontrarán en Tratado <Pin lang="en">483</Pin> sobre Fuego Cósmico, pero intentaré dar algunas ideas y sugerencias prácticas que ayudarán al aspirante común a trabajar debidamente.

Recordaremos ante todo que ningún aspirante está libre de faltas, no importa cuán sincero y devoto sea. Si lo estuviera, sería un adepto. Todos los aspirantes son aún egoístas, propensos al mal genio y a la irritabilidad, a momentos de depresión y a veces hasta sentir odio. Con frecuencia ese mal genio y odio puede ser despertado por lo que podríamos llamar causas justas. Injusticias por parte de otros, crueldad hacia seres humanos o animales, odio y depravación hacia los semejantes, hacen despertar en ellos las reacciones correspondientes, ocasionándoles mucho sufrimiento y demora. Una cosa hay que tener siempre en cuenta. Si un aspirante siente odio por un compañero, si demuestra mal genio y encuentra aversión y antagonismo, es porque no es totalmente inofensivo; hay en él todavía la simiente de las dificultades, pues es ley de la naturaleza recibir lo que damos y producir reacciones de acuerdo a nuestra actividad física, emocional o mental.

Hay ciertos tipos de hombres que no caen dentro de esta categoría. Cuando un hombre ha llegado a una etapa de elevada iniciación, el caso es diferente. Las ideas simientes que trata de trasmitir, <Pin lang="es">351</Pin> el trabajo que está autorizado a hacer, la empresa precursora que trata de llevar adelante, puede provocar - y a menudo lo hace - odio y furia por parte de quienes no sienten la belleza de su causa y la exactitud de la verdad que enuncia, y de lo cual no es responsable personalmente, causándole muchos trastornos. Este antagonismo procede de los reaccionarios y los fanáticos de la raza, y debe tenerse en cuenta que es en gran parte impersonal, aun cuando está enfocado sobre él como representante de una idea. Pero no me refiero a estas almas elevadas, sino a los estudiantes de la Sabiduría Eterna que están aprendiendo, no sólo que raras veces piensan, sino que cuando lo hacen, con frecuencia piensan <Pin lang="en">484</Pin> erróneamente, porque son forzados a una actividad mental por reacciones que residen en sus naturalezas inferiores, basadas en el egoísmo y la falta de amor.

Hay tres lecciones que todo aspirante debe aprender:

1. Primero, que él construya cada forma mental bajo el impulso de alguna emoción o deseo; en casos muy raros puede ser construida en la luz e incorporar por lo tanto alguna intuición. Pero en la mayoría, el impulso motivador que despierta la materia mental a la actividad, es emocional, o también un potente deseo que puede ser bueno o malo, egoísta o altruista.
2. Segundo, se debe tener en cuenta que la forma mental así construida puede quedar dentro de su propia aura, o encontrar su camino hacia un objetivo presentido. En el primer caso, dichas formas mentales formarán parte de una densa pared, que lo rodeará completamente o constituirá su aura mental, y acrecentará en poder a medida que fija su atención en ella; podrá ser tan grande que le oculte toda realidad, o tan dinámica y potente que resulte víctima de lo que ha construido. La forma mental será más poderosa que su creador, de manera que llegará a obsesionarle sus propias ideas y a ser impulsado por sus propias creaciones. En el segundo caso su forma mental encontrará su camino hacia el aura mental de otro ser humano o grupo. He aquí la simiente del trabajo mágico maligno y la imposición de una poderosa mente sobre otra más débil. Si ésta halla su camino en algún grupo, formas análogas impulsivas (encontradas dentro del aura del grupo) se unirán a ella, teniendo el mismo valor o medida vibratoria. Entonces ocurrirá lo mismo que tuvo lugar en el aura grupal y sucedió dentro del "círculo infranqueable" individual - el grupo tendrá a su alrededor un muro separador de formas mentales y estará obsesionado por alguna idea. Aquí tenemos la clave de todo sectarismo y fanatismo, y de alguna forma de locura, individual o grupal.
3. <Pin lang="en">485</Pin> Tercero, el creador de la forma mental (en este caso un <Pin lang="es">352</Pin> aspirante) es responsable. La forma permanece vinculada a él por su propósito vital y en consecuencia, por el karma de los resultados, correspondiéndole el trabajo final de destruir aquello que ha creado. Esto es verdad respecto a toda idea encarnada, tanto buena como mala. El creador de todas ellas es responsable por el trabajo de su creación. El Maestro Jesús, por ejemplo, tiene aún que enfrentarse con las formas mentales que denominamos la Iglesia Cristiana, y tiene mucho que hacer. El Cristo y el Buda tienen todavía algún trabajo que consumar, aunque no con las formas que encarnan sus principios enunciados, sino con las almas que han evolucionado mediante la aplicación de esos principios.

 Sin embargo, el problema es diferente con el aspirante que aún está aprendiendo a pensar. Tiende a utilizar la materia mental para encarnar su comprensión equívoca de las verdaderas ideas, tiende a expresar sus simpatías y antipatías mediante el poder del pensamiento; se siente inclinado a utilizar la materia mental para lograr los deseos de la personalidad. Esto lo atestiguará todo aspirante sincero.

Muchos de ustedes controlan demasiado sus pensamientos y protegen la formulación de las ideas. Algunos pensamientos son ideas, revestidas de materia mental y residen en el plano de materia mental. Éstas son las concepciones abstractas y los hechos apenas percibidos de la vida oculta interna o mística, que pasan a través de la mente del pensador. No son tan difíciles de proteger, por ser sus vibraciones tan elevadas y sutiles que pocas personas tienen el poder de revestirlas adecuadamente de materia mental, y su número es tan reducido que no es mayormente grande el riesgo de que tales expresiones sean imprudentemente propaladas.

Además la enseñanza oculta implica las comunicaciones. El círculo de los que las captan se está ampliando, y esas formas mentales frecuentemente <Pin lang="en">486</Pin> atraen hacia sí y llevan al corazón del estudiante la materia astral del deseo con el fin de verificar, corroborar y participar con el grupo, cuyo conocimiento es tan vital como el suyo. A veces esto es posible y otras no. Si se prohibe, ¿cuál será entonces el medio de protección? En gran parte no permitir que la materia del plano astral se adhiera a la forma mental. Combatir la cuestión en el nivel del deseo e impedir se forme ese tipo de materia. Donde no existe deseo de hablar y donde el esfuerzo va dirigido a evitar la acumulación de materia alrededor del núcleo, se produce otra forma mental que interviene y protege.

Aún surge otro tipo de forma mental - el más predominante y causa de la mayor parte de los trastornos. Éstos son la información, <Pin lang="es">353</Pin> el material detallado, las noticias (si así prefieren llamarlo), base de lo que puede degenerar en habladurías referentes al trabajo administrativo y de otra índole, y aquello que concierne a otras personas. ¿Cómo evitar que la mente no trasmita hechos como éstos? Ellos tienen su origen en los acontecimientos del plano físico, y aquí reside la dificultad. Los hechos internos de la vida oculta y aquellos que se originan en el plano mental no son difíciles de ocultar. No llegan, a ustedes hasta que el templo de las vibraciones sea bastante elevado como para poder captarlas y, por regla general, cuando esto sucede, se posee un carácter y sabiduría suficientemente estabilizado. Pero esto no acontece con un hecho en el plano físico. ¿Qué debe hacerse? Los pensamientos anteriores descienden desde arriba; los posteriores se elevan hacia arriba desde el plano físico y aumentan su vitalidad por el conocimiento de la mayoría, generalmente de la mayoría inculta. Uno se origina nebulosamente en el plano mental; sólo el tipo más elevado de mente puede formularlo y revestirlo de materia con precisión geométrica, y una mente de esta naturaleza tiene por lo general la suficiente sabiduría para no revestirlo de materia del plano astral. Esto no acontece en el plano físico. <Pin lang="en">487</Pin> Cuando se la encuentra y se hace contacto con ella es una entidad vital, ataviada con materia del plano astral y del plano mental. En este caso, ¿la vitalizarían o la detendrían? Se puede detener mediante un impulso y una oleada de amor hacia el sujeto implicado que envuelve a la forma mental y la devuelve a quien la origina, llevada por una emanación de materia astral, de fuerza suficiente como para impulsarla a través y alrededor de ella, tal vez desintegrándola, pero con toda seguridad será devuelta a quien la envió, sin causarle daño. Puede ser una información maligna, una mentira o una habladuría. Desvitalícenla por medio del amor, destrúyanla mediante el poder de una forma mental opuesta, de paz y armonía.

Quizás pueda ser una verdad, un acontecimiento funesto o una mala acción cometida por algún hermano descarriado. ¿Qué hay que hacer entonces? La verdad no puede ser desvitalizada o desintegrada. La Ley de Absorción les ayudará en este caso. Absorban en sus corazones la forma mental que encuentren y trasmútenla mediante la alquimia del amor. Permítanme ser práctico e ilustrar esto, porque la cuestión es de mucha importancia.

Si un hermano les habla de un hecho cualquiera de otro hermano - hecho que el mundo denomina maldad -, ustedes que saben más que el común de los hombres, comprenderán que eso que se llama maldad podrá ser sólo la expiación de karma <Pin lang="es">354</Pin> o tener como base un buen móvil, erróneamente interpretado. No deben agregar nada más a las habladurías, ni propalarlas; de este modo, en lo que a ustedes concierne, la forma mental construida alrededor del hecho ha llegado a un punto muerto.

¿Qué harían entonces? Construir una corriente contraria de pensamientos que enviarán (sobre una ola de amor) al hermano, aparentemente errado: bondadosos pensamientos de ayuda, de valor y aspiración y una inteligente aplicación de la lección que deberá aprender, resultante de la acción cometida. No utilicen la fuerza, porque los pensadores fuertes no deben influenciar a otras mentes, sino enviar una nueva corriente <Pin lang="en">488</Pin> de amor inteligente y transmutador. He aquí tres métodos, ninguno estrictamente oculto, porque éstos, impartidos más adelante, serán asequibles a la mayoría:

1. La forma mental mantenida en los niveles mentales, por ejemplo, la inhibición de la materia del plano astral. - Inhibición
2. La forma mental destruida y desintegrada por una corriente de la fuerza del amor bien dirigida. - Desintegración
3. La absorción de la forma mental y la formulación de un pensamiento contrario de sabiduría amorosa. - Absorción

Hay tres castigos principales que acompañan al erróneo empleo de la sustancia mental y el aspirante debe aprender a resguardarse y evitar esas actividades; oportunamente esto hará que el proceso de liberación sea innecesario:

1. Una forma mental potente puede actuar como un "boomerang". Vuelve a quien la envió para cumplir su misión con mayor intensidad. El odio profundo revestido de materia mental puede retornar a su creador cargado con la energía de la persona odiada, y por lo tanto causa estragos en la vida del aspirante. No odien, porque el odio siempre retorna a su punto de partida. Hay una profunda verdad en el antiguo aforismo: "Tanto las maldiciones como los pollos vuelven a casa a dormir".

 Un gran deseo de posesión material vuelve trayendo inevitablemente lo que ha sido deseado, hallando sólo en la mayoría de los casos que el aspirante ya no tiene el deseo vehemente de posesión, sino que lo considera como una obligación o, al mismo tiempo, ya posee más de lo que necesita; está saciado y no sabe qué hacer con todo lo adquirido.

 Una poderosa forma mental que incorpora la aspiración de iluminación espiritual, o el reconocimiento por parte de un Maestro, puede atraer tanta iluminación como para cegar al aspirante y hacerlo poseedor de una riqueza de energía espiritual <Pin lang="es">355</Pin> para la cual no está preparado <Pin lang="en">489</Pin> ni en condiciones de utilizar. También el aspirante puede ser atraído por la forma mental de uno de los Grandes Seres, y se introduce más profundamente en el mundo de la ilusión y del astralismo. De allí la necesidad de humildad, de anhelo de servir y, por consiguiente, de olvido de sí mismo, si se quiere construir verdadera y correctamente. Tal es la ley.

2. Una forma mental también puede actuar como agente ponzoñoso y envenenar todas las fuentes de la vida. Quizá no tenga fuerza suficiente para salir del aura de su creador (muy pocas formas mentales la tienen) y hallar su meta en otra aura, para acopiar allí fuerzas y volver a su punto de partida, pero puede tener una vitalidad propia capaz de devastar la vida del aspirante. La violenta aversión, la roedora preocupación, los celos, la constante ansiedad o el anhelo por algo o alguien, puede actuar tan potentemente como un excitante o veneno, que echará a perder toda su vida e inutilizará su servicio. Toda una vida se amarga y desvitaliza por la preocupación, el odio y el deseo encarnado en él. Todas las relaciones con otras personas son inutilizadas y hasta nocivas, pues el aspirante preocupado o suspicaz, echa a perder el círculo familiar o el grupo de amigos por su actitud interna ponzoñosa, dominado por una idea. La relación con su propia alma y la fuerza de contacto con el mundo de las ideas espirituales se paralizan, no progresa, queda detenido por el veneno de su sistema mental. Su visión se deforma, su naturaleza se corroe y todas sus relaciones impedidas por los pensamientos agotadores que él mismo ha encarnado en formas, poseen una vida tan poderosa que pueden envenenarlo. No logra librarse de ellas por más que lo intente, aunque vea claramente en teoría la causa de su dificultad. Ésta es una de las formas más comunes de dificultades, porque tiene sus raíces en la vida personal egoísta, frecuentemente tan fluida que parece desafiar la acción directa.
3. El tercer peligro del cual el aspirante debe <Pin lang="en">490</Pin> protegerse es obsesionarse con sus propias ideas encarnadas, ya sean aparentemente correctas o fundamentalmente erróneas. Recuérdese que las ideas correctas son temporarias, y en su oportunidad ocuparán su lugar como verdades parciales, cediéndolo más tarde a verdades mayores. Un hecho del momento es considerado luego como parte de un hecho más grande. Un hombre puede haber captado algunos de los principios menores de la Sabiduría Eterna con mucha claridad, y estar tan convencido de su corrección que, olvidándose del todo mayor, construye una forma mental sobre la verdad parcial que ha visto, lo que se convertirá en una limitación y lo mantendrá prisionero, impidiendo su <Pin lang="es">356</Pin> progreso. Está tan seguro de poseer la verdad, que no puede ver la verdad de otro. Puede estar tan convencido que es real su particular concepto de la verdad que ha llegado a él mediante su propia alma, matizada por su rayo y construida en cierta forma por su mente personal separatista, que olvida las limitaciones de su propio cerebro. Sólo vive para esa pequeña verdad, no puede percibir otra; quiere inculcar su forma mental a otras personas, y se convierte en una fanático obcecado y mentalmente desequilibrado, aunque el mundo lo considera cuerdo.

¿Cómo puede el hombre resguardarse de estos peligros? ¿Cómo podrá mantener el equilibrio que le permita juzgar correctamente y conservar el contacto mental con su alma y las de sus semejantes?

Primero y ante todo, mediante la constante práctica de la Inofensividad. Esto implica inofensividad en la palabra, en el pensamiento y en consecuencia en la acción. Es una inofensividad positiva, que significa constante actividad y vigilancia, no es una tolerancia negativa y fluida.

Segundo, cuidar diariamente los pensamientos y supervisar la vida mental. No se permitirán ciertas líneas de pensamiento; viejos hábitos mentales deben ser neutralizados por un pensar constructivo <Pin lang="en">491</Pin> y creador; ciertas ideas preconcebidas (obsérvese el valor esotérico de esta frase) serán relegadas a segundo término para poder visualizar los nuevos horizontes y penetrar en las nuevas ideas. Esto significa una constante vigilancia diaria, hasta que los viejos hábitos hayan sido vencidos y el nuevo ritmo establecido. Entonces el aspirante descubrirá que la mente está tan enfocada sobre las nuevas ideas espirituales, que las viejas formas mentales dejarán de llamarle la atención y morirán por inanición. Éste pensamiento es alentador. El trabajo de los primeros tres años será el más arduo. Después, la mente será acaparada por las ideas y no por las formas mentales.

Tercero, rehusará vivir en el mundo de los propios pensamientos y entrará en el mundo de las ideas y corrientes de pensamientos humanos. El mundo de las ideas es el mundo del alma y de la mente superior. La corriente de pensamientos humanos y opiniones, pertenece a la conciencia pública y a la mente inferior. El aspirante debe actuar libre en ambos mundos. Obsérvese esto cuidadosamente. No significa que debe actuar libremente, lo cual implica la idea de facilidad, sino que debe actuar como un agente libre en ambos mundos. De la meditación constante diaria obtiene lo primero, y mediante lecturas generales y el interés y comprensión lo segundo.

Cuarto, debe aprender a desprenderse de sus propias creaciones <Pin lang="es">357</Pin> mentales y librarlas a fin de que cumplan el propósito para el cual él inteligentemente las envió. Este cuarto proceso se divide en dos partes:

1. Mediante una frase mística, corta el vínculo que retiene una idea incorporada en su aura mental.
2. Desligando su mente de la idea, una vez que la ha enviado a cumplir su misión, aprende la lección del Bhagavad Gita y "trabaja sin apegos".

Estos dos puntos variarán de acuerdo al crecimiento y posición del aspirante. Cada uno, por sí mismo, formulará <Pin lang="en">492</Pin> su propia "frase de ruptura" y aprenderá por sí solo y sin ayuda, a apartar su mirada de los tres mundos en los cuales trabaja, en su esfuerzo por impulsar la idea del trabajo que debe realizar. También ha de aprender por sí mismo a apartar su atención de la forma mental que ha construido, donde está encarnada esa idea, sabiendo que mientras viva como alma y la energía espiritual fluya a través de él, su forma mental expresará la idea espiritual y llevará a cabo su trabajo. Se mantiene unida por la vida del alma y no por el deseo de la personalidad. Los resultados tangibles siempre dependen del impulso de la fuerza espiritual que anima la idea encarnada en su forma mental. Su trabajo reside en el mundo de las ideas y no en los efectos físicos. Automáticamente los aspectos físicos responderán al impulso espiritual.
