---
title: Uso de la imaginación en la meditación
---

# Uso de la imaginación en la meditación

> [Del intelecto a la intuición](/del-intelecto-a-la-intuicion/la-practica-de-la-meditacion#es136)

El siguiente paso en la práctica de la meditación es el empleo de la imaginación. Nos imaginamos al triple hombre inferior alineado, o en comunicación directa con el alma. Hay varias maneras de hacerlo. A esto lo llamamos práctica de la visualización. La visualización, la imaginación y la voluntad, <Pin lang="en">224</Pin> parecen ser tres factores muy potentes en todo proceso creador. Son las causas subjetivas de muchos de nuestros efectos objetivos. Al principio la visualización es en gran parte cuestión de fe experimental. Sabemos que mediante el proceso de razonamiento, llegamos a la comprensión de que dentro y más allá de los objetos manifestados, existe un objeto o canon ideal, que está tratando de manifestarse en el plano físico. La práctica de la visualización, la imaginación y el empleo de la voluntad, son actividades calculadas para acelerar la manifestación de este ideal.

Al visualizar, utilizamos nuestra concepción más elevada de lo que ese ideal puede ser, revestido de cierto tipo de materia, generalmente mental, pues aún somos incapaces de concebir formas y tipos más elevados de sustancia con la cual envolver nuestras imágenes. Al imaginar un cuadro, la sustancia mental de nuestra mente establece cierto ritmo de vibración que atrae hacia sí el correspondiente grado de sustancial mental, en que la mente está sumergida. La voluntad mantiene esta imagen fija y le da vida. Este proceso continúa, seamos o no capaces de verlo con el ojo mental. No tiene importancia que podamos o no verlo, porque el trabajo creador se realiza igualmente. Quizás podamos alguna vez seguir y ejecutar conscientemente todo el proceso.

En conexión con este trabajo, en la etapa del <Pin lang="en">225</Pin> principiante, algunas personas se imaginan a los tres cuerpos (los tres aspectos de la naturaleza forma) vinculados por un cuerpo radiante de luz, o visualizan tres centros de energía vibrante que recibe el estímulo de un centro más elevado y poderoso; otros imaginan al alma como un triángulo de fuerza, unido al triángulo de la naturaleza inferior —vinculado por el "cordón plateado", mencionado en la Biblia cristiana, el sutratma o hilo del alma de las escrituras orientales, la "línea de la vida" de otras escuelas de pensamiento. En cambio otros mantienen la idea de una personalidad vinculada con la divinidad que mora internamente, ocultando en sí misma a esa divinidad, "Cristo en nosotros, esperanza es de gloria". Tiene poca importancia la imagen elegida, siempre que se <Pin lang="es">137</Pin> inicie con la idea fundamental de que el yo trata de establecer contacto con el no-yo, utilizar su instrumento en los mundos de la expresión humana y viceversa, impulsar al pensamiento de ese no-yo para que se dirija hacia la fuente de su ser. Mediante el empleo de la imaginación y la visualización, el cuerpo de deseos, o naturaleza emocional, se alinea con el alma, y una vez realizado, puede continuarse con la práctica de la meditación. El cuerpo físico y la naturaleza de deseos se sumergen a su vez bajo el nivel de la conciencia, entonces nos centramos en la mente y tratamos de someterla a nuestra voluntad.

Precisamente aquí enfrentamos el problema. La mente se niega a amoldarse a los pensamientos que decidimos pensar, y recorre todo <Pin lang="en">226</Pin> el mundo en su acostumbrada búsqueda de temas. Pensamos en lo que vamos a hacer durante el día, en lugar de reflexionar sobre nuestro "pensamiento simiente"; recordamos a alguien a quien debemos ver o alguna actividad que demanda nuestra atención; empezamos a pensar en algún ser querido, e inmediatamente descendemos al mundo de las emociones, debiendo empezar el trabajo de nuevo. De manera que reunimos nuevamente nuestros pensamientos y los retomamos con mucho éxito durante medio minuto, pero de pronto recordamos una cita o una diligencia que alguien está gestionando y volvemos otra vez al mundo de las reacciones mentales, quedando olvidada la línea de pensamientos. Nuevamente reunimos nuestras ideas diseminadas y retomamos la tarea de someter a la mente obstinada.
